### ISSUE TITLE
TenantRoute error - the same controller name in different modules results in an AmbiguousActionException

### ISSUE THREAD

**Issue by timmahon** [OrchardCMS/Orchard2#103]
The TenantRoute doesn't seem to be taking the module name into consideration when trying to decide which route should be used.  If a module contains a controller name (for instance AdminController) that is the same name controller but in another module, both controllers seem to be getting matched which results in an AmbiguousActionException.

To repro, create two modules Orchard.Module1 and Orchard.Module2, add a controller to each module TestModuleController with a single action Index, and add these to the running shell.  When trying to route to either 

```
http://localhost:5001/Orchard.Module1/TestModule/Index
http://localhost:5001/Orchard.Module2/TestModule/Index
```

the following exception occurs:-

```
fail: Microsoft.AspNet.Mvc.Infrastructure.DefaultActionSelector[0]
      Request matched multiple actions resulting in ambiguity. Matching actions: Orchard.Module1.Controllers.TestModuleController.Index
      Orchard.Module2.Controllers.TestModuleController.Index
fail: Orchard.Hosting.Web.Routing.Routes.TenantRoute[0]
      Error occured serving tenant route
      Microsoft.AspNet.Mvc.Infrastructure.AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:

      Orchard.Module1.Controllers.TestModuleController.Index
      Orchard.Module2.Controllers.TestModuleController.Index
         at Microsoft.AspNet.Mvc.Infrastructure.DefaultActionSelector.SelectAsync(RouteContext context)
         at Microsoft.AspNet.Mvc.Infrastructure.MvcRouteHandler.<RouteAsync>d__6.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at Microsoft.AspNet.Routing.Template.TemplateRoute.<RouteAsync>d__27.MoveNext()
      --- End of stack trace from previous location where exception was thrown ---
         at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
         at Orchard.Hosting.Web.Routing.Routes.TenantRoute.<RouteAsync>d__4.MoveNext() in C:\work\Orchard2\src\Orchard.Hosting.Web\Routing\Routes\TenantRoute.cs:line 46
```

**Comment by sebastienros** [comment]
The area must be missing somewhere ... will look at it.

**Comment by timmahon** [comment]
It works if you put an area on the controller, so I think you are right...
```
[Area("Orchard.Module1"]
public class TestModuleController : Controller {
```
but this isn't ideal...

**Comment by timmahon** [comment]
After a bit of thought, I don't think this issue is a bad thing - while it helps with development to be able to access a controller via Module/Controller/Action is this actually a good thing in practice and production environments?

I guess the convention originated in the need for Scripts/Content/Styles to be accessible via the front end.  With FileProviders in the new ASPNET is this now required?

Should we not encourage people to actually use real routes (via IRouteProvider) to their controllers rather than rely on this convention?

If so then it would be easier to separate Admin routes and front end UI routes which could open some interesting scenarios:-

1. switch off admin routes
2. ability to have a separate admin tenant (think site.azurewebsites.net and site.scm.azurewebsites.net)
3. ability to move the admin to a different location (it's currently hardcoded as "Admin" in Orchard 1.x)

Suggestion would be to remove the Module/Controller/Action convention (other than dev) and replace IRouteProvider with a different interface

```
public interface IRouteProvider : IDependency 
{
    IEnumerable<RouteDescriptor> GetRoutes();
    IEnumerable<RouteDescriptor> GetAdminRoutes(string adminPrefix);
}
```

**Comment by sebastienros** [comment]
I think we need to assign the area automatically when we discover controllers. I was not sure if MVC would do it by itself.

**Comment by sebastienros** [comment]
It should be fixed now there is a convention for getting the area from the module name. It's not yet on master.
