### ISSUE TITLE
InvalidOperationException at YesSql.Core.Services.Session.Dispose() (+ possible fix).

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard2#106]
This when shut down the app (after having done at least one request).

Possible fix in `OrchardContainerMiddleware.cs`, replace this:

                ...
                using (scope)
                {
                    ...
                }
                ...

With:

                ...
                using (scope)
                {
                    using (shellContext)
                    {
                        ...
                    }
                }
                ...

This to call the `shellContext.Dispose(bool disposing)` through its `IDisposable.Dispose()`. Not through the `~ShellContext()` destructor (see in `ShellContext.cs`)...

Not sure it's a good fix. If so, I can do a PR...

Best

**Comment by sebastienros** [comment]
`using(scope)` is to release the scoped resources after every requests.
The `shellContext` lives for the whole tenant's life, so this can't be right. 

Now if it fixes the issue it means something in `ShellContext` is preventing a connection from begin freed, and it should be done at the end of the request (with the scope). Apparently the `ServiceProvider` is disposed there, so I will assume this is what is holding the connection. But this should be the Application level SP, so it shouldn't have a connection. Maybe the `IStore` implementation has something like this, but it shouldn't, looking into it.

**Comment by sebastienros** [comment]
It appears to be when MvcOptions are processed and resolve an `IRazorViewEngine` that a new `ISession` is requested, from the ApplicationService. I don't what is requiring it, or why ApplicationService is used in this case.

**Comment by Jetski5822** [comment]
Something to do with AdminMenuFilter?

**Comment by sebastienros** [comment]
Will look, but the View was rendered after the resoltuion ofthe session, thought about it, will see ...
