### ISSUE TITLE
Arguments, should we still use Argument.cs

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Orchard2#111]
So at the moment we have a helper called Argument.cs, do people prefer

if (from.Length != to.Length)
{
    throw new ArgumentNullException(nameof(from), "Parameters must have the same length");
}

or

Argument.Validation(from.Length != to.Length, nameof(from), "Parameters must have the same length")

I like the second one as its less code, but... not sure. What do people think?

**Comment by sebastienros** [comment]
I prefer the first as it's more explicit, and doesn't require much more typing.

**Comment by MpDzik** [comment]
I agree with @sebastienros.

**Comment by Jetski5822** [comment]
Sounds good, its what the asp net team are doing. I think the corefx team do a mixture... Im going to get rid of the Argument.cs class and the Validation module that proceeds
