### ISSUE TITLE
Unauthorized editing wiki pages 

### ISSUE THREAD

**Issue by Ermesx** [OrchardCMS/Orchard2#112]
Hi,
I'm not sure if it's correct but when I read the Engineering Guidelines I noticed that I can edit that page.
<img width="1014" alt="zrzut ekranu 2016-01-02 o 19 31 59" src="https://cloud.githubusercontent.com/assets/5731890/12075685/4e1ed6e6-b188-11e5-94bd-4e2d63b08eb2.png">
For test I put dot on end of page and it looks like I can save it even when I'm not a member of orchard2 repo. Look:
<img width="728" alt="zrzut ekranu 2016-01-02 o 19 36 09" src="https://cloud.githubusercontent.com/assets/5731890/12075693/9b0bb4b0-b188-11e5-8742-01224820cbef.png">
I think editing should be blocked for others.
<img width="1023" alt="zrzut ekranu 2016-01-02 o 19 36 20" src="https://cloud.githubusercontent.com/assets/5731890/12075694/9d5c678c-b188-11e5-82bf-6b0ea072b448.png">

**Comment by Jetski5822** [comment]
Eeeek good catch! Must have missed that checkbox on setup, thanks for letting us know. N
