### ISSUE TITLE
Check that IMemoryCache registration is tenant aware

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#114]
I am not sure there is a single memory cache store per tenant, which is mandatory. I think we are currently depending on MVC default registration.

**Comment by jtkech** [comment]
@sebastienros just for infos if it can help.

As i understand in `OrchardContainerMiddleware.cs` we create an `IServiceScopeFactory` as a child / request scope... And we have:

    httpContext.RequestServices = scope.ServiceProvider;

Before, we get a shell context and we are at the shell / tenant level, and we have:

    httpContext.ApplicationServices = shellContext.ServiceProvider;

Finally, if before i do the following, i think I can memorize the real app level services.

    var appServices = httpContext.ApplicationServices;

That said, i've resolved an `IMemoryCache` through the request scope.

    var test = scope.ServiceProvider.GetService<IMemoryCache>();

Then, i can see that this service isn't resolved from this scope but from its `_root` one that is the `shellContext.ServiceProvider` at the shell / tenant level, and is marked as a `Singleton`. And, at the app level, i don't see this service in the `_resolved` list of my `appServices` variable.


**Just tried with 2 tenants** (not so easy to create a 2nd tenant, i didn't remember that shellsetting is now as a POCO where we have to put empty fields...), where i've used this:

                    var test1 = scope.ServiceProvider.GetService<IMemoryCache>();
                    var test2 = test1.Get("Test");
                    test1.Set("Test", shellSetting.Name);

Then, on each tenant request, in the `test2` variable, i retrieve the right tenant name set on the previous request of the same tenant. Seems to be good, right?

Best

**Comment by sebastienros** [comment]
Have you tried after I have pushed and closed the issue?

**Comment by jtkech** [comment]
The last commit of my version is: `Refactored shape cache`

**Comment by sebastienros** [comment]
Please try with the updated code then.

**Comment by jtkech** [comment]
@sebastienros 

So it's before this one: `Explicitly set default IMemoryCache lifetime`

But not 100% sure of my tests

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/Orchard2/commit/81c16ae7dc2060c52952578c9b74cca451b8d49d

**Comment by jtkech** [comment]
Yes I will try with the last update

**Comment by jtkech** [comment]
Not related to your recent commit, but with 2 tenants, many times i have loading extensions exceptions and i need to restart the app...

But when it works, with 81c16ae,  i get the same behavior with IMemoryCache that seems to be right.

**Comment by jtkech** [comment]
@sebastienros 

I've re-tried it by using the same object for the cache key.

    private readonly object _key = new object();

And seems to work well with or without your commit.

For the startup issue with 2 tenants, i got e.g this message:

    Loader scopes disposed in wrong order

Seems to be due to shells activations in concurrent tasks. If in `DefaultOrchardHost.cs`, where shells are activated, I replace this:

    Parallel.ForEach(allSettings, settings =>

with a regular foreach:

    foreach (var settings in allSettings)

It works.

I'll keep looking if there is a solution to activate shells in parallel...


Best
