### ISSUE TITLE
Multi-tenancy stress

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#118]
I was able to run around a thousand tenants for a little more than a GB. After that, it's still fast but I can definitely see it's slower even targeting a single tenant.
There needs some investigation as it should not impact that much the perf. Maybe some code is not clever at handling that many tenant, some profiling with a single thread should tell.

**Comment by jtkech** [comment]
@sebastienros 

Not sure we can do this but, in an experimental test with only 2 tenants, if in `ExtensionAssemblyLoader.cs` we always use the same `CompilationCache` (used to create a new `CompilationEngine` in the `Assembly Load()` method), then the first request is much faster and uses less memory...

Maybe some potential thread safety issues by using the same compilation cache... But, i've seen that the `Assembly Load()` method is first called at the host level (i think there is no concurency problem here), and at the tenant levels, i think it's ok because now you use a `Lock { }` in the `ExtensionManager LoadFeature()` method...

If you want to give it a try, see this PR #120

Best

**Comment by sebastienros** [comment]
I don't think its related to compilation or extensions as at this point everything is cached. What needs to be done is __use a profiler__ and see where the bottleneck is when there are hundreds of tenants. It will show the code that is not adapted for this amount of tenants, it could be the RunningShellTable resolution for instance, but only a profiler can tell.

**Comment by jtkech** [comment]
@sebastienros  Ok, which profiler do you recommend?

Just for infos, after some others tests with 2, 3, 4, 5 tenants, it seems that my update is more effective when the number of features increases, rather when the number of tenants increases.

But for infos, before the update => 15 s and 320 Mb.
After the update => 9 s and 200 Mb.

**Comment by sebastienros** [comment]
I think I just fixed the issue by fixing the fact that the routes were all used and were checking the shellsettings, as they were all registered at the top level. The more shellsettings the more tests were made. There is still some optimization to make, which I commented in the code, by having a single root IRouter that would do a lookup by ShellSetting to find the correct tenant route. Right now there is one top route per tenant.

**Comment by jtkech** [comment]
Wow,

Returned back to Orchard2, after a quick look i've seen that **routes publishing and routes table updating** occur only once per tenant, this **on the 1st request that match a given tenant**. So, seems ok right now.

Then, the routes table of a selected tenant is naturally used... E.g, in `TenantRoute.RouteAsync()` i could remove this line `if (IsValidRequest(context.HttpContext))` that check the `ShellSettings`.

But maybe you meant that it would be better **to do all the routes job for all tenants in one time**. As it is done in `Orchard 1` when all shells are not only registered but also started through `ActivateShell()`.

Last thing, is it normal that `IRouteProvider` is an `ISingletonDependency`? In Orchard 1, it's an `IDependency`.

Best.

**Comment by sebastienros** [comment]
> i've seen that routes publishing and routes table updating occur only once per tenant

Correct, tenants are kind of "lazy loaded".

> i could remove this line if (IsValidRequest(context.HttpContext))

This is part of my comment, right now it's expected as all root routes are evaluated in order. And the root routes are `TenantRoute` instances (one per tenant), so we need to check for each call.
But my comment also explain how to improve it, by having a single root route that would have indexed this list of `TenantRoute` per tenant name so that we don't need to _scan_ all the tenant routes on every request. It's even more important once we run a lot of tenants.

> is it normal that IRouteProvider is an ISingletonDependency

Yes, on purpose as it is used once, and I don't want any component depending on it to become more fine grained dependencies. For instance it was a transient and another component depended on this then it would itself become transient.

**Comment by jtkech** [comment]
Thanks for your explanations.

But in `OrchardRouterMiddleware` this is the right `IRunningShellRouterTable` that is used for the tenant previously selected in `OrchardContainerMiddleware`... So, on each request,  `TenantRoute.RouteAsync()` is called only once for the right tenant and, as i understand, without having to check `IsValidRequest(context.HttpContext)`.

The main difference i see is in `DefaultOrchardHost.ActivateShell()`. In Orchard 1, `context.Shell.Activate()` is called to activate the shell, so, on the 1st request this is done for all tenants in one time. In Orchard 2, a tenant is activated in `OrchardContainerMiddleware` through the activating event, but here this only occurs on the 1st request that match this tenant.

I could try to do something here by adding this in `ActivateShell()` for each tenant in their own created scope... But maybe i misunderstood something here.

Best

**Comment by sebastienros** [comment]
I will try to understand why you are mentioning the check is not necessary.

There is nothing to do on `ActhivateShell()` for now.

**Comment by jtkech** [comment]
Sorry, here i was thinking we could update the shell routes table (actually named `RunningShellRouterTable`). The idea was to have a longer global first request, but after a faster 1st request on each tenant.

Not sure it would be better, but i thought that was what you wanted.

**Comment by jtkech** [comment]
So, just for testing, i've tried the following that works. But again not sure it's a good direction to activate all tenants in one time instead of doing it one by one when they are 1st requested.

At the end of `ActivateShell()` i've added this:

            if (_shellContexts.TryAdd(context.Settings.Name, context))
            {
                _runningShellTable.Add(context.Settings);

                // Evolutive
                using (var scope = context.CreateServiceScope()) {

                    if (!context.IsActivated) {
                        lock (context.Settings) {
                            // The tenant gets activated here
                            if (!context.IsActivated) {
                                var eventBus = scope.ServiceProvider.GetService<IEventBus>();
                                eventBus.NotifyAsync<IOrchardShellEvents>(x => x.ActivatingAsync()).Wait();
                                eventBus.NotifyAsync<IOrchardShellEvents>(x => x.ActivatedAsync()).Wait();

                                context.IsActivated = true;
                            }
                        }
                    }
                }
            }

And at the end of `ActivatingAsync()` i've added this:

            // Evolutive
            var routerTable = _serviceProvider.GetService<IRunningShellRouterTable>();

            var router = routerTable.GetOrAdd(
                _shellSettings.Name,
                name => _serviceProvider.GetService<IRouteBuilder>().Build()
            );

            return Task.CompletedTask;

Best.
