### ISSUE TITLE
Inside a zone shape template, we should be able to access any other zone or subzone shape using its 'path' in the shapes hierarchy

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard2#126]
Something as Content.Content.Header

**Comment by sebastienros** [comment]
Already done, even in O1. You can always go to Layout and navigate the shapes from there.

**Comment by CSurieux** [comment]
Not subzones ? I can't have it working in 01.
Layout.Content.Content.Header is nok

**Comment by sebastienros** [comment]
That should work, definitely.
