### ISSUE TITLE
It seems that Orchard 2 uses Sass for its css ?

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard2#131]
I would be interested in a possibility to keep something from all the Less code I have in Orchard 1.
Less was the reco for Orchard 1, why changing ?

**Comment by Jetski5822** [comment]
Why do you want to keep Less? We are using the latest Bootstrap theme that is Sass....

**Comment by sebastienros** [comment]
There isn't any decision made or to be made, as Nick explains in this specific case bootstrap 4 uses scss so having a theme based on this requires the scss. The one on the front end uses bootstrap 3 and hence less.
