### ISSUE TITLE
WebApi

### ISSUE THREAD

**Issue by GVX111** [OrchardCMS/Orchard2#132]
Can i make WebApi Controller in Orchard module  and register api route with Routeattribute?

**Comment by GVX111** [comment]
I fixed. @Jetski5822 

<pre> _routeBuilder.Routes.Insert(0, AttributeRouting.CreateAttributeMegaRoute(_routeBuilder.DefaultHandler, _routeBuilder.ServiceProvider));</pre>
line in 44 file https://github.com/OrchardCMS/Orchard2/blob/0c374167350f62bec6fab5160794ec35244680ed/src/Orchard.Hosting.Web/Routing/Routes/RoutePublisher.cs

**Comment by Jetski5822** [comment]
Whoah sweet, wanna do a PR? or would you prefer I patch it?

**Comment by GVX111** [comment]
If you can patch.

**Comment by GVX111** [comment]
also need to add in MvcCore AddJsonFormatters and AddApiExplorer
