### ISSUE TITLE
when orchard2 released?

### ISSUE THREAD

**Issue by RahimGashti** [OrchardCMS/Orchard2#133]
hello
I want use orchard, but when orchard2 released?
can use this project instead of orchard 1.9.2?

**Comment by Jetski5822** [comment]
This project will not be ready for some time - stick with 1.9.2 for now.

**Comment by RahimGashti** [comment]
thank you for reply.
I download orchard 2 project but package not restored from myget.org.
.....
  GET https://www.myget.org/F/xunit/FindPackagesById()?id='Microsoft.AspNet.DataProtection.Abstractions'
  GET https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/microsoft.win32.registry/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.win32.registry/index.json
  GET https://www.myget.org/F/xunit/FindPackagesById()?id='Microsoft.Win32.Registry'
  GET https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/system.security.principal.windows/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.security.principal.windows/index.json
  GET https://www.myget.org/F/xunit/FindPackagesById()?id='System.Security.Principal.Windows'
  OK https://api.nuget.org/v3-flatcontainer/system.diagnostics.tracing/4.0.0/system.diagnostics.tracing.4.0.0.nupkg 93719ms
  NotFound https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/microsoft.aspnet.authorization/index.json 2006ms
  NotFound https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/microsoft.aspnet.cryptography.internal/index.json 2128ms
  NotFound https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/microsoft.aspnet.dataprotection.abstractions/index.json 2178ms
  OK https://www.myget.org/F/xunit/FindPackagesById()?id='Microsoft.AspNet.DataProtection.Abstractions' 2298ms
  OK https://www.myget.org/F/xunit/FindPackagesById()?id='Microsoft.AspNet.Cryptography.Internal' 2343ms
  NotFound https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/system.security.principal.windows/index.json 2235ms
  NotFound https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/microsoft.win32.registry/index.json 2287ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.cryptography.internal/index.json 5662ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.cryptography.internal/1.0.0-rc1-final/microsoft.aspnet.cryptography.internal.1.0.0-rc1-final.nupkg
  OK https://www.myget.org/F/xunit/FindPackagesById()?id='Microsoft.Win32.Registry' 5675ms
  OK https://api.nuget.org/v3-flatcontainer/system.reflection.typeextensions/4.1.0-beta-23516/system.reflection.typeextensions.4.1.0-beta-23516.nupkg 100788ms
  OK https://www.myget.org/F/xunit/FindPackagesById()?id='System.Security.Principal.Windows' 7818ms
Warning: FindPackagesById: System.Dynamic.Runtime
  HTTP request timed out. Retrying.
  GET https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/system.dynamic.runtime/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.win32.registry/index.json 8123ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.win32.registry/4.0.0-beta-23516/microsoft.win32.registry.4.0.0-beta-23516.nupkg
  NotFound https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/system.dynamic.runtime/index.json 880ms
  OK https://api.nuget.org/v3-flatcontainer/system.xml.readerwriter/4.0.0/system.xml.readerwriter.4.0.0.nupkg 106144ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.cryptography.internal/1.0.0-rc1-final/microsoft.aspnet.cryptography.internal.1.0.0-rc1-final.nupkg 7054ms
  GET https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/system.runtime.handles/index.json
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.handles/index.json
  GET https://www.myget.org/F/xunit/FindPackagesById()?id='System.Runtime.Handles'
  OK https://api.nuget.org/v3-flatcontainer/system.security.principal.windows/index.json 12693ms
  GET https://api.nuget.org/v3-flatcontainer/system.security.principal.windows/4.0.0-beta-23516/system.security.principal.windows.4.0.0-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.dataprotection.abstractions/index.json 12931ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.dataprotection.abstractions/1.0.0-rc1-final/microsoft.aspnet.dataprotection.abstractions.1.0.0-rc1-final.nupkg
  NotFound https://www.myget.org/F/aspnetrelease/api/v3/flatcontainer/system.runtime.handles/index.json 927ms
  OK https://www.myget.org/F/xunit/FindPackagesById()?id='System.Runtime.Handles' 952ms
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.handles/index.json 1386ms
  GET https://api.nuget.org/v3-flatcontainer/system.runtime.handles/4.0.1-beta-23516/system.runtime.handles.4.0.1-beta-23516.nupkg
  OK https://api.nuget.org/v3-flatcontainer/system.runtime.handles/4.0.1-beta-23516/system.runtime.handles.4.0.1-beta-23516.nupkg 7862ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnet.dataprotection.abstractions/1.0.0-rc1-final/microsoft.aspnet.dataprotection.abstractions.1.0.0-rc1-final.nupkg 10689ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.win32.registry/4.0.0-beta-23516/microsoft.win32.registry.4.0.0-beta-23516.nupkg 16172ms
  OK https://api.nuget.org/v3-flatcontainer/system.security.principal.windows/4.0.0-beta-23516/system.security.principal.windows.4.0.0-beta-23516.nupkg 15019ms
  OK https://api.nuget.org/v3-flatcontainer/system.dynamic.runtime/4.0.11-beta-23516/system.dynamic.runtime.4.0.11-beta-23516.nupkg 137747ms

**Comment by RahimGashti** [comment]
can we migrate from orchard 1.9.2 to orchard2 after release it?
