### ISSUE TITLE
Could we improve the limits fixed to dependency injection in v1

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard2#134]
I frequently find myself in a situation where I would need some value or some service in a property of a ContentPart, but autofac can't be used in v1 to initialize properties, even if this is in its possibilities.
Yes I know, lot of people will give me a lesson of good software usage and practice and so and so...you know what I mean.

**Comment by sebastienros** [comment]
You can already do that with a content handler during the Initializing or Loading events.

**Comment by CSurieux** [comment]
It is a trick and not identical to what we get with injection.
Will the content events persist as NH is gone ?

**Comment by sebastienros** [comment]
The content events have nothing to do with NH, just the content management triggering them. And they are still there. And we'll never implement dependency injection for data object, for the exact reason you mentioned: "lot of people will give me a lesson of good software usage and practice and so and so"

**Comment by CSurieux** [comment]
Ok, Great. We should call this the Orchard Academy (seems very ecolo).
So I am ready to learn why.
