### ISSUE TITLE
Question about yesSQL

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard2#138]
I know it is not Sql but should we able to do easilly requests similar to SQL join based on other fields than the main Id.
A classic data schema
Companies -> external keys to itself, contacts, addresses (x n)
Contacts -> external key to itself, companies, addresses
Addresses 

In O1 it is very uneasy to select the adresses related to a selection of companies and filter on various items in each entity.

**Comment by CSurieux** [comment]
Addendum, I forget this one:

I hope itwill be easier with YesSQL to manage more complex types created in its own code.
For exemple a Mony implementation based on decimal and currency. 
NH was so limiting on this feature.

**Comment by sebastienros** [comment]
I would say Yes, as your class is store in Json so it will serialize whatever is contains and you can customize what it serializes using Json.NET settings.
Also the indexes can be any computed value you want, they just have to map to SQL columns of your choice. And they can be foreign keys to other tables.
Then you can query anything in SQL, it's part of the YesSql API, you'll find some overloads which accept SQL.
And in case it helps, writing sql should be easier as you just need to return document ids, then ask YesSql to get you the documents represented by these ids.

I'd encourage you to try the examples you are giving to continue this conversation and see where the limitations are so we can fix them.

NB: Please, no questions on GitHub, we never know if we can close these, and also adds clutter to issues management. Prefer Stackoverflow and/or the Gitter chat rooms. Thanks.

**Comment by CSurieux** [comment]
> NB: Please, no questions on GitHub, we never know if we can close these, and also adds clutter to issues management. Prefer Stackoverflow and/or the Gitter chat rooms. Thanks.

so it changed because here https://github.com/OrchardCMS/Orchard2/issues/87
it was

> Feel free to open issue for every suggestion so we can track discussions for each of them.

Certainly the guy in the high castel or Manuel Valls

**Comment by bleroy** [comment]
Suggestions are fine, questions should be asked, but not here. This seems to be somewhere in the middle. Also, can you please stop it with the random Nazi comparisons?

**Comment by CSurieux** [comment]
Nothing is totally white or black. I was more referring to the writing of P.K. Dick about disproportionate contingencies applied on mind rather than to any criminal  historical period.
________________________________
De : Bertrand Le Roy<mailto:notifications@github.com>
Envoyé : ‎18/‎02/‎2016 19:23
À : OrchardCMS/Orchard2<mailto:Orchard2@noreply.github.com>
Cc : CSurieux<mailto:christian.surieux@hotmail.fr>
Objet : Re: [Orchard2] Question about yesSQL (#138)

Suggestions are fine, questions should be asked, but not here. This seems to be somewhere in the middle. Also, can you please stop it with the random Nazi comparisons?

---
