### ISSUE TITLE
Reuse IShapeTableManager across tenants

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#140]
From my tests by trying to start 1000 tenants this is the most consuming part in terms of startup perf and memory. It can easily be changed to store each theme's `ShapeTable` at the application level, but each module can provide different bindings (some attribute binding could override a template one).

The solution is to create a ShapeTable per feature and whenever a binding is looked up then just use the ones that are enabled.
However not all features/modules add some attribute bindings, and themes always win and don't vary by tenant. We could then look in the Theme bindings first, then module ones, by adding a priority or a chain of responsibility instead of merging all the bindings. Each tenant could have its own chain of responsability, and reuse all the bindings for each feature.

For instance:

Tenant 1:
ThemeA -> Module 1 -> Module 2 (shape found)

Tenant2 (without Module 1)
ThemeA -> Module 2 (shape found)

The features are chained using feature priority order (as today).

**Comment by sebastienros** [comment]
@jtkech You want something to work on, here is a good candidate for you.

Let me know if you want it or not, or if you have any questions. This could also be applied to O1 btw.

**Comment by jtkech** [comment]
Ok, seems very interesting but i first need to see how it currently works.

> themes always win and don't vary by tenant

Not used to MultiTenancy but i thought that each tenant could have its own selected theme.

I will start on it asap.

Best.

**Comment by sebastienros** [comment]
I skyped you. Let me know if you want to talk about it first, I can give you more context.

**Comment by jtkech** [comment]
I'm connected, you can call me

**Comment by jtkech** [comment]
I thought i was closed to a quick solution but...

Things are first organized by binding strategies (IShapeTableProvider) from which we build shape alterations. A binding strategy is related to a feature but finally these are shape alterations which are related to features and from which we build shape descriptors.

**So, it seems that this is at the IShapeTableProvider level that we would need to use a shared "cache" (managed by DefaultShapeTableManager) not to re-build shape alterations related to a feature**.

Maybe only for the core ones (e.g ShapePlacementParsingStrategy) which are looking on other modules, and not for a non core IShapeTableProvider which only provides shapes from itself. Right?

Best

**Comment by sebastienros** [comment]
Another point, the ShapeTemplateStrategy will find the templates for all available modules (not features) and should create as many minishapetable as modules, and assign them to the default feature of a module (each module has a default feature with the same name)

**Comment by sebastienros** [comment]
Maybe a ShapeTableProvider should be able to return a list of { Feature, ShapeTableBinding[] }, then when they are gathered, just call them as a list, so instead of having one set of bindings per feature, you'd have many sets. Let's talk later if needed.

**Comment by jtkech** [comment]
I will learn this w-end more in depth how e.g ShapeAlterationBuilder works. Here my last findings.

- Currently IShapeTableProviders provide a way to build ShapeAlterations.

- A ShapeAlteration is tied to a ShapeType and a Feature.

- A ShapeDescriptor is tied to a ShapeType and is Altered by all ShapeAlterations of the same ShapeType.

- So each ShapeDescriptor depends somewhere on the list of current features (e.g the theme).

- When building ShapeAlterations we create delegates which create other delegates when Altering a ShapeDescriptor. But the more consuming work seems to be done when building ShapeAlterations.

- So, a 1st step would be to cache each ShapeAlteration which is tied to a ShapeType and a Feature. And tell to the ShapeTableBuilder and core IShapeTableProvider to only act on requested features.

- A 2nd step would be to cache each ShapeDescriptor but with a list of ShapeAlterations already applied on it. Here we would not only need to be able to do an Alteration but also to revert back an Alteration.

- Note: Alterations are done by feature dependencies and priorities order. So when applied afterwards, affected ShapeDescriptors collections woud need to be re-ordered.

Best.
