### ISSUE TITLE
Do you have a plan for theme.txt and module.txt?

### ISSUE THREAD

**Issue by hguven** [OrchardCMS/Orchard2#142]
Hi
Do you have a plan conversion for *.txt  files to .json?

**Comment by GVX111** [comment]
you can change it from code in: AddModuleFolder and AddThemeFolder.
https://github.com/OrchardCMS/Orchard2/blob/13eacd6c824c6bfb3d53b5c781a180853dbaf498/src/Orchard.Environment.Extensions/Folders/ServiceCollectionExtensions.cs

**Comment by sebastienros** [comment]
Please, no questions on the issue tracking. Feel free to join our gitter room. Also I think there is already an open issue to implement that.
