### ISSUE TITLE
configurationBuilder.GetBasePath()

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/Orchard2#144]
configurationBuilder.GetBasePath() returns "D:\Orchard2\src\Orchard.Web\App_Data\App_Data\" and makes an error on trying to find the settings.txt file.

**Comment by GVX111** [comment]
Dublicate issue. https://github.com/OrchardCMS/Orchard2/issues/143

**Comment by Skrypt** [comment]
Closing this one. More complete description on the other :)
