### ISSUE TITLE
Usage of the Create 'pattern' for content items should not be limited to admin mode

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard2#150]
We should be in position to decide when defining a content item if it can be created in front-end mode.
In Extenso having the drivers, handlers, etc. working of with the actual front-end theme for authenticated users.
I am sure this suggestion will be soon closed.

**Comment by bleroy** [comment]
Sounds like a good idea to me. A good generalization of what already exists for forms. It would require that part authors shift their assumptions to a world where their editor parts would need to work outside of the admin by default, which may be a little too much for the existing ecosystem, but this may be a great thing to do for Orchard 2.

(also, stop it already with the reverse psychology ;) )

**Comment by CSurieux** [comment]
Surprising, thanks. Everybody could make mistakes and in this case it seems that I made one.

**Comment by sebastienros** [comment]
Even though the idea might be interesting, I will close this issue for consistency.

**Comment by CSurieux** [comment]
Ha, I was somehow disappointed.

**Comment by Jetski5822** [comment]
You guys!

**Comment by CSurieux** [comment]
I am also suggesting directly in code comments, it is more complicated to close.
