### ISSUE TITLE
Imported project Microsoft.DotNet.Props was not found.

### ISSUE THREAD

**Issue by YasirSyed** [OrchardCMS/Orchard2#177]
I am getting the following errors after cloning the latest Orchard2 code and building it on Visual Studio Enterprise 2015 edition Version 14.0.24720.00 Update 1. Can someone tell me where do I get this Microsoft.DotNet.Props from?

C:\GIT\Orchard2\src\Orchard.DeferredTasks.Abstractions\Orchard.DeferredTasks.Abstractions.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\GIT\Orchard2\src\Orchard.DeferredTasks.Abstractions\Orchard.DeferredTasks.Abstractions.xproj

C:\GIT\Orchard2\src\Orchard.DeferredTasks\Orchard.DeferredTasks.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\GIT\Orchard2\src\Orchard.DeferredTasks\Orchard.DeferredTasks.xproj

C:\GIT\Orchard2\src\Orchard.Recipes.Abstractions\Orchard.Recipes.Abstractions.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\GIT\Orchard2\src\Orchard.Recipes.Abstractions\Orchard.Recipes.Abstractions.xproj

C:\GIT\Orchard2\src\Orchard.Web\Orchard.Web.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\GIT\Orchard2\src\Orchard.Web\Orchard.Web.xproj

**Comment by GVX111** [comment]
You need to update RC2 or install dotnet Cli [https://www.microsoft.com/net/core#windows](url)

**Comment by Jetski5822** [comment]
Closing, to clean up backlog. If still issue, let us know.

**Comment by YasirSyed** [comment]
Thanks, I don't get the error any longer after installing the following:

1. Visual Studio 2015 Update 3
[https://www.visualstudio.com/en-us/news/releasenotes/vs2015-update3-vs](url)

2. ASP.NET and Web Tools 
[https://visualstudiogallery.msdn.microsoft.com/c94a02e9-f2e9-4bad-a952-a63a967e3935](url)
