### ISSUE TITLE
The Dockfile error

### ISSUE THREAD

**Issue by Jamesxql** [OrchardCMS/Orchard2#180]
This line: 
RUN sudo apt-get install dotnet-dev-1.0.0-preview1-002702

shuold be:

RUN sudo apt-get install -y dotnet-dev-1.0.0-preview1-002702

otherwise, the docker build will report:

The command '/bin/sh -c sudo apt-get install dotnet-dev-1.0.0-preview1-002702' returned a non-zero code: 1

**Comment by alexbocharov** [comment]
Try run `sudo apt-get install dotnet-dev-1.0.0-preview1` or `sudo apt-get install dotnet-dev-1.0.0-preview2-sdk`

**Comment by Skrypt** [comment]
@Jamesxql is right, that -y is for pre-giving a yes answer to that command ; else it will hang at that command waiting for an answer.
