### ISSUE TITLE
Timezones cross platform

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Orchard2#182]
Think about using Nodatime..
http://www.joeaudette.com/cross-platform-time-zone-handling-for-aspnet-core.aspx

**Comment by dementeddevil** [comment]
I think the latest thinking is to use DateTimeOffset although I haven't taken a look at the Orchard source to check that it is using UTC dates throughout the persistence logic (which of course it should be)

**Comment by Jetski5822** [comment]
Was thinking the same, sticking with DateTimeOffset...

**Comment by agriffard** [comment]
FYI @Jetski5822 , I added a way to specify the Timezone setting.
@sebastienros was wondering if it was cross-platform if we store the timezone id.
See #404
