### ISSUE TITLE
Feature Loading: Duplicate method call.

### ISSUE THREAD

**Issue by GVX111** [OrchardCMS/Orchard2#186]
Why we calling two time `_extensionManager.LoadFeatures`
First time in `DefaultOrchardHost on CreateAndActivateShells line:#94`
and second time in `CompositionStrategy line #46`

I think we don't need LoadFeatures in DefaultOrchardHost.

**Comment by jtkech** [comment]
@GVX111 didn't seen in deepth, so just as a side note. 

The requested features are not the same. In one place this is the available features, in the other place this is the enabled features.

    _extensionManager.LoadFeatures(_extensionManager.AvailableFeatures());
    _extensionManager.LoadFeatures(enabledFeatures);

And to prevent from duplicate works, features / extensions are cached in the following dictionnaries.

    private Dictionary<string, Feature> _features = new Dictionary<string, Feature>();
    private readonly ConcurrentDictionary<string, ExtensionEntry> _extensions = new ...;

Best.

**Comment by GVX111** [comment]
Sorry I missed something. :|

**Comment by jtkech** [comment]
No worries :)
