### ISSUE TITLE
When you use an invalid password on Setup, Site is created without user

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#191]
User is created thought this event handled by an Orchard.Users handler:
```
await eventBus.NotifyAsync<ISetupEventHandler>(x => x.Setup(
                        context.SiteName,
                        context.AdminUsername,
                        context.AdminEmail,
                        context.AdminPassword,
                        context.DatabaseProvider,
                        context.DatabaseConnectionString,
                        context.DatabaseTablePrefix)
                    );
```
Problem is if it fails it is not notified to the user and the creation of the site is completed but without any admin user, so you cannot access the new site.
I'm open to fix it, which should be the approach?

**Comment by Jetski5822** [comment]
maybe we should use a cancellation token?

**Comment by jersiovic** [comment]
CancellationTokens are created with a CancellationTokenSource and as far as I know is the CancellationTokenSource what is used to cancel an operation. So, it looks the idea behind CancellationTokens is a consumer of an action can cancel an operation without matter how many different actions are running for complete that operationt. 
I dont see how could it help here.

**Comment by jersiovic** [comment]
In the case we are aware that password validation failed what should be the action to take? To remove the tenant and report the error to the user? 
In this particular case looks easier to validate password before the tenant is created to don't have to remove it if it is invalid.

**Comment by Jetski5822** [comment]
maybe we need a ISetupValidationEventHandler ?

**Comment by jersiovic** [comment]
For the sake of maintaining modules decoupled ... ok

**Comment by jersiovic** [comment]
Using ISetupValidationEventHandler is to have the validation logic of the user int Orchard.Users module. However, how at that point no tenant exists handler defined in Orchard.Users is not loaded because the only feature enabled are Orchard.Logging.Console and Orchard.Setup.
I could add Orchard to be enabled by default, problem is Orchard.Users has dependencies like Orchard.Data, so at this point what would be best option in your opinion?
