### ISSUE TITLE
On login an unhandled exception occurrs 

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#192]
The error I receive is:
"An unhandled exception occurred while processing the request.
InvalidOperationException: No authentication handler is configured to handle the scheme: Identity.Application"

**Comment by sebastienros** [comment]
The fix is wrong IMO. We should just register the required services, using `UseIdentity` will register may other services that are not necessary or incompatible with our implementations.
It needs to be replaced by the correct calls.

**Comment by jersiovic** [comment]
I have reviewed what does UseIdentity https://github.com/aspnet/Identity/blob/dev/src/Microsoft.AspNetCore.Identity/BuilderExtensions.cs and by now it does almost the same we do at Configure method using options to configure cookieAuthentication. 
So, current UseIdentity is equivalent to what we do. In fact I have checked out the head of the master branch and removed the builder.UseIdentity() line to check if the exception occurs but now it doesn't occurs. So, it seems my fix was for nothing. 
I'm going to remove the line I added.

**Comment by sebastienros** [comment]
There is still an issue during Setup without this line of code. So there must be a difference, I get the error on `Identity.External`.

**Comment by sebastienros** [comment]
This is the code from UseIdentity 
```
            var options = app.ApplicationServices.GetRequiredService<IOptions<IdentityOptions>>().Value;
            app.UseCookieAuthentication(options.Cookies.ExternalCookie);
            app.UseCookieAuthentication(options.Cookies.TwoFactorRememberMeCookie);
            app.UseCookieAuthentication(options.Cookies.TwoFactorUserIdCookie);
            app.UseCookieAuthentication(options.Cookies.ApplicationCookie);
```

The difference is probably in the default options then.
