### ISSUE TITLE
[Authorize] annotation is ignored

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#194]
As far as I know if you use [Authorize] annotation in a controller class or in one of its methods, when a request by an unauthenticated user is done it receives an error or it is redirected to the login page.
However currently this annotation is ignored.
Any clue of why is this happening?

**Comment by sebastienros** [comment]
I am not sure this is still the standard behavior. The authorization might be linked to your location for instance, even if you are anonymous. It's just checking any available policy.
