### ISSUE TITLE
Integrating Blockly

### ISSUE THREAD

**Issue by gentledepp** [OrchardCMS/Orchard2#197]
I was just wondering, if it would be an option, to integrate Googles Blockly into the workflow engine, so that you can do more stuff in those steps.
It is by far the easiest way for non-programmers to "write code". I do not mean that you should replace your activities. What I mean is, that there could be a "code activity".
For example: You already have a C# scripting activity. 
For this, you could add the Blockly C# editor, so that also non-programmers can help theirselves.

Just a thought. What do you think?

**Comment by Jetski5822** [comment]
Hmm interesting: https://developers.google.com/blockly/

what do you htink @sfmskywalker and @pszmyd ? Sounds like a good idea for a module outside of core?

**Comment by sfmskywalker** [comment]
I think it's a great idea for a gallery module, but not part of core. Core will already have a Code Activity based on JavaScript.
