### ISSUE TITLE
Updated Roadmap Dates?

### ISSUE THREAD

**Issue by maroonedsia** [OrchardCMS/Orchard2#198]
**Could you please update us on some rough dates for the roadmap?**
That will help us on planning learning Orchard 2.0.

I really would like to learn Orchard, but I think because of fundamental changes in ASP.NET Core, I would rather wait for Orchard 2.0 to get released.

Thanks,
Sia

p.s. I'm not sure if "Issues" is the best place to post a question, sorry for that.

**Comment by Jetski5822** [comment]
Hi Sia,

We dont have date for the milestones for the roadmap at the moment. The framework for O2 is influx, I know I want to change a bunch of things, and so does @sebastienros - and we have other guys working on dynamic compilation like @jtkech , @alexbocharov and @GVX111 .

I myself am looking at recipes when I get time.

What cool though, is that for module development, not an awful lot will change between O1 and O2, you still have DI concepts like IDependency, and putting a module in to the modules folder. There will be more extension points, but the big things like CI and module composition will remain the same-ish, so the transition should be that tough.

That big changes are around storing content, we dont use NHibernate anymore for example, but thats actually a good thing, and im sure you will agree on that one! - however, there will be some new concepts for you to understand around that.

My Advice is.... Learn O1... alot of what you learn from that will XFer across, and will help you learn O2 faster. If you want to get your hands dirty, then find something on the roadmap we havent done, or you would like to change, and work on it! - look at the code, and fire it up. If you want to change something, issue a PR, all PR's are welcome and we try our best to code review them all and give good feedback.

Well up to you, but hey - Welcome man to Orchard!

**Comment by maroonedsia** [comment]
@Jetski5822 

Thank you very much for the reply and explanation. 

Cheers,
Sia
