### ISSUE TITLE
Update dependencies to RTM 

### ISSUE THREAD

**Issue by shahid-pk** [OrchardCMS/Orchard2#202]
What is the plan of updating the project dependencies to rtm bits. I think corefx , coreclr and Asp.net Core packages can be updated to rtm releases.

**Comment by jtkech** [comment]
You need to install latest dotnet core and sdk e.g by using `build.cmd` (but i don't use it) or from microsoft sites as [here](https://www.microsoft.com/net/core#windows) or for the latest dev build [here](https://github.com/dotnet/cli#installers-and-binaries). As i remember, the last time i've done it, i've used VS tools updating but i needed before to install `Visual Studio 2015 Update 3`.

Then, we already use rtm releases of Asp.net Core packages, e.g in `Orchard.Web/project.json` we use:

    "dependencies": {
      "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-*",
      ...

Then, after a `dotnet restore` from the `Orchard2` root folder, core packages are updated, and in the related `project.lock.json` file we can see that `rtm release 1.0.0` are used in place of `1.0.0-rc2-final`:

      "Microsoft.AspNetCore.Server.Kestrel/1.0.0": {
        "type": "package",
        "dependencies": {
          "Libuv": "1.9.0",
          "Microsoft.AspNetCore.Hosting": "1.0.0",
          "Microsoft.Extensions.Logging.Abstractions": "1.0.0",
          ...
Best.

**Comment by shahid-pk** [comment]
thanks for the info.
