### ISSUE TITLE
Provide token authentication for Web APIs without the need of an external identity server

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#210]
I have read about OpenIddict https://github.com/openiddict

It brings token authentication and OpenID Connect support to ASP.NET Core on top of ASP.NET Core Identity. It attempts to provide a simple and easy-to-use solution in comparison with IdentityServer’s complexity. 
By default it relies on Entity Framework for its storage but it can be replaced providing alternate implementations of its interfaces https://github.com/openiddict/openiddict-core/tree/dev/src/OpenIddict.Core/Stores to integrate it on Orchard. 
So, It's likely it will fit with Orchard, but if not maybe we can use it as a source of inspiration.

**Comment by sebastienros** [comment]
What about generating these tokens? This is the part that is not in ASP.NET identity by default.

**Comment by Jetski5822** [comment]
Why is it not in there by default?

**Comment by sebastienros** [comment]
Because generating these tokens is a difficult business AFAIK.

**Comment by PinpointTownes** [comment]
> What about generating these tokens?

It's OpenIddict's main objective: generating tokens :smile: 

> Why is it not in there by default?

Because Katana's OAuth2 authorization server middleware was not ported to ASP.NET Core, so there's basically nothing built-in that can be used to generate tokens.

If you were to add native OAuth2/OIDC support in a project like Orchard, maybe ASOS (the underlying OIDC server middleware behind OpenIddict) would be a better fit: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server

**Comment by sebastienros** [comment]
Thanks, that explains things better.

**Comment by jersiovic** [comment]
Too many free time on holidays, so I'm integrating OpenIddict with Orchard 2 :)
I prefer this path because I'm able to rely on OpenIddict classes cause I'm not an expert on OpenId/OAuth so it is safer to rely on their code.
In next phases if we think OpenIddict is disturbing we can replace its component by our own classes and logic.

By the moment I have replaced entity framework stores from OpenIddict by others based on YesSql,to make it work. I still use OpenIddict managers, its builder and extension, those are specilly useful because it helps to decide easily which flows do we want to enable. 

I'm implenting it within Orchard.Users module and I will need to add an extra admin view to provide administrators a way of managing the client apps that a tenant will allow access to its API fulfilling their ClientId, ClientSecret, DisplayName, LogoutRedirectUri,  string RedirectUri and Type.

 How can I do it? I saw that Orchard 2 recognizes Admin controllers using its name. If I there is one controller called AdminController in Orchard.Users module how I add an extra one?

**Comment by PinpointTownes** [comment]
> I prefer this path because I'm able to rely on OpenIddict classes cause I'm not an expert on OpenId/OAuth so it is safer to rely on their code.
In next phases if we think OpenIddict is disturbing we can replace its component by our own classes and logic.

Sure, using OpenIddict with Orchard should work fine :smile: 

I guess it really depends on what you want to do exactly: do you need something deeply integrated with Orchard or do you something more "standalone"? For a built-in Orchard module, using ASOS might offer more flexibility thanks to its low-level approach.

**Comment by PinpointTownes** [comment]
My bad, I had not realized Orchard vNext directly used Identity ("Orchard 1.0" had its own membership stack), so yeah, OpenIddict is probably a good option :smile:

**Comment by sebastienros** [comment]
@jersiovic like in O1 you can add an `[Admin]` attribute on your controller.

@PinpointTownes while you are here, I hope you will be able to look at his code to see if he's using it correctly.

**Comment by PinpointTownes** [comment]
> @PinpointTownes while you are here, I hope you will be able to look at his code to see if he's using it correctly.

Sure. Show me the codezzz and I'll take a look.

**Comment by jersiovic** [comment]
Great! Thank you

**Comment by sebastienros** [comment]
So a client app is just like any other user? In this case I assume we need a specific Permission (Manage Client Apps) to be able to edit this list. The table and storage should be very close to what I have done for users too, right?

I suggest I create an oauth branch on this repos so that you can make PRs targeting it. This way multiple contributors can contribute, even myself.

**Comment by jersiovic** [comment]
Yes it is going to be very similar to users.

Ok perfect I will push to that branch my changes

**Comment by jersiovic** [comment]
By the moment I'm testing with UseJsonWebTokens(), AllowPasswordFlow() and AllowRefreshTokenFlow() and it works properly with Postman, adding a Client App declared as confidential. Configure the other flows doesn't look a problem. 

My idea is Ochard admin can also configure from the UI:
 + Which flows he wants to enable.
 + Set it he wants its own certificate and its password for the .pfx file (we would store this password in plain text in the db??)

A doubt: 
Orchard by default authenticates through cookie based middleware. Adding the OpenIddict middleware we add the posibility of authenticate through tokens.
I have clear that confidential client apps are server apps (can use password authentication to get a token), while public apps will be mobile and SPA apps. 
SPA apps need to authenticate on authorization server to get a valid token (in our case it is the same as the resource server).
My doubt comes with SPA apps served by Orchard mixed with regular mvc pages (apps served by the same site that is the authorization server and the resource server). We don't want that a user logged in Orchard through cookie authentication middleware has to login another time if it uses an SPA served by the same site because it needs to get an authorization token. What is the best path to do so? I have read things related with the topic but nothing I'm sure is the right option.

**Comment by sebastienros** [comment]
Reading certificates needs to be abstracted. There are many stores (windows certificates store, azure, keyvault, ...).

For the other questions I have close to no idea. I will also try to understand the issue.

**Comment by PinpointTownes** [comment]
> Set it he wants its own certificate and its password for the .pfx file (we would store this password in plain text in the db??)

FYI, OpenIddict/ASOS natively support X.509 RSA certificates and raw RSA keys and offers convenient `OpenIddictBuilder.AddSigningCertificate` helpers to register signing credentials (that can be stored in the machine store, in a .pfx file or retrieved from a blob).

There's no dedicated `OpenIddictBuilder.AddSigningKey` method but you can add a RSA key via `Configure(options => options.SigningCredentials.AddKey(new RsaSecurityKey(...))`. ECDsa support is planned, but IdentityModel doesn't support it well ATM.

> We don't want that a user logged in Orchard through cookie authentication middleware has to login another time if it uses an SPA served by the same site because it needs to get an authorization token. What is the best path to do so? I have read things related with the topic but nothing I'm sure is the right option.

It really depends on the flow you want to use. With the resource owner password flow, your JS side will have to get the user credentials to be able to send a valid token request.

Interactive flows like implicit are much more flexible, as you're responsible of creating your own authorization controller/middleware to handle the consent part with your own views/logic. You can (and even should) use cookies authentication to store the user identity during the OIDC steps.

Here's a sample of such a controller (that relies on Identity and its cookies middleware): https://github.com/openiddict/openiddict-samples/blob/master/samples/Mvc/Mvc.Server/Controllers/AuthorizationController.cs#L39-L91

**Comment by jersiovic** [comment]
Ok, we can talk about the certificate abstraction once you see my changes. By the moment in Debug it is not used a certificate and in Release mode I look for the certificate in a .pfx file within Tenant Folder in App_Data/Sites/ 
Thank you @PinpointTownes I see the different overrides available.

**Comment by jersiovic** [comment]
@PinpointTownes so ,when an SPA provided by our server asks authorization but user was authenticated previously by cookie middleware it will see directly the /accept view without the need of a second authetication. The point is for SPA provided by our server we shouldn't ask acceptance to the user. A solution for that is to redirect to /accept action when we detect a logged in user in an /authorize action.

Is this a risk for security? Should I have to do an extra check to be sure the app asking authorization is one provided by our server or it is ok do the redirect always that the user is authenticated when this action is done no matter if it is an SPA provided by a third party or one provided by our server?

**Comment by jersiovic** [comment]
Well what I'm saying it is wrong because I cannot do  a redirection to an action that requires a POST. I should allow GET on it or on the same /authorization action I could do signing like it is done in /accept action if user was loggen in previously. The question is the same than before. Is this ok? Should we limit this only to SPA apps provided by our site? In that case what's is the best way to check that?

**Comment by jersiovic** [comment]
My previous comments were wrong because when you access to /Authorize is because you are Authorized if not you are not redirected to the login page previously. So I'm not able to know if the user was logged in or not when the SPA asked for Authorize.
At this point the solution could be that we use an extra property for Applications called "Skip Consent" that we will set to true for apps served by our site.
In that way when /Authorize is call by one of our SPA apps we will avoid the Consent providing the token directly returning Signin result.
I'm wrong at some point now?

**Comment by PinpointTownes** [comment]
> In that way when /Authorize is call by one of our SPA apps we will avoid the Consent providing the token directly returning Signin result.

That's indeed the right thing to do if you want to avoid requiring an explicitly consent for your SPA side :smile:

**Comment by jersiovic** [comment]
Thank you :)

**Comment by jersiovic** [comment]
@sebastienros let me know when the oauth branch is available to make a pull request.

**Comment by jersiovic** [comment]
In the mean time some doubts:

1. Some weeks ago I found in orchard 2 [Authorize] annotation doesn't work https://github.com/OrchardCMS/Orchard2/issues/194 So, in the controller for OpenID instead of using Authorize like in the sample provided by @PinpointTownes I should use something like that to know if it is an authenticated user?

var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {

**Comment by sebastienros** [comment]
Again, it works as expected ;) It's the way it works in ASP.NET MVC Core.
You can check for a Role for instance, or use the API like you show for permissions in Orchard, or create a default policy of your choice which can be "the user needs to be authenticated" or create a custom attribute for checking a user is only authenticated. I'd suggest the first two options.

**Comment by jersiovic** [comment]
In the mean time some doubts:
1. Some weeks ago I found in orchard 2 [Authorize] annotation doesn't work https://github.com/OrchardCMS/Orchard2/issues/194 So, in the controller for OpenID instead of using Authorize like in the sample provided by @PinpointTownes I should use something like that to know if request is done by an authenticated user?
```await _userManager.GetUserAsync(User)==null```
 
2. I have had to add a property Tokens to fullfill requisites of OpenIddict for the following classes: Orchard.Users.Models.User and Orchard.Users.Models.OpenIdApplication. It stores a list of the current active tokens for a user or for an application. When you use a Storage based system like EF this is not a problem, you load Tokens or not when loading User or OpenIdApplication using and include. However, with YesSql everything is loaded when you load an User or an OpenIdApplication. In my opinion we should store tokens in a separated class UserToken and OpenIdApplicationToken to avoid problems if admin user is modifying an OpenIdApplication at the same time a consumer of that app is obtaining an authorization token. This solution wouldn't be a problem for OpenIddict because it relies on UserStorage and ApplicationStorage. I ask to be sure do you agree?

**Comment by sebastienros** [comment]
Maybe @PinpointTownes had defined a standard authorization policy, and this is what the [Authorize] attribute is using in this example. The behavior changed between RC2 and RTM I think, it's very recent.

No, store in the same object for now.

**Comment by PinpointTownes** [comment]
@sebastienros nope. The samples use `[Authorize]` with the default policy, that rejects unauthenticated requests (AFAIK, this behavior has not changed and is consistent with MVC 5).

**Comment by sebastienros** [comment]
I will investigate, I was part of the discussion for the change.

**Comment by sebastienros** [comment]
I have created the branch.

**Comment by PinpointTownes** [comment]
Feel free to ping me if you need help with the code :smile:

**Comment by sebastienros** [comment]
Quick notes from what I envision in therms of end users scenarios, feel free to correct me if you think I am wrong.

1- There should be an entity called Application that is the same as a User, but for API usage only. 
2- An Application is assigned Roles, like Users are. 
3- And application gets a computer generated client id and secrets. It can't be changed, just revoked. It's roles can be changed.
4- From an app, I can request a JWT token using this client id and secret and then use it in all the requests to communicate with Orchard.
5- In Orchard, the application is creating a service principal, like standard users.
6- From JavaScript, if the user is authenticated I can extract a valid JWT to do authenticated AJAX queries.

**Comment by jersiovic** [comment]
> 1- There should be an entity called Application that is the same as a User, but for API usage only. 
IMO despite we need an Application management (for adding editing or removing Applications like we have for users). I don't think they are the same. If we think on Twitter API, you register there Applications that can be used by twitter user for authenticate themselves and for interact with Twitter API on their name. But at the end of the day is the authenticated user who determines the permissions is going to have the app to do things. The same for Orchard. The point of having an application management is that depending of the kind of application, public (SPA or mobile app) or Confidential (server app) you are allowed to use one authentication flow or other for avoid breaking security.

>  2- An Application is assigned Roles, like Users are. 
As I said before. Initially at least I haven't followed this path. By the moment we issue IdentityClaim for the user. But maybe in next steps if we are interested on assing Roles to an app for limiting what an user can do through that app to only things that this role is allowed to.
> 3- And application gets a computer generated client id and secrets. It can't be changed, just revoked. It's roles can be changed.
The client and secret is set currently by the admin (the secret is the hash of the password provided by the admin). Currently I haven't implemented that admin can change password, but I don't see why we shouldn't do it.

>  4- From an app, I can request a JWT token using this client id and secret and then use it in all the requests to communicate with Orchard.
Yes 
 5- In Orchard, the application is creating a service principal, like standard users.
In fact, it works like standard user because what is logged in is a stardard user.
 6- From JavaScript, if the user is authenticated I can extract a valid JWT to do authenticated AJAX queries.
Yes

**Comment by jersiovic** [comment]
@PinpointTownes I'm facing the following issue:
I get successfully an access tokenId using password grant_type:
![image](https://cloud.githubusercontent.com/assets/4950766/17511671/4edfff80-5e24-11e6-8251-7d41b7200589.png)
But when I access to a resource using the access token obtained previously the user is not authenticated as I expected:
![image](https://cloud.githubusercontent.com/assets/4950766/17511727/9f8fa976-5e24-11e6-9d1e-8de46bd52a43.png)

In the controllor ((System.Security.Claims.ClaimsIdentity)User.Identity).Name is null instead of "admin" as I expected.

**Comment by sebastienros** [comment]
> > 1- There should be an entity called Application that is the same as a User, but for API usage only.

> IMO despite we need an Application management (for adding editing or removing Applications like we have for users). I don't think they are the same. If we think on Twitter API, you register there Applications that can be used by twitter user for authenticate themselves and for interact with Twitter API on their name. But at the end of the day is the authenticated user who determines the permissions is going to have the app to do things. The same for Orchard. The point of having an application management is that depending of the kind of application, public (SPA or mobile app) or Confidential (server app) you are allowed to use one authentication flow or other for avoid breaking security.

Are you suggesting each User would have a set of Application items?
So as a site owner, if I want to create an application I can add any on any user?

**Comment by jersiovic** [comment]
I suggest that we initially only use oauth flows based on user authentication instead of flows based on app authentication.
In that way Applications will be independent of users for us. As site owner you will create applications that are not related to any user. Those apps will be used by any user registered in Orchard redirecting him to login page it still is not loged in.

In a future step we can allow flows that allow access to an application (without user authentication). When we allow this, maybe we should let the site owner to set in the app configuration as which user the app should be logged in. But this equivalent to use directly a flow based on user, so I don't see why we could need allow access to an application.

**Comment by sebastienros** [comment]
I don't understand what an "application" is in the case of "oauth flows based on user authentication".
For me the goal is to "Provide token authentication for Web APIs without the need of an external identity server" so I see two scenarios:
1- We have an Orchard site, we want an authenticated user to be able to call WebAPI as part of the site, e.g. SPA page hosted by Orchard. Orchard authenticate the current user with these API calls.
2- We have an Orchard site, we want another site to be able to call into our APIs. We create an Application object with ClientId and ClientSecret, the remote app can use these to get a token. The Application object is associated to a Role (set of permissions).

I assume you are currently only handling case 1. If true, why do you need an Application concept?

**Comment by PinpointTownes** [comment]
> I don't understand what an "application" is in the case of "oauth flows based on user authentication".

It's the entity that sends the API requests on behalf of the user (e.g the JS side of a SPA).

> I assume you are currently only handling case 1. If true, why do you need an Application concept?

Unlike the resource owner password grant, interactive flows like implicit require validating things like `client_id` or `redirect_uri`. You can read http://stackoverflow.com/a/37380970/542757 for more information.

**Comment by sebastienros** [comment]
Ok, so this is a third scenario:
3- I have an Orchard site, we want to call the APIs from an external application, the external application can authenticate a user from the Orchard site.

**Comment by PinpointTownes** [comment]
It's not really a different scenario, as it also applies to your own Orchard-based website.

OpenIddict (or any other OAuth2/OIDC server) must be able to confirm that the user will be redirected to an endpoint controlled by your application (e.g a callback page of your SPA), and not a random page controlled by an attacker.

**Comment by jersiovic** [comment]
Currently I'm pursuing following three scenarios, that justify the use of the Application concept, in fact personally I'm specially interested on the last one:
1- We have an Orchard site, we want an authenticated user to be able to call WebAPI as part of the site. I'm talking ONLY of SPA pages HOSTED IN ANOTHER SITE OR A MOBILE APP. Orchard authenticate the current user with these API calls. App configured as: Public, SKIP CONSENT = FALSE (it shows a message to user informing him that it is providing access to its account to a third party app when the authorize call is done).
2- We have an Orchard site, we want an authenticated user to be able to call WebAPI as part of the site. Now I'm talking ONLY about SPA pages HOSTED WITHIN OUR ORCHARD SITE. Orchard authenticate the current user with these API calls. App configured as: Public, SKIP CONSENT = TRUE (it doesn't shows any message to user informing him that it is providing access to its account to a third party app).
 3- We have an Orchard site, we want another site to be able to call into our APIs. We create an Application object with ClientId and ClientSecret, THE REMOTE APP WILL USE USER AND PASSWORD OF A USER to get a token (Using Owner password credentials flow).

**Comment by jersiovic** [comment]
I'm attempting to get base url of the site in Module.Configure() for configuring JwtBearerAuthentication. 
```
public override void Configure(IApplicationBuilder builder, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
            var site = _siteService.GetSiteSettingsAsync().Result;
            builder.UseOpenIddict();
            builder.UseJwtBearerAuthentication(new JwtBearerOptions()
            {

                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
#if DEBUG
                RequireHttpsMetadata = false,
#endif
                Audience = site.BaseUrl,
                Authority = site.BaseUrl 
            });
        }
```

Problem is module load fails if I ask ISiteService by IoC on Startup method. Is there an alternative to get the base url of each tenant at this point?

**Comment by sebastienros** [comment]
you should have this configuration done in an IStartup, look at the Demo module

**Comment by sebastienros** [comment]
Also because it is per tenant configuration. One tenant == one middleware.

**Comment by jersiovic** [comment]
@PinpointTownes I have configured Jwt token options in the following way:

```
            builder.UseOpenIddict();
            builder.UseJwtBearerAuthentication(new JwtBearerOptions()
            {

                AutomaticAuthenticate = true,
                AutomaticChallenge = true,
#if DEBUG
                RequireHttpsMetadata = false,
#endif
                Audience = "http://localhost:2918/", //In final version it will be siteUrl
                Authority = "http://localhost:2918/" //In final version it will be siteUrl
           });
```
I ask for an access token using grant_type = password in the following way:
![image](https://cloud.githubusercontent.com/assets/4950766/17544692/20a89a54-5ed9-11e6-835b-7f554224162d.png)
Then I use the access token provided to fulfill the header of a request to one webApi:
![image](https://cloud.githubusercontent.com/assets/4950766/17544779/a4b22b76-5ed9-11e6-9bf4-a925ead46945.png)

Problem is still the same I had previously. In the action within the web api controller ((System.Security.Claims.ClaimsIdentity)User.Identity).Name is null instead of "admin" as I expected.

Following your advice I set audience in Jwt options and in both requests I use same the same string in the Resource header. Do you know what could be wrong?

**Comment by jersiovic** [comment]
@PinpointTownes more clues: I have breakpoints in all the methods of our ApplicationStore, UserStore and TokenStore to be sure that is not happening due to an error there. However on the second request to the webapi using an AccessToken the execution doesn't stop on those breakpoints.

**Comment by PinpointTownes** [comment]
You must request the `profile` scope to be able to retrieve the user name.

**Comment by jersiovic** [comment]
It works!! Thank you :)

**Comment by sebastienros** [comment]
Could this be related to the `Authorize` issue that Sergio is talking about? 
https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

**Comment by jersiovic** [comment]
I close this issue cause it is done in this PR https://github.com/OrchardCMS/Orchard2/issues/215
