### ISSUE TITLE
AuthorizationService.AuthorizeAsync doesn't fail in any case

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#217]
I have added this action to ContentAPiController in Orchard.Demo module:

```
 public async Task<IActionResult> GetAuthorizedById([FromServices] IContentManager contentManager, int id)
        {
            var contentItem = await contentManager.GetAsync(id);

            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ViewContent, contentItem))
                return Unauthorized();

            if (contentItem == null)
            {
                return NotFound();
            }

            return new ObjectResult(contentItem);
        }
```
Problem is that no matter if I'm logged in or I'm anonymous AuthorizeAsync never returns false.

Maybe this issue is related with this other one https://github.com/OrchardCMS/Orchard2/issues/194

**Comment by sebastienros** [comment]
In this case, ViewContent permission is actually available on all roles, even `Anonymous`. Try with a more restrictive permissions. Or remove it from the anonymous user (the controller is not yet implemented for this)

**Comment by jersiovic** [comment]
You are right.
