### ISSUE TITLE
CTRL+F5 loops on compilation

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#224]
Not sure what's happening, from VS.NET, running with CTRL+F5 starts the browser but the VS Output Console shows compilation is happening repeatedly.

**Comment by jtkech** [comment]
Just tried, it works for me, need to check it with the last master branch, will do it asap.

With CTRL+F5, the debugger is not attached, so normally dyn compilation doesn't use the VS Output console. That said, maybe a problem with a circular dependency, will check it.

**Comment by jtkech** [comment]
Sorry, can't repro. When i use CTRL+F5, i only see regular compilation messages before launching the app, not `Dynamic compilation` messages. Anyway, nothing is done repeatedly.
