### ISSUE TITLE
[Setup] Add a password strength hint

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#225]
In the setup screen. I don't think a real validation is necessary, but at least the red/yellow/green lights.

**Comment by bleroy** [comment]
Well, you'll need to explain why a pwd is not passing the test. I think validation should be enforced given how powerful the super-user account is.

**Comment by sebastienros** [comment]
The Users module already has some rules to apply. This user will have to comply with those at least, and this can be displayed. 
1- should we define a stronger/custom policy for the super user
2- should we be able to provide a custom policy
3- can it impact negatively the dev and trial experience

**Comment by bleroy** [comment]
1. yes, except maybe if IsLocal: don't want to make things too hard for dev boxes.
2. always difficult to do in setup. In principle, yes.
3. Well, yes :), see 1.

**Comment by sebastienros** [comment]
I think for now we are good then. The super user account needs to apply the default settings which are 
- 6 letters min
- one non-alphanumeric at least
- one uppercase at least
- one digit at least

Which is a little bit harder than O1 so it's not really an issue for devs, but at the same time enforces some good rules.
I am not sure being loose on IsLocal is a good thing though, most production sites are first created locally, and it's easy to forget about this account.

So the next thing to do is to add a description with the requirements for this password (before it fails validation) and bonus to add a color indicator of the strength of the password.

**Comment by agriffard** [comment]
I will try to integrate a Password strength indicator like this one on the setup screen :
http://rivalex.github.io/BootstrapStrength.js/

**Comment by agriffard** [comment]
Will there be a way to define the pasword policy?
Will an admin UI allow to specify this parameters?

Ex: Minimum length, Number of non alphanumeric, uppercase and digit characters required.

The ASP.NET Identity PasswordValidator would be initialized with these options.
The Password strength indicator would be parameterized with these options.

**Comment by agriffard** [comment]
A popover could also indicate what are the requirements for the password.

**Comment by sebastienros** [comment]
Let's start with the options as site settings. And a notification to
restart the tenant/site for these to be taken into account. Then we can see
at adding 2FA and password recovery.
