### ISSUE TITLE
Recipe Change Ideas

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Orchard2#227]
A few changes Im thinking about;

1 - RecipeStep.Step should change to dynamic from JToken, this would decouple the implementation from the transport format
2 - Maybe ditch the abstract class RecipeExecutionStep. I don't see its use.
3 - Create a Orchard.Recipes.Json, and move the Parser there... But on by default. 
Orchard.Recipies.Abstractions -> Orchard.Recipes <- Multiple Parsers

Additional things to do:
1. Add UI

**Comment by sebastienros** [comment]
> RecipeStep.Step should change to dynamic from JToken, this would decouple the implementation from the transport format
I think it should change to JObject instead, as this is what it is, and it's useful compared to dynamic as we can do `ToObject<>`. Or if we need to abstract then we would have to provide a type to bind to it.

> Maybe ditch the abstract class RecipeExecutionStep. I don't see its use.
I think all steps currently use it. But I am not a big fan, it doesn't help much.

I think the parser logic is good so far. For instance if we want to create a javascript or a C# version of a recipe, then we can then create a custom parser, which would evaluate a single step called "C# recipe" and would run the script. And have a "C#" step in json that would run the same type of step.

We mostly need more concrete steps actually (content types, import data, ...).
