### ISSUE TITLE
Fix Authorize attribute (Oauth2 Branch)

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#230]
Authorize is used in the access openid controller to control who is authorized to get a valid token. Problem it is ignored.

https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Web/Modules/Orchard.OpenId/Controllers/AccessController.cs

**Comment by jersiovic** [comment]
Just for the record @sebastienros pointed this link as sth that could be related with the problem. https://leastprivilege.com/2016/08/21/why-does-my-authorize-attribute-not-work/

I will spend some time this week to this issue

**Comment by jersiovic** [comment]
@sebastienros what it is pointed in this post doesn't seem to be the problem we are having. Because when I make an attempt to access with an anonymous user to an action with an [Authorize] attribute, that user doesn't have any claim assigned. So, it is not a matter of mismatch between RoleClaimType and the name used by role claims.
I don't get why [Authorize] logic allows a request with no claims assigned to its User.

**Comment by jersiovic** [comment]
Rescuing a previous conversation in a PR about this topic we said:

> **@PinpointTownes said:** When you don't specify a policy name,  [Authorize]  uses the default one... that rejects unauthenticated requests: https://github.com/aspnet/Security/blob/dev/src/Microsoft.AspNetCore.Authorization/AuthorizationOptions.cs#L22.
> **@jersiovic said:** @sebastienros where Orchard is supposed to override the default policy? I expected to found it here https://github.com/OrchardCMS/Orchard2/blob/51e873fb2a78a14d723899f6ed2f8efaa592e4cf/src/Orchard.Security/AuthorizationServiceModule.cs but here nothing is done
> **@sebastienros said:** We don't have to. I just defined some  AuthorizationHandler  classes to handle permissions (which are custom  Requirement ). So the  AuthorizeAttribute  should just work as is.
> Unless the default policy is affected by the fact some  IAuthorizationHandler  are registered.

The point is I've commented the registration code of all the IAuthorizationHandlers (SuperUserHandler, RolesPermissionsHandler and PermissionHandler) to be sure Orchard 2 is not afecting in any way default policy, but still I'm able to access to an action with [Authorize] attribute with an anonymous user.

**Comment by jersiovic** [comment]
Finally, I ve fixed the problem.
If in Orchard.Hosting.Mvc.ServiceCollectionExtensions.AddOrchardMvc() method I add .AddAuthorization() after .AddMvCore() call everything works as expected.

The point is currently this was done in the Configure() method of Orchard.Security.Startup class, but I guess the moment in which this is done matters, that's why it doesn't have effect.

So, by the moment I would move .AddAuthorization from Orchard.Security.Startup to Orchard.Hosting.Mvc.ServiceCollectionExtensions. 

Maybe, when this issue https://github.com/OrchardCMS/Orchard2/issues/248 is solved we will have the opportunity of decouple things moving security configuration another time to Orchard.Security module forcing Orchard to configure Authorization just after AddMvCore() but before other configurations that hurts its effect.

@sebastienros What do you think? Do I send a PR with that change ?

**Comment by sebastienros** [comment]
Nice find. I will look at the code again and see how to fix this. T/his might have a bigger impact as modules might have to provide components on a specific order. It might also be an issue in MVC or identity.

10 minutes after ....
Have been told that there are two AddAuthorization(), so we need both. One is for MVC (and can only be called on the result of AddMvcCore() and one is from Identity (which is the one we have in the module). So keep the one in the module, and add the one in AddOrchardMVC.

**Comment by jersiovic** [comment]
Oh I see, it would have been a good idea those net.core methods had more self explanatory names to make us easier see difference between them. 
Done. I have committed the change

**Comment by jersiovic** [comment]
This commit https://github.com/OrchardCMS/Orchard2/commit/57e92ede5c5e0fc0f5de935bf412b793554ea08d I made for fixing the Authorization issue solves that issue so, it fix Authorization flow, but breaks Password Flow.
This is what I get after that commit when I test Password Flow.

I have a breakpoint on AccessController.Token Action but code execution never stops there.
![image](https://cloud.githubusercontent.com/assets/4950766/18644125/607a893c-7ea8-11e6-844d-dc8480545212.png)

If I undo the change on that commit Password Flow works properly and the execution stops on my breakpoint but another time Authorization attribute doesn't work.

![image](https://cloud.githubusercontent.com/assets/4950766/18644037/0db836a4-7ea8-11e6-98db-a070d853132b.png)

@PinpointTownes @sebastienros any clue of why .AddAuthorization() could be causing Openiddict doesn't work as expected?

**Comment by PinpointTownes** [comment]
@jersiovic yeah, that's because the entire `AccessController` is decorated with `[Authorize]`.

I pushed a commit that should fix that: https://github.com/OrchardCMS/Orchard2/commit/00ea762a1aa8288d55614be043025bbf4cbbd4c0.

**Comment by jersiovic** [comment]
Aah it's true. 
Thank you
