### ISSUE TITLE
OpenId screens are ugly

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#231]
Feel free to copy what Orchard.Users is doing.

**Comment by jersiovic** [comment]
Well I have checked out the head of the branch and I find that there is not any page that looks nice on the Dashboard. In my original pull request that was not the case.

Now I get errors like the following ones in browser console accessing Orchard.User/admin/Index page or any other based on the Admin theme.
```
Index:13 GET http://localhost:2918/TheAdmin/Styles/TheAdmin.min.css 404 (Not Found)
Index:153 GET http://localhost:2918/TheAdmin/Scripts/TheAdmin.js 404 (Not Found)
```
Even though those files exists. Any idea of what made it fail?

**Comment by jersiovic** [comment]
Same happens in the master branch.

**Comment by Jetski5822** [comment]
Was this due to my change?

**Comment by Jeremaihloo** [comment]
Same happens in the master branch. It is a new clone.

I get 404 errors in `Orchard.Setup` area . Some js and css res. Even though those files exists after using `gulp build`. 

Orchard2 is new to me.

**Comment by sebastienros** [comment]
Can you try again now? It works on my machine ... I will try to reset the assets in the meantime

**Comment by jersiovic** [comment]
Yes now it works with your changes in master branch. Thank you.
Can you update the oauth2 branch with changes in master branch?

**Comment by sebastienros** [comment]
Yes, you should rebase the openid branch on master (not the opposite). If you are not sure how to do it, I can help.

**Comment by jersiovic** [comment]
Despite you added me as a member I still feel more comfortable working on my own repo and sending PRs to be sure I don't break anything :) 
But I know how to do a rebase. Later after the Orchard meeting I will do it.

**Comment by sebastienros** [comment]
not sure you can make a PR out of a rebase
