### ISSUE TITLE
Tag Helper <script at="Foot"> doesn't work properly (OAuth branch)

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#232]
The views used for adding a new app or for editing it has a bug. 
This is how it should work: you set the app Confidential using the combobox then you should see all the available roles for choosing which will be used when that app logs in. However, if you choose a public app roles has to be hidden because for that apps what is logged in is the user of the app, not the app itself, and the user has its own roles assigned so no there is no need of selecting any role.

Problem is it doesn't work as described because of tag helper provided by Orchard 2: `<script at="Foot">` doesn't load an inline script in Edit.cshtml https://github.com/xkproject/Orchard2/blob/00cdd7dff42dac4b7ab7cc7d5a45b4969c667601/src/Orchard.Web/Modules/Orchard.OpenId/Views/Admin/Edit.cshtml 

```
<script at="Foot"> 
     $("#Type").change(function () { 
         $("#RoleGroup").toggle("slow"); 
     }); 
</script> 

```
Same problem happened at Create.cshtml https://github.com/xkproject/Orchard2/blob/00cdd7dff42dac4b7ab7cc7d5a45b4969c667601/src/Orchard.Web/Modules/Orchard.OpenId/Views/Admin/Create.cshtml but there I removed at="Foot" in that way inline script is included but not in the right order so it doesn't work because of its dependencies.

**Comment by sebastienros** [comment]
This is what I use in my views:

```
<script at="Foot" type="text/javascript">
//<![CDATA[
    $(function(){
        Sortable.create(document.getElementById("fields"));
        Sortable.create(document.getElementById("parts"));
    })
//]]>
</script>
```

And you need to ensure this is added to your `_ViewImports.cshtml` :

```
@addTagHelper *, Orchard.ResourceManagement
```
