### ISSUE TITLE
Revisit certificate storage

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#243]
In the current bits, the OIDC module either uses an ephemeral key (when compiling with the DEBUG flag) or a X.509 certificate whose name is hardcoded in `Orchard.OpenId.Startup`. If the certificate cannot be found, OpenIddict will throw an exception stating that no signing credentials were registered, which doesn't really help one understand what's wrong.

We should consider revisiting that.

**Comment by jersiovic** [comment]
This issue was fixed allowing to the admin user to choose through the UI the certificate to use from those certificates available in the certificate store he also select. He can also set a test configuration based on an ephemeral key. So, no more hard coded strings or debug flags.
