### ISSUE TITLE
Add continuous integration for pull requests (AppVeyor/Travis)

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#244]
Looks like none of the Orchard repos uses CI, which makes detecting compilation errors/test failures quite hard before merging PRs.

/cc @Jetski5822 @sebastienros @bleroy, as this work item requires admin rights :smile:

**Comment by sebastienros** [comment]
We already have it, look at the badges on the homepage. @alexbocharov did it. 
What we don't have I think is the PRs integration. And also we don't have all tests passing right now.

**Comment by PinpointTownes** [comment]
> What we don't have I think is the PRs integration. 

Yeah, that's what I meant. I'll update the title to make that clearer.

**Comment by alexbocharov** [comment]
I'm not in the organization OrcahrdCMS. I can't make a directly integration. 

@sebastienros Please add me to the OrchardCMS in order to I was able to correctly configure the integration (if possible)

**Comment by sebastienros** [comment]
Added you as a dev, though I am not sure this is sufficient to create hooks. If not then just ask me to create a specific one.

**Comment by alexbocharov** [comment]
@PinpointTownes Everything is working

**Comment by PinpointTownes** [comment]
@alexbocharov great, thanks! :+1:

**Comment by PinpointTownes** [comment]
Looks like CI integration is only enabled for the master branch. When you have a minute, please enable it for all branches :smile:

**Comment by alexbocharov** [comment]
@PinpointTownes 
```yaml
branches:
  only:
    - master
    - release
    - dev
    - /^(.*\/)?ci-.*$/
```
Sample:
`ci-youbranchname` or `youname\ci-youbranchname`

**Comment by PinpointTownes** [comment]
Any particular reason to restrict CI to these branches? Currently, the `oauth2` branch doesn't get any CI love and I'd like to fix that.

> Sample:
ci-youbranchname or youname\ci-youbranchname

FWIW, I never use this approach as it creates extreme noise in 'public' repos. I prefer having feature branches in my fork, where I can freely rewrite the history without breaking anyone.

**Comment by alexbocharov** [comment]
Ok, let's try

**Comment by alexbocharov** [comment]
I removed the limit

**Comment by PinpointTownes** [comment]
@alexbocharov thanks!
