### ISSUE TITLE
Setup is broken after providing an invalid password twice

### ISSUE THREAD

**Issue by SzymonSel** [OrchardCMS/Orchard2#250]
Once you fill out the setup form with an invalid password and click '**Finish Setup**', you get an validation error '_Passwords must have at least one uppercase('A'-'Z')_.'

Clicking '**Finish Setup**' again (with or without the password inputs filled out) you get an 

```
NullReferenceException: Object reference not set to an instance of an object.
TryInvoke in DisplayHelper.cs, line 40
```

It the user hasn't been created, but the setup has ended "successfully".

**Comment by agriffard** [comment]
I confirm :
The first time, the database is created and the error message for a wrong password appears.
The second time, the setup doesn't try to create the user anymore so the state is not consistent: There is no super admin user.

**Comment by agriffard** [comment]
The password errors are also not well displayed: Only the last one is retrieved.

In Orchard.Users\Services\SetupEventHandler.cs, Setup method:
The reportError Action can be called multiple times if there are many errors on the password policy but it will replace the context.Errors["Password"] value so the only last one will appear.

**Comment by agriffard** [comment]
Let's explain what is happening:

- During setup, recipe is executed and modules are enabled.
- Orchard.Users registers the dependencies of ASP.NET Identity.
- Orchard.Users's SetupEventHandler tries to create the admin user.
- If there is a validation error (ex: incorrect password or email), the user is not created but in the mean time, a new HomeRoute has been specified by the recipe to point to Orchard.Demo/Home.
- This new homepage is loaded but it is not the setup one.
- The identity middleware tries to authenticate the user but it hasn't been created so there is an NRE in SecurityStampValidator.ValidateSecurityStampAsync().

To avoid this, may be we should create the super user in the setupService before the execution of the recipe, like in O1.

**Comment by sebastienros** [comment]
I think it's done now
