### ISSUE TITLE
Description of dynamic Compilation / Loading before doing some work on Packaging.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard2#253]
The goal is to describe what is currently done in different contexts and some specific scenarios. Then it will be easier to discuss about my last little concerns and what we could do for module packaging.

Maybe better to write a doc, but not so easy for me in english. So, right now i'll do it here step by step.

Best.

**Comment by sebastienros** [comment]
Your English will be fine ;) At least a blog post, or better a wiki page just dumping what you know, even not very polished. Just so that someone who wants to jump into the code can understand what is done, and why it's done.

Do you still plan to support the `/bin` folder thing we talked about?

**Comment by jtkech** [comment]
I am about to finish my first comment on this.
Oh, a **wiki page** seems better, how can i do this?
(sorry for the stupid question but never done)

About the `/bin` folder, yes i'll do it but i've worked on the issue related to the `Windows 7` environment, i've some ideas but i wait for some test results from @PinpointTownes #203.

For the `/bin` folder, i will have some questions e.g related to what we have to implement by code in terms of `Packaging`. So, i think it's good to have a 1st description on what is already done.

**Comment by jtkech** [comment]
> **The needs**

To be a modular application, `Orchard.Web` doesn't specify any dependencies on Modules (and Themes) in its `project.json` file. So, when you build `Orchard.Web`, Modules are not compiled. You can manually build them (e.g from VS tools) but when you launch `Orchard.Web`, we still need to load their assemblies.

- So, **Dynamic Loading** is necessary, we need to load all modules assemblies (and their dependencies) at runtime. By doing this we can also pass to the razor view engine all needed metadata references for modules views compilation (not described here). We also need to store modules specific assemblies in some probing folders, this to retrieve them in different contexts that will be described later.

- **Dynamic Compilation** is useful in a development context, e.g you can update a module source file and just hit F5, the module (and all dependent modules) will be dynamically re-compiled. Idem when you update a non ambient core project (not built with `Orchard.Web`), this core project and all dependent modules will be re-compiled. Idem when updating packages through a global `dotnet restore` ...

- **In production**, most of the time it will be better to use pre-compiled modules, but we will discuss later about the relevance to use **Dynamic Compilation** in a published context. It has been already tested in some production environment where core projects are not there and / or there is no package storage ...

**Comment by sebastienros** [comment]
Try this url: https://github.com/OrchardCMS/Orchard2/wiki/_new

**Comment by jtkech** [comment]
Thanks. Yes, i can see the wiki pages but the `_new` link doesn't work.
Do i need write access? Or can i fork this repo and then do some PRs?

**Comment by jtkech** [comment]
Thanks for the access, so i close this "issue".
