### ISSUE TITLE
Html helper extensions

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#257]
I am trying to migrate the Orchard.Modules module to see what kind of changes there are between Orchard 1 and 2.

I have managed to adapt most of the files and the existing structure.

In the 'Features' view, an Html.UnorderedList extension method is used.
I wonder if we will still use this kind of helper and in which project these extensions should be declared.

**Comment by alexbocharov** [comment]
@agriffard, At the moment in [src/Orchard.Abstractions/Mvc](https://github.com/OrchardCMS/Orchard2/blob/master/src/Orchard.Abstractions/Mvc/)

**Comment by alexbocharov** [comment]
This is an alternative to `https://github.com/OrchardCMS/Orchard/tree/dev/src/Orchard/Mvc`

**Comment by sebastienros** [comment]
I would refrain from trying to add anything than MVC doesn't. Just to prevent cluttering between Orchard and MVC. We should ensure that Orchard development is as close as MVC. 
Most of the time Tag Helpers are a much better fit than Html helpers, and probably already exist. In this case just create a `<ul>` tag and use bootstrap cards.
