### ISSUE TITLE
dotnet pack commands broken

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#266]
Since the modules are in `src/Orchard.Cms.Web`

**Comment by alexbocharov** [comment]
Fixed https://github.com/OrchardCMS/Orchard2/commit/a6c90b6b2c5b053d3d821c11eec9e5999a34dab3

@sebastienros I suggest to make the publishing of packages in MyGet

**Comment by sebastienros** [comment]
Thanks, it couldn't find it as I was searching file from VS.NET. 

MyGet could be useful. But we need to update the version numbers in order to not be blocked later as we can't go down. So verly low priority.
