### ISSUE TITLE
[Design] Tokens

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#273]
Time to work on porting the Tokens modules. Please share you current struggles, what you like, and how you would like this module to look like.

Some ideas:
- Make it optional. The modules don't have to reference it or "depend" on it, they just call it and if the module is not enabled then the UI hint is not displayed and the text is not tokenized.
- Use a popup to make it work better (no glitches) and support advanced UI like search, or embedded doc.
- Change the tag to remove the old `{foo}` syntax, just support `${foo}` or change it to `{{foo}}`
- We could also adopt another language like [handlebars](https://github.com/rexm/Handlebars.Net) which supports lists
- Rationalize how lists are used
- Should we use a function-like syntax to have parameters on tokens?
- Should we have a token filter to apply them on the rendered html, for instance to alter the user-edited content, like images, or custom scripts (snippets)

**Comment by sebastienros** [comment]
I know @LombiqTechnologies is a big fan of [Liquid](https://shopify.github.io/liquid/basics/introduction/) what ideas should we take from it?

**Comment by Skrypt** [comment]
We would need to find the + and - from each of them.
Liquid has a large base of themes. Yeah, I know, those templates are useless outside of the scope of Shopify unless you build almost the same data structure than what they have. So, that does'nt make it a strong point. I think we would need to evaluate what both can and cannot do to. 

https://engineering.linkedin.com/frontend/client-side-templating-throwdown-mustache-handlebars-dustjs-and-more

I have'nt read this all but that's a nice find.

**Comment by Skrypt** [comment]
> * Use a popup to make it work better (no glitches) and support advanced UI like search, or embedded doc.

I had in mind with the new admin theme to use a bootstrap modal instead of the dropdown to be able to see more detailed information about the tokens.

> * Change the tag to remove the old {foo} syntax, just support ${foo} or change it to {{foo}}

Change it to {{foo}} seems like the best bet.

> * Should we have a token filter to apply them on the rendered html, for instance to alter the user-edited content, like images, or custom scripts (snippets)

YES !

I need to read more about Handlebar but it looks nice. I've just started working with Liquid on a project that is not Orchard related so I'll be able to compare over time.

**Comment by Skrypt** [comment]
And other idea would be to step right now into the WebComponents world ?

**Comment by Piedone** [comment]
Re Liquid: since it's a templating syntax, and what we need here is a much smaller subset of features, at most I'd use it as inspiration for the syntax (otherwise full Liquid support exists for Templates and views).

The only thing that I think could be borrowed is the variable print syntax Sebastien mentioned (i.e. `{{foo}}`).  The syntax used for Liquid filters (like `{{ "title" | capitalize }}`) could inspire our function syntax but I think the current one is actually better.

For more Liquid syntax info see. https://shopify.github.io/liquid/

**Comment by sebastienros** [comment]
Looking at [Dust](http://www.dustjs.com/) right now

**Comment by Skrypt** [comment]
The thing with Liquid is that it restricts also the access to types. For making a class available to liquid you need to create a Class that inherits from "Drop". That's a nice feature.

**Comment by sebastienros** [comment]
Dust has filters too, using `|`, and doesn't have logic, so simpler, but its tags (helpers) can be extended and support if/else or equality alike.

**Comment by Skrypt** [comment]
I'm just asking myself if we won't have to rethink this later on if we will want to use WebComponents. It would be as simple as using <template></template>. But I think we would be bound to use Polymer for having all the functionalities that Tokens require. 

http://webcomponents.org/articles/introduction-to-template-element/

http://x-tag.github.io/ not sure what it is yet.

**Comment by Skrypt** [comment]
Github uses Liquid + Handlebar. I think the advantage though with Liquid is about SAS.

**Comment by sebastienros** [comment]
Common concepts between Dust, Handlebars and Liquid, they have:
- expressions (known as objects in liquid)
- helpers (known as tags in liquid)
- filters

**Comment by sebastienros** [comment]
@Skrypt webconponents is too chatty, and it's tags.

**Comment by Skrypt** [comment]
I agree, but sad it's not mature enough. I'd be happy with Handlebar and/or Liquid 😉

**Comment by sebastienros** [comment]
What it looks like right now:

![image](https://cloud.githubusercontent.com/assets/1165805/19400610/c43e956e-920b-11e6-86a7-ce342a095078.png)

And the result in the editor on publication

![image](https://cloud.githubusercontent.com/assets/1165805/19400594/b494b576-920b-11e6-924f-5959c91606b2.png)

I am currently using handlebars as the liquid syntax is more cumbersome on collections.
