### ISSUE TITLE
Migrate to OpenIddict beta2

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#276]

**Comment by PinpointTownes** [comment]
Here's what needs to be changed: https://gist.github.com/mjrousos/523eee36ddf1db2ac61e8b40e36dcf74#gistcomment-1900571

**Comment by PinpointTownes** [comment]
Reassigned to me.

**Comment by PinpointTownes** [comment]
Unfortunately, I don't any much time to work on this ATM, so this will have to wait.

**Comment by jersiovic** [comment]
@PinpointTownes JFYI I have rebased OAuth branch on the head of Main branch.

**Comment by PinpointTownes** [comment]
FYI, the `alpha1`/`alpha2`/`beta1` packages will be removed in the near future: https://github.com/openiddict/openiddict-core/issues/341.

**Comment by jersiovic** [comment]
Ok I will take it into account for upgrading it sooner than latter

**Comment by Jetski5822** [comment]
@PinpointTownes @jersiovic  was this done?

**Comment by PinpointTownes** [comment]
@Jetski5822 yep!
