### ISSUE TITLE
Error enabling or disabling a feature

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#277]
I tried to migrate Orchard.Modules.
When I want to enable a feature calling featureManager.EnableFeaturesAsync(...), there is an error :

> The connection does not support MultipleActiveResultSets.

**Comment by sebastienros** [comment]
That's bad :/ I hate these ones, as it requires to track the session/transaction creations to find the issue. How can I reproduce it, can you try from a simple controller/action? This way I would not need your module to fix it.

**Comment by agriffard** [comment]
I have an IFeatureManager in the AdminController and in the ModuleService. 
If I call the same code that there is in the EnableFeaturesAsync method in the controller instead of the ModuelService, there is no error.

**Comment by agriffard** [comment]
I made some tests enabling and disabling features.
For example, if I disable Orchard.ContentFields, I'd expect that the fields wouldn't be displayed in edition or on the front, but it is not the case.
 
What would prevent these behaviors ?

**Comment by sebastienros** [comment]
Check that the database has been changed and the module is not enabled anymore there. Also check if it works after restarting the app which would mean the change hasn't been detected.

**Comment by sebastienros** [comment]
Where is the module so I can test it? I have added this to the current sprint. I will work on the Tenants management in parallel.

**Comment by agriffard** [comment]
A feature disabled had "EnableState":"Falling" in database .

**Comment by agriffard** [comment]
And reenabling it makes it change to EnableState":"Rising".

**Comment by agriffard** [comment]
I pushed an initial commit.

**Comment by agriffard** [comment]
Orchard.Modules needs to be added to the features in 'core.recipe.json' in Setup.

**Comment by sebastienros** [comment]
Thanks.

NB: you should create branches instead of committing to master directly. And when it's ready either create a PR if it needs review or merge it back. This way we don't get unwanted work-commits, or breaking changes because of unfinished features.

**Comment by sebastienros** [comment]
I fixed it, there is a module branch now

**Comment by agriffard** [comment]
Thank you. Sorry, I should have done that from the beginning.
