### ISSUE TITLE
[Route] annotation doesn't work

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#278]
I'm working on a module that provides a versioned Web API based on a custom-header: "api-version".

I want to use same route for different actions in a controller, one for one version and the other for other. So, I need [Route] working properly. Problem is when I use a [Route] Annotation with any Action it turns inaccessible: Ex: [Route("api/data")]

Is there any reason for this behaviour? I'm at the head of oauth2 branch., maybe is sth fixed in master branch? or is it due to a design decision?

Happy to be back for spending time on Orchard 2 :)

**Comment by jersiovic** [comment]
This issue https://github.com/OrchardCMS/Orchard2/issues/282 could explain why annotation doesn't work.

**Comment by jersiovic** [comment]
Despite I found an explanation to #282 issue. I'm not able to make the annotation work

**Comment by sebastienros** [comment]
What are the repro steps? Or a link to the feature you are trying to use.

2016-10-21 11:11 GMT-07:00 Sergio Navarro <notifications@github.com>:

**Comment by sebastienros** [comment]
Can you provide a simple repro I can run on master?

**Comment by jersiovic** [comment]
Fixed at https://github.com/OrchardCMS/Orchard2/pull/695
