### ISSUE TITLE
Create more Tokens

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#289]
This issue is to track all the tokens that need to be done, and what modules need to provide them.
We can start with the list we have already in O1.

**Comment by agriffard** [comment]
Tokens have been replaced by Liquid templates and filters.

We could use this thread to give ideas about useful Liquid filters we would like to provide.

**Comment by sebastienros** [comment]
Maybe start with what's in O1 and see how it's done in Liquid. I already added a few for content related usage (display_text, display_url).
