### ISSUE TITLE
[Design] Tenants module

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#290]
I am beginning to work on the tenants module. This should be pretty straightforward but I still have some suggestions to make.

In O1 we can preset some values for the setup screen. We can also decide which modules and themes are available on the new tenant.

For an MVP (Minimal Viable Product) I would suggest to remove the possibility to define presets, and instead have the full Setup experience as part as the tenant creation. I don't see any reason why we would set some values and not the others. Or this scenario must be really rare. Please provide some examples otherwise and how not having this would not have any other mitigation.

Because we don't have the notion of available modules per tenant, yet, I won't implement this in the first version of this module. We can still add it once we have the feature.

The UI would and behavior would other than that be identical to O1.
Please share any ideas to make it better. Or things that you don't like in O1 and should be discussed.

/cc @Piedone

**Comment by sebastienros** [comment]
One suggestion I would have is to provide tenants management tools as part of the module, like the Command line tool that can target multiple tenants at once (I think it's still a PR on O1), or being able to enable/disable modules without having to log into the specific tenant. Any other administrative operation a landlord should be able to do on its tenants?

**Comment by Piedone** [comment]
The "preset" feature is needed for SaaS use-cases where sites are operated in bulk but which should be set up quickly without an Ops person supplying an SQL connection string (and sometimes by a marketing person for demonstration purposes). You can always implement your own setup screen of course but the current one is sufficient in the cases I know and thus I wouldn't remove the feature.

The obvious example is DotNest but I know about at least three companies who do something similar for their customers. While I wouldn't like to disclose them publicly I can give contacts in private if you'd like to inquire.

**Comment by jersiovic** [comment]
I would love to have:

- A log per tenant visible at one click next to each tenant name. It will show only logs related to that tenant. 
- A tool for registering  users on all tenants or in a subset. In fact it would be more useful we can add users to parent tenant and mark them as available on children tenants if multitenant module is enabled..
- Have the possibility of executing a recipe on all the tenants or in a subset.
- To have the option of viewing the recipe journal of the last recipe executed for each tenant and an icon with an alert showing sth didn't work properly if sth failed with last recipe execution.
- Info related to the size of disk each tenant uses for media, number of content items, statistics or request per tenant, ....
- To have a hook for providing third parties modules that extend the actions or Info provided per tenant in this module
- Remove tenant action that removes all its tables and its folders
- Clone tenant action that will copy tenant tables on new ones with the prefix of the new tenant.
- Backup all tenants or a set of tenants. Maybe YesSql can provide backup/restore methods independent of the db and independent of import/export feature implemented on drivers, that will allow us to have an exact copy of that tenant compatible with same orchard version and modules. It will be very useful if you have different multitenant servers with same Orchard version for moving one tenant from one server to another knowing that the tenant backup can be restored exactly as it was in the original server. Currently with import/export we need to be sure every module we use has implemented import export on their drivers and that there is not any data stored in other tables which is not reflected on a recipe.
- Restore a tenant from a backup

I know all of this is too much for a MVP, the intention is we can agree on the address this module should point.

**Comment by sebastienros** [comment]
@jersiovic I think all these requirements are independent from this module (minus one or two of them) but it's good information to take into account when designing the multi-tenancy infrastructure such that we can do it with modules. 

For the backup, I think we could have a custom Deployment Step to handle all the content from the db and everything else. Please take a look at the 10/25 meeting video to see how.
