### ISSUE TITLE
Validate part drivers

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard2#292]
Sorry no time right now to retrieve the details and how it can fit in O2.
- But, when submitting a content item form, the idea is to have the ability to `Validate` model values of all parts without any database writing, this before creating and / or updating a content item.
- As an example, in O1, we are using a workaround to reduce transaction logs related to comment submissions through the front end (then we also needed to adapt the audit trail module).
- Also have a content type `Versioned` option. Then, when publishing, if this option is set a new content item version is created, otherwise the current version is updated.

Best.

**Comment by sebastienros** [comment]
I think everything is already handled, in O2 a content item is already a version. And none is created if the object is not valid, but I need to validate it as I haven't tried for a while. I agree with the concern.

I don't understand the `Versioned` requirement. How is that different from `Draftable` in O1?

**Comment by jtkech** [comment]
Indeed we could use the `Draftable` option but we would need to adapt its usage, that why i talked about a new option to be more clear.

As i remember, even with `Draftable` = false, in the admin controller a content item is first querried with the `DraftRequired` option, so a new content item is always created.

Here, according to the option, we would need to use the `Latest` option ... I already do this but don't remember details.

**Comment by jtkech** [comment]
For the `Validate` driver you are right, none is created if the object is not valid, but you need to do a transaction `Cancel()`. So the suggestion is to minimize these transaction logs.

In the comments module, we first create a fake content item in memory then call `UpdateEditor()` on it. Then we check the model, then use `Create()`, re_use `UpdateEditor()` (a 2nd time), then `Publish()`.

**Comment by sebastienros** [comment]
> Also have a content type Versioned option. Then, when publishing, if this option is set a new content item version is created, otherwise the current version is updated.

You need to be more explicit about the differences between `Versioned` and `Dratftable`, what you are defining is exactly what O1 is doing:

**Comment by sebastienros** [comment]
For Validate, I know exactly what you are talking about, but I think O2 does it differently already. Let's check I assume if there are no SQL queries between new Transaction and Cancel, then there is no impact at all, otherwise any SELECT would write in the log, as all of them are in transactions too.

**Comment by jtkech** [comment]
@sebastienros so, at least i re-tried it on O1 (will do it on O2 if it is possible)

First, `conditionallyPublish()` depends on `contentItem.Has<IPublishingControlAspect>()` which is true when you have a `PublishLater` part. So 1st without this part.

# 1. Not Draftable and no PublishLater part

- So, you only have the `Save` button, not the `Publish` one, and when the content is saved it is automatically published ... Seems to be ok.

- But when re-editing where you get the `Latest` item, because it is `Published` and `VersionOptions.DraftRequired` is used, a new version is created through `BuildNewVersion()`.

- **So here, on each saving you get a new version in the database**.

# 2. Not Draftable but with PublishLater part

- 1st, not sure it's good to display the `PublishLater` button when not `Draftable`.

- So, here when saving the content it is not automatically published and here no new version is created.

- To publish the content you can use the `PublishLater` button or go to the contents list and then use the `Publish link`. If a published version already exists, you have to use before the `Unpublish link`.

- Here, when publishing no new version is created, only the latest which is a draft is marked as published.

- **But when the latest is published, if you re-edit and save it, as above, a new version is built**.

# 3. Note on Widgets

- Before, Widget was ok, on each saving no new version was created. But, after adding the ability to publish / unpublish them, things has been done as other content items.

- **So, now in O1 each time you save a widget you also get a new version item in the database**.

# Suggestion

So, in all scenarios multiple versions items are created in the database. My goal is to have the ability to prevent from this. Need to retrieve the details but the suggestion would be:

- When editing a `non Draftable` content, use the `Latest` option in place of `DraftRequired`. Then the content is published as before on saving (see below for the `PublishLater` button special case).

- So, after a first publishing, when you re-edit your content you act on the latest and already published content, and **you don't create a new version** because you don't use `DraftRequired`.

- But here the `PublishLater` will be useless. So maybe use the above only if there is no `PublishLater` part. Or consider that if a content type is not `Draftable` we don't display the `PublishLater` button.

Best.

**Comment by jtkech** [comment]
To return back to the `Validate` part.

> I assume if there are no SQL queries between new Transaction and Cancel, then there is no impact at all

Here, not sure if some SQL queries can have more impact than others when done before a transaction cancel, but i was mainly thinking about the creation of a new ContentItemVersionRecord and ContentItemRecord before validating the model.

**Comment by jtkech** [comment]
Obsolete
