### ISSUE TITLE
[Design] Logging support

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#300]
#### This thread is to talk about how we need to implement Logging

I agree we need flexibility, but unlike what @Jetski5822 has done previously I really think it can't be a module, as we need logging before the modules are found, and the logger factory is a Host service, not a tenant service. I also think logging should be at the infrastructure level, not per tenant. 

What I could see is a configuration file that would provide how to log, where to log. Even if it's a configuration file of our choosing. I know how the logging works in dotnet core, but I want to throw some ideas to the asp.net team to see what is the best approach in our case. It could also just be about letting people change the Program.cs as we have made it very lightweight and in a way that devs can create their own web project, Code is configuration in asp.net.

And yes, we need at least to be able to log to the files, like we did in O1, so we'll have to take some dependencies.

**Comment by sebastienros** [comment]
As a side note, we had the same issue in O1, we would be using `hostcomponents` which exactly defines what it was done for, defining the components that need to be configured, but at the host level, like DI for the host, file system providers (Azure), ... Maybe we need something similar, and I just found another location where is matters (loading certificates).

**Comment by sebastienros** [comment]
What are the currently available logging system in .NET Core?
- Serilog
- Nlog
- The ASP.NET team is thinking about rolling out a very simple file based one

Do we need to be able to change the logger by configuration, or should it require Startup.cs change?
Do we need to provide an opinionated logging configuration by default (supporting tenants, per-day files, ... )?
What should be the integration with the admin, if any? Or should the logger implementation provide such tools (see Serilog).

**Comment by jersiovic** [comment]
I didn't know Serilog. It looks good I don't know if it lacks of any relevant feature for us. 

> Do we need to be able to change the logger by configuration, or should it require Startup.cs change?

In theory it would be good we are able of changing logger by configuration to avoid forks only for changing the logger. I don't think it will be a common need but specially if you are using Orchard as SaaS and integrate it with other app you have developed maybe is useful you can change Orchard logger to use same logging infrastructure in both apps

> Do we need to provide an opinionated logging configuration by default (supporting tenants, per-day files, ... )?

The minimum of functionality you mention as a sample would be desirable at least for final users (non devs)

> What should be the integration with the admin, if any? Or should the logger implementation provide such tools (see Serilog).

IMO a desirable solution would be to delegate in specialised software like Glimpse that can be connected to the logging framework and left each one render logs in the way they prefer it. However thinking on final user (non-dev) we should provide a kind of light integration in admin with an specialised software we choose, Glimpse sounds good to me. Maybe a logging menu item pointing to the main page of the specialised software and in tenants admin page a link to see logs of that tenant pointing to that software. Orchard should provide hooks to replace or extend this light integration with this concrete default specialised software .

**Comment by sebastienros** [comment]
Should we have one file per tenant? 

If we see an issue, it's easy to know on which tenant and open the log file. But if we want to track issues we might not want to have to track all tenant files.

**Comment by Jetski5822** [comment]
Yes we should.

**Comment by jersiovic** [comment]
As I have said here https://github.com/OrchardCMS/Orchard2/pull/299#issuecomment-268924196 
In NLog sth like that can be done with this https://github.com/NLog/NLog/wiki/Event-Context-Layout-Renderer but maybe it would be more desirable to use one of those renderers, storing in httpcontext or in request the tenant name https://github.com/NLog/NLog/wiki/Layout-Renderers#nlogweb-package-
Next in NLog config we can configure one file per tenant.

In fact, I would use one nlog.config per tenant that will be included from main NLog.config https://github.com/NLog/NLog/wiki/Configuration-file#include-files
When a new tenant is created we can create a default nlog config file for that tenant that wouldll be included from main NLog.config.

**Comment by jersiovic** [comment]
Well I forgot to mention we can use When-Filter https://github.com/nlog/NLog/wiki/When-Filter#extensibility to decide which log messages should go to each tenant log

**Comment by jersiovic** [comment]
Related to the topic of having one nlog config file per tenant what would be nice is we could add programmatically the include for tenants log config using NLog config API https://github.com/nlog/NLog/wiki/Configuration-API instead of adding the include lines directly to the main nlog config file.

**Comment by DanielStolt** [comment]
I agree that logging should not be an extension; it needs to be very core.

Also agree with @jersiovic that logging framework should probably not be substitutable. Instead we should use a logging framework that *itself* supports plugging different providers. In any case, Startup.cs change is totally fine if you need to change it out.

I'm torn when it comes to logging per tenant, but I think the way it works today is probably best (the log is global, but tenant is a value that you can filter on, this way you can configure different outputs for different tenants if you want).

Yes, somewhat opinionated default configuration is good - should be something useful out of the box.

I don't see why there should be any integration with admin UI - logging should be an aspect configured at the host level.

**Comment by sebastienros** [comment]
After I wrote the my latest comment I also realized it would be very hard to maintain the logs if they were spread across tenant folders. Having a single one is better IMO.

Also agreed it's a host decision, and anyone could create their own host to change the logger. As long as we don't add any dependency in the modules. It's our decision in the OrchardCms project to select which logger we use by default.

That said, we can probably merge @jersiovic PR as soon as it's ready, again.

**Comment by jersiovic** [comment]
PR ready again.
Io maintain things simple and generic I see sensible if Orchard only provides the tenant name to the logger. A module that offers an UI through admin should be offered through a third party module outside of Orchard Core because if it was in Core it would condition everybody on how organize their logs to be read by this module.

**Comment by Jetski5822** [comment]
We have NLog, and maybe an implementation of Log4Net soon too. Closing as initial implementation done
