### ISSUE TITLE
Any timeframe for the roadmap toward Orchard V2 RTM

### ISSUE THREAD

**Issue by JanSichula** [OrchardCMS/Orchard2#306]
Hello,

first of all let me express that I am excited about Orchard V2 being implemented on top of ASP.NET Core. ASP.NET Core needs a premiere CMS/Blogging project and Orchard V2 has got very good qualifications to become one with fantastic and experienced team behind it. Having expressed this conviction of mine, here comes my question or a plea.
I am in charge of project where a new church web site is going to be implemented. After much deliberation, it seems like the Orchard best suits our needs. Yet the decision also involves the dilemma whether to wait for V2 RTM or go with V1 hoping that some workable migration path shall be made available once V2 goes gold. Now I was able to discover interested roadmap at https://github.com/OrchardCMS/Orchard2/wiki/Roadmap but for all it’s value, it is missing any time hints. I can understand that timeframe for a project of this size and difficulty is a every sensitive issue but still I would point to the good example of ASP.NET team who were all the time transparently revealing timeframe for ASP.NET Core in the best possible intention and adjusting along the way when it was necessary.
I am sure there are other people watching progress of Orchard V2 who would also love to get some light on the estimated timeframe toward RTM. Please, please, any hint is much better than none at all.

**Comment by YaoaY** [comment]
+1

**Comment by sebastienros** [comment]
I will try to update the roadmap with estimates from now on. But it will vary a lot based on the people helping, and also my availability on the project. I don't want you to think this are goals, just estimates.

**Comment by sebastienros** [comment]
I have updated the roadmap with target dates for the existsing milestones.
