### ISSUE TITLE
Consider using the default access token format instead of JWT

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#310]
The OpenID module currently uses JWT tokens instead of the default encrypted format, that relies on Data Protection.

This requires using the JWT bearer middleware, which uses discovery to retrieve the signing credentials from OpenIddict's discovery endpoint. Unfortunately, this doesn't work well when people choose to use SSL and a self-signed certificate, as the `HttpClient` used by the JWT middleware will block the discovery request if the certificate is not fully trusted.

Instead, we may consider using the default token format + the OAuth2 validation middleware, that doesn't use HTTP discovery.

@jersiovic @sebastienros thoughts?

**Comment by jersiovic** [comment]
I like the idea but only if it can be set per OpenId Application. Depending on who is going to consume your web api you will want an standard like JWT or default encrypted format, and at least in my case it is very likely I have two web APIs running under Orchard one consumed by apps under my controls and others consumed by anyone interested on it.
What I would add in any of those cases in Open Id configuration page is a description explaining what a requisites a consumer will need to consume a Web Api using an Open Id Application Configuration with the values we have set. I mean: Available Flows,  Scope header, Authority header, Certificates registered as Trusted only in client or in client or server, etc ...

**Comment by PinpointTownes** [comment]
> I like the idea but only if it can be set per OpenId Application.

This is not supported by OpenIddict, as it has practical issues (what happens when an access token is issued for 2 resources and one of them wants the default format and the other one wants JWT?).

If JWT is important for you, we can find a compromise:

  - Use the default token format (opaque) by default.
  - Provide a global `appsettings.json` option to switch to the JWT format when interoperability is needed.

**Comment by jersiovic** [comment]
Well, by the moment is the minimum to avoid many questions on forums like my question because client won't have the autogenerated certificate on its trusted certificates storage. So, I can agree we can do it in this way if Openiddict is not going to provide a way to support this configuration per OpenId App any time soon.
@sebastienros do you agree?

**Comment by jersiovic** [comment]
@pinpointTownes related to the issue of having to provide a token for two resources, I think you should address the problem in Openiddict per openid application not per resource.

**Comment by PinpointTownes** [comment]
You mean per client? Heh no, this doesn't make sense, as the client is not even supposed to read the access token.

> Access tokens are credentials used to access protected resources. An access token is a string representing an authorization issued to the client.  The string is usually opaque to the client.

https://tools.ietf.org/html/rfc6749#section-1.4

**Comment by jersiovic** [comment]
I don't say the client needs to read the token. What I say is that if the bearer token contains the clientId provided when the token was requested then OpenIddict can use this Client Id to decide which mechanism he needs yo use (JWT or the other). I depende on how we configured that OpenIdApp in the Orchard. OpenId module.

**Comment by PinpointTownes** [comment]
> What I say is that if the bearer token contains the clientId provided when the token was requested then OpenIddict can use this Client Id to decide which mechanism he needs to use (JWT or the other).

I really don't understand what's the point of making the token type vary by the client, as it's only supposed to present it (it must not use it, as it's not listed as an audience).

> Does the token contains the Client Id?

When it's known, it does (the OpenID module now uses `RequireClientIdentification()` so it's safe to assume it is)

**Comment by jersiovic** [comment]
I think I understand why I'm wtong: the only thing to know how to deal with the received token is based on the resource requested all the other info is within the token so it doesn't help to know how to access the token.
Well, in the case when an access token is issued for 2 resources and one of them wants the default format and the other one wants JWT we can return an error informing that an access token for two resources that work with different access token types cannot be issued. 
At the end of the day this is a decision of the admin of the site. If admin wants to provide different access tokens for two resources it has this con that in fact he will agree cause his intention is one resource is consumed by a group of clients different than the group of clients that consume the other resource. So, it doesn't have sense same client ask for a token that gets access for both resources.

**Comment by PinpointTownes** [comment]
> Well, in the case when an access token is issued for 2 resources and one of them wants the default format and the other one wants JWT we can return an error informing that an access token for two resources that work with different access token types cannot be issued. 

For that, we'd have to register the "resources" somewhere in the DB and it's not something that the OpenID module currently does.

> So, it doesn't have sense same client ask for a token that gets access for both resources.

Well no, it's a perfectly valid scenario (here's a draft that standardizes the `resource` parameter: https://tools.ietf.org/html/draft-campbell-oauth-resource-indicators-01)

**Comment by PinpointTownes** [comment]
_Posted by @jersiovic:_

> For that, we'd have to register the "resources" somewhere in the DB and it's not something that the OpenID module currently does.

This is not a problem, we could add it if we agree it is useful.

> Well no, it's a perfectly valid scenario (here's a draft that standardizes the resource parameter: https://tools.ietf.org/html/draft-campbell-oauth-resource-indicators-01)

I agree it is a perfectly valid scenario if we talk of two resources accessible through same type of token.
What is strange is you offer two types of tokens for two differen resources an expect same Client access both at the same time. Why an admin would want to configure two different types of tokens for those two resources. If I were the admin of a soy I would configure different access types for resources accessible be different sets of clients.

**Comment by jersiovic** [comment]
I can provide a page for configuring if Open Id will use JWT token or default OpenIddict access token format per tenant. 
@sebastienros do you agree?

**Comment by sebastienros** [comment]
Same thing, OpenId site settings, the same page as for the certificate.

**Comment by PinpointTownes** [comment]
Fixed by https://github.com/OrchardCMS/Orchard2/commit/aed6b02b9260daad95776c5a6dfd1411a6434a84.
