### ISSUE TITLE
Sqlite needs some work

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#317]
I have integrated the code to get Sqlite available in master. Right now it fails, first because the migrations are not "flushed" before the table are necessary, like the Readuncommitted isolation level is not really reading the uncommitted new table. Doing a `_session.CommitAsync()` in the `DataMigrationManager` fixes this step, but I don't like having to do so. Anyhow, after that there is another exception.

Finding and fixing all the issues would probably require to add YesSql source code to the local project to understand what queries are issued, or at least add some logging, and also what is creating the sessions and the connections.

I don't really see this as a priority right now so I won't personally work on it, but would be glad to help anyone interested.

**Comment by Jetski5822** [comment]
@sebastienros Can we close?
