### ISSUE TITLE
Orchard.Roles module doesn't work properly

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#320]
If you create a new role and reboot Orchard, when you come back to roles view you find the new role doesn't exists.

Reason is Create method in https://github.com/OrchardCMS/Orchard2/blob/master/src/Orchard.Cms.Web/Modules/Orchard.Roles/Services/RoleStore.cs relays in cache to return data but uses a private var to maintain data pending of update. Problem is those too are not in sync. 

```
        public async Task<RolesDocument> GetRolesAsync()
        {
            return await _memoryCache.GetOrCreateAsync(Key, async (entry) =>
            {
                _roles = await _session.QueryAsync<RolesDocument>().FirstOrDefault();
                if (_roles == null)
                {
                    _roles = new RolesDocument();
                    UpdateRoles();
                }
                entry.ExpirationTokens.Add(_signal.GetToken(Key));
                return _roles;
            });
        }
        public void UpdateRoles()
        {
            if (_roles != null)
            {
                _roles.Serial++;
                _session.Save(_roles);
                _signal.SignalToken(Key);
            }
        }
...

#region IRoleStore<Role>
        public async Task<IdentityResult> CreateAsync(Role role, CancellationToken cancellationToken)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (role == null)
            {
                throw new ArgumentNullException(nameof(role));
            }
            var roles = await GetRolesAsync();
            roles.Roles.Add(role);
            UpdateRoles();
            return IdentityResult.Success;
        }
```
I was preparing a PR fixing it replacing local var roles per class var _roles. Problem is I've found another problem: each time I remove a role an new record with the rest of the roles is stored in db. However the GetRolesAsync method gets previous record with all the Roles so the Role is not removed. This is the reason: `await _session.QueryAsync<RolesDocument>().FirstOrDefault();` so the problem is not only that I have a new record each time, also I'm not able to read the last record, because of the FirstOrDefault(). I can replace it by LastOrDefault() to fix it but I'm not sure we want to store a record with all the roles each time a role is added/removed.

Is this behaviour on purpose for any reason? The `_roles.Serial++;` on Update roles seems to be done to take this circumstance into account ....

@sebastienros any advice on how should I fix this to fit what you have in mind?

**Comment by sebastienros** [comment]
I can repro, working on it
