### ISSUE TITLE
BodyPart_Summary

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#328]
In Orchard.Body\Views\BodyPart_Summary.cshtml:
@Html.Raw() should be used to prevent to return encoded HTML.

**Comment by agriffard** [comment]
The code that returns 200 first characters should also be modified:
`body.Substring(0, Math.Min(body.Length, 200))`
because the HTML can be cut in the middle of a markup.

We need to use a similar method than the Html.Ellipsize string extension made in O1.

Another improvement could be to add a definition setting in the BodyPart:
'Summary max characters'
By default, it would be 0 and we wouldn't truncate the summary but if a length is specified, it would be used in the generate the excerpt.

**Comment by sebastienros** [comment]
It's more complex than that, even O1 gas flaws. I'll submit something I did
on weblogs.

**Comment by agriffard** [comment]
I committed a simple fix:
`@Html.Raw(body.RemoveTags(true).Ellipsize(200))`
Suggest your solution if you have a better one.

**Comment by sebastienros** [comment]
This should work fine as you are removing the tags before ellipsizing. The limitation is that it's removing any important tag, like links, images, ...

The final solution will need to support a tag to mark the summary explicitly, and fallback to another technique if there is none, like the one you chose.
Maybe we should also accept tokenized configuration here, or just that. We would need helpers to detect a beacon, and also to remove tags.

I am also reopening it to track the feature.
