### ISSUE TITLE
Meta Title generation

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#329]
The meta title doesn't contain the title of the current content displayed.

It could be done by changing the TitlePart.cshtml:
`@{
    Title.AddSegment(new Microsoft.AspNetCore.Html.HtmlString(Model.Title), "0");
}`

**Comment by agriffard** [comment]
May be there could be another way to achieve this:
- Create a module with a SEOPart.
- Add a property MetaTitle.
- Provide definition settings with a tokenizable property similar to the Pattern in the AutoroutePart.
- The details view of this part would be in charge to change the meta title segment.

Thanks to this, people could choose if they want to use automatically the Title to generate the meta title from a token or if they want to specify another one manually.

**Comment by sebastienros** [comment]
Right now the solution is to render the element using DisplayText in the
Content.cshtml file.

**Comment by agriffard** [comment]
See #429 Generating title metadata
