### ISSUE TITLE
Use Site settings in theme Layout

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#331]
The theme layout should use the SiteName specified in the site settings.

To do this properly, please confirm we have to do these actions :
1) Inject the service:
```
@inject Orchard.Settings.ISiteService SiteService
@{
    var site = await SiteService.GetSiteSettingsAsync();
}
```
2) Change the title segment
```
@{
        Title.AddSegment(T[site.SiteName], "after");
}
```
3) Change the Project Name in navbar-header:
`<a class="navbar-brand" href="#">@site.SiteName</a>`

**Comment by agriffard** [comment]
The homepage link also needs to be changed :
 ```
<ul class="nav navbar-nav">
      <li class="active"><a href="~/">Home</a></li>
</ul>
```
The BaseUrl setting could be used but it should be more appropriate to generate it with HomeRoute.

What is the best way to do it?

**Comment by sebastienros** [comment]
Don't touche BaseUrl for now, you can create a PR with the rest, looks good.
