### ISSUE TITLE
Use Orchard 2 for a blog

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#332]
I saw the first commit of @sebastienros on a blogs branch.

For a few days, I have been thinking about it and I now have one goal : Use Orchard2 to run my [website](http://www.antoinegriffard.com).

I hope this thread will allow us to list the minimal features and steps needed to run a new blog (or even better: migrate an existing one).

**Comment by agriffard** [comment]
Here is what I did to setup my blog manually (in the future, I guess there will be a recipe):

1) Create a 'Blog Post' content type:
Add Autoroute, Body, Title parts
Organize parts in desired order: Title, Autoroute, Body, Blog fields
Edit AutoroutePart settings: Use a token in Pattern (ex: {{slug}} ) or check 'Allow custom path'

2) Create a 'Blog' content type
Add Title, Autoroute, Body, List parts
Organize parts in desired order: Title, Autoroute, Body, Blog Post fields
Edit AutoroutePart settings: Check 'Allow custom path'
Edit ListPart setting: Choose BlogPost for 'Contained Content Type'

3) Create your Blog content item.

4) Add Blog posts to your blog.

**Comment by agriffard** [comment]
I need to be able to manage the site Settings in the admin: To set the BaseUrl, SiteName, PageSize, HomeRoute (point it to my blog route or url)

**Comment by sebastienros** [comment]
I also want to work on it to see what it feels to build a site and what is missing.

Agreed with Settings, that's my next task, it's necessary for all modules and already a limitation for Search. I have added it to the backlog for visibility, I will do something reusable.
For tags, we can just create a text field that would contain comma separated values. It doesn't provide listing by tags, but it would already work with search.
I also see we need to be able to define the homepage, I will create a module for it, and a Part.
Then Menu management. With probably a ViewComponent while widgets are not available, so we can render a menu from the Layout directly.

I am currently trying to use this theme: https://startbootstrap.com/template-overviews/clean-blog/

**Comment by sebastienros** [comment]
I have added a new token block helper for `List`, now you can use this expression `{{#container}}{{slug}}/{{/container}}{{slug}}` for both blogs and blog posts.

**Comment by agriffard** [comment]
To automatically create some content types BlogPost and Blog, would we use a Migration in an Orchard.Blogs module or import a recipe (see #350) ?

**Comment by sebastienros** [comment]
Recipe, definitely.

**Comment by sebastienros** [comment]
Another thing I think we need and is easy to do, reverting a previous decision, is that we should be able to have a list of different content types. We talked about it during a previous meeting and I asked who had used it, actually I think for Blogs of "feeds" in general it's important. For instance the homepage feed on orchardproject.net accepts different kinds of posts, like external link, article, ... And it's very easy to implement actually. So I will do it.

**Comment by agriffard** [comment]
Support for multiple content types in lists added in #361

**Comment by sebastienros** [comment]
Created a Project https://github.com/OrchardCMS/Orchard2/projects/1

**Comment by agriffard** [comment]
ContentDefinitionStep allow to create content from recipe : #419
Blog recipe, TheBlogTheme.
See https://github.com/OrchardCMS/Orchard2/projects/1 to follow progress.
