### ISSUE TITLE
Module move about

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Orchard2#334]
# AspnetCore Modules

At the moment we have two projects called, Microsoft.AspNetCore.Mvc.Modules.Abstractions and Microsoft.AspNetCore.Mvc.Modules. I think we should refactor these slightly... This does mean creating more projects, and some renaming.... 

Renaming

As only a few classes have anything to do with MVC, we should rename these too

Microsoft.AspNetCore.Mvc.Modules.Abstractions -> Microsoft.AspNetCore.Modules.Abstractions
Microsoft.AspNetCore.Mvc.Modules -> Microsoft.AspNetCore.Modules - this should be the main project that has the .AddModules() stuff in it and should reference everything else.

New projects introduced...

**Microsoft.AspNetCore.Modules.Mvc** holds all the mvc items like, filters, and model binders etc.
**Microsoft.AspNetCore.Modules.Routing** Router Middleware, area route configuration and homepage route
**Microsoft.AspNetCore.Modules.Hosting** WebHostExtensions, and everything inside of Orchard.Hosting. AddHostCore needs to be split with the Shell dependencies being moved to Orchard.Environment.Shell under a AddShellComponents() or something like that.

Other changes...

**ISite** I feel this is too opinionated. To get around this, I feel like ISite should be just a IConfiguration interface, and inside of Orchard... we should have a IOrchardSite... with the necessary items pulled out.

**Errors** I think maybe we should ditch the Orchard Specific ones and move to the core ones as much as possible, and rename them from Orchard to something else, ModuleException, etc.

Will add more stuff as im going through... ideas guys...

**Comment by sebastienros** [comment]
There is already an `mvc` branch that does a split between MVC and the rest. I don't think it works anymore but it has some of these ideas. I am not sure what to split between Orchard and MVC, we should wait to see what ASP.NET intends to do for modules. Because then we'll have to rename this project, and probably not care about not depending on MVC.

So I'd say gather your ideas, but wait to know ASP.NET plans, this should be settled soon.

**Comment by Jetski5822** [comment]
Do you know when this will settled?? Soon as in this week??

**Comment by sebastienros** [comment]
I don't think this week, that's thanksgiving ;) and even if it's a month, wait for it. My other branch (if you are talking about search) has been fixed, I commented on the PR.

**Comment by Jetski5822** [comment]
@sebastienros I merged your Search branch in earlier. Its your mvc branch. let get that building with a PR, ill merge it in an start iterating on it. Even if the components are broken out then brought back together again its a good start.

**Comment by sebastienros** [comment]
Ok, for the same reason, I don't want to merge MVC or continue working on that until I know what the ASP.NET plans are.

**Comment by Jetski5822** [comment]
I dont like this holding pattern :(
