### ISSUE TITLE
After Upgrading to ASP.Net 1.1.0 Orchard crashes

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#338]
If I checkout commit previout to those that Upgrade Orchard to  ASP.Net 1.1.0 I can run Orchard without problems. But with the head of the master branch it can be build without problems but it fails without starting the app when I try to run it.

I have found this related issue on ASP.Net GitHub in https://github.com/aspnet/Home/issues/1719#issuecomment-261803230

**Comment by jersiovic** [comment]
CC: @agriffard I think it is interesting you are aware of that problem

**Comment by sebastienros** [comment]
Maybe you have an outdated CLI. Try to uninstall any preview release of the SDK, and also in your users folder I think there is a copy of the cli that should be deleted, I can't remember where, I will ask.

**Comment by jersiovic** [comment]
I have uninstalled all net.core packages and reinstalled Net.Core 1.0.1. 
And executed: ´git clean -xdf´ and  ´build.cmd´
But still same problem.
@sebastienros the folder I should remove is c:\Users\{username}\.dnx\ ?

**Comment by sebastienros** [comment]
.NET Core 1.1.0 please

**Comment by sebastienros** [comment]
SDK and CLI

**Comment by jersiovic** [comment]
Ah ok, I didn't see it was available through all downloads link. So I thought Asp.Net version didn't have to match with Net.Core ... downloading 1.1.0 version (SDK and CLI)
Thank you
