### ISSUE TITLE
Orchard shapes, Content Types as => View Components & Tag Helpers

### ISSUE THREAD

**Issue by weedkiller** [OrchardCMS/Orchard2#345]
I am trying to migrate a site over, and our modules, and I realizing a lot of overlap from the old architecture to the new ASP MVC Core features.

Now that the new ASP MVC layout is simpler, will orchard content types be View Components renders as Tag Helpers?

Can you give us an example and shed some light on where this is heading please.

**Comment by sebastienros** [comment]
Content Types, View Components and Tag Helpers are very different, and not really related.

Would you be able to provide a more specific question, or even state what you would like to do so I can give you a good example?

**Comment by sebastienros** [comment]
And feel free to join us on gitter (link in readme.md) to have a better exchange

**Comment by weedkiller** [comment]
Thanks for responding.

So, at least from a developer consuming the bits for plug-ins POV I noticed _similarities_ in your design partly because they were forward thinking in composing the UI, which is now finally done with tag helpers and view components.

I posted more on the gitter chat
