### ISSUE TITLE
MarkdownBodyPart

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#357]
I suggest to create a custom part for Markdown instead of using flavors and we can't switch back and forth to Html. The stored content is different.

We don't need to render live results like in O1 but use Live Preview instead.
Also there is a dotnet core implementation https://github.com/Knagis/CommonMark.NET that is supposed to be fast to render it.

There could be a conflict with setting the BodyAspect value if both Body and MarkdownBody are attached to the same content type, but that's not something that really make sense, so I don't think we should handle it.

We should also create a field that behaves the same as the part.

**Comment by DanielStolt** [comment]
This would mean that the whole concept of flavors is removed correct?

**Comment by sebastienros** [comment]
Not sure about removing flavors yet, but make it HtmlFlavor only. So it would just change the editor, not have format specific logic, like the Filters needs to check in O1.

**Comment by sebastienros** [comment]
I personally would love a minimalist editor like the one on SO, and this is also true for the BodyPart

![image](https://cloud.githubusercontent.com/assets/1165805/20722481/a31ec7a8-b61b-11e6-8d50-010504326c3e.png)

**Comment by bleroy** [comment]
What's wrong with the editor in Orchard 1? What I don't like with the SO editor is that it's horizontally split, which is kind of ok for short comments, questions, and answers, but not good for long posts. Vertical split is the way to go.

**Comment by sebastienros** [comment]
I don't think we need an editor with preview when we have content preview.

**Comment by sebastienros** [comment]
In case it was not clear, when I pasted the editor screen shot, I just wanted to show the editor part, I don't want the horizontal split either, I just don't want any at all.

**Comment by bleroy** [comment]
Aaaah, I see. Well, that's debatable: for a page editor, yes. For a blog post editor, the author will likely prefer to focus on the body, and won't care about the rest of the page. So I'd have both options, and make sure it can be configured at the type level.

**Comment by sebastienros** [comment]
Markdow flavors !

**Comment by bleroy** [comment]
No, part and type settings...

**Comment by sebastienros** [comment]
Yes, markdown flavor, as a TypePart settings, like in O1 with Body flavor.

**Comment by sebastienros** [comment]
It's a dropdown that appears in the part setting (for the type) where you select how the editor should look like.

**Comment by DanielStolt** [comment]
You might check out the markdown editor I built for our website, I think you might like it. It is implemented as a language on top of CodeMirror. It has pretty decent syntax highlighting and keyboard support etc.

http://www.ideliverable.com/blog/why-tabs-are-better-than-spaces#comments-anchor

Scroll to the bottom where you can write a new comment.

I would be happy to contribute this to Orchard.

**Comment by sebastienros** [comment]
@DanielStolt I have found a popular editor that works exactly like yours, also using codemirror. Feel free to create a PR if you think yours is better.

**Comment by DanielStolt** [comment]
I feel rejected and hurt.

Which one did you find? URL?

**Comment by sebastienros** [comment]
https://github.com/NextStepWebs/simplemde-markdown-editor

**Comment by DanielStolt** [comment]
It looks quite OK. But mine is smarter in dealing with the selection, e.g. if the caret is in a word and you hit Ctrl+B then the word gets selected and then bold added around it. SimpleMDE seems to behave rather dumb in this regard. On the other hand it supports more configuration options.
