### ISSUE TITLE
[Design] Menu management

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#358]
This issue is to track requirements for the Menu module. I think we should keep it very close to what is in O1 as it doesn't seem to a source of pain for anyone.

## O1 Challenges
- Performance https://github.com/OrchardCMS/Orchard/issues/4867
- Breadcrumbs https://github.com/OrchardCMS/Orchard/issues/3537
  - For this one I suggest we create a different module with html helpers and services, that could also use some data from menus.
- Content items as menu items https://github.com/OrchardCMS/Orchard/issues/4630
  - We should not allow content items to be menu items, for the related issue, and also for performance reasons. Just logical content menu items should be allowed, so when a content is deleted, the menu would either be removed or return a 404, and would have no impact if the menu item is deleted.
- Accessibility https://github.com/OrchardCMS/Orchard/issues/4461
  - For anything that is highly client side driven (Menu, Layout, ...) we should make an extra effort to support keyboard shortcuts and make it [aria](https://www.w3.org/WAI/intro/aria) compliant.
- Drafts
  - I think @jagraz mentioned it, we should be able to have draftable menus. This should be easy if we choose to make menus content items.

### Menu Items 
In O1 are content items. I adds complexity and performance issues. We had content items to make menu items extensible, for instance by being able to add a CSS field. I don't see any other usage than css, or maybe other simple fields for custom properties but it's very limited. Usually menu item types are dedicated implementations like Query, Taxonomy, ... which come with their own UI and content. However I think we'll need to keep it this way, and I will propose a better design to fix the drawbacks.

## Suggested design
- Localization will follow the current model from O1, which is that nothing has to be done and let it handled by widgets ;)
- Menu will be a content type, and the editor will be based on the default content editor, allowing drafts or scheduled publishing
- Menu items are content items. Their types have the `MenuItem` stereotype.
- We will make use of the Dynamic Cache feature to cache menus independently. we might also decide that response caching is sufficient. 
- Use the same JavaScript library to edit the menu

### Storage
I suggest that we store the full menu hierarchy, including all menu items (content items) in the menu document. This will solve the major performance issue as their will be a single document to load, whatever the complexity of the menu (not taking into account other menu item sources like queries).
The idea is that we would create a custom `Content__MenuItem_Edit` shape to edit the menu items (or a custom controller) and return the content item document instead of persisting it. This way we can still reuse content definitions, parts and fields, but we would ignore the storage and indexing of menu items.

**Comment by sebastienros** [comment]
http://decentcms.org/docs/decent-core-navigation/navigation-file

**Comment by DanielStolt** [comment]
@sebastienros Maybe this issue should be in the O2 repo?

Anyway, I have worked on several projects where we have used the extensibility of menu items heavily. CSS is a common requirement, but we also commonly use it to:

- Add images or icons
- Add text fields to categorize menu items
- Render menu items as separate headings and body texts
- Add SEO elements to menu items

So the decision to keep this extensibility is quite important IMO.

**Comment by sebastienros** [comment]
This comment makes me realize that there are two aspects of menu management, the `INavigationProvider` part that is the API to build the menus, and the management UI part which lets us create menus from the admin.

@DanielStolt can you give some examples of how you use these?

> Add images or icons
Is it just about being able to add a field to a menu item type so the editor of this menu item can show them?

>  Add text fields to categorize menu items
Fields again?

> Render menu items as separate headings and body texts
I don't understand, example?

> Add SEO elements to menu items
What kind?
Also related probably. should we also support accessibility attributes OOB? Or just as an extensibility?

**Comment by DanielStolt** [comment]
Images, icons and categorization: yes, we normally do this using fields of the appropriate type.

Examples:

- Add a media library picker field to allow editors to specify an image to be rendered for the menu item.
- Add a boolean field to allow editors to specify that a particular menu item will require authentication, and have the theme render them differently if the user is not authenticated
- Add a text field to allow editors to specify a category on each menu item, and have the theme group the menu items into these categories

Separate headings and description texts: sorry I should not have said "body", that was confusing. I meant scenarios where you want the menu to not just be one text, but perhaps a heading and a longer description text, rendered in some appropriate way by the theme. Usually fields will suffice for this purpose too.

SEO elements - struggling to think of examples now, but I think our IDeliverable.Seo module adds a new part that you can add on menu item types to give them a bunch of SEO-related functionality.

So it's not only about fields, sometimes it's very useful (I would say crucial) to be able to add parts to menu item types also.

Accessibility attributes are an interesting question. I assume you mean primarily keyboard accessibility? I am torn here - on one hand it would feel like involving too much HTML-specific detail and leaking abstraction, but on the other hand it's such a common requirement that perhaps we should be pragmatic and include it OOB?

**Comment by sebastienros** [comment]
Great, I assume that parts and fields + custom theme will solve all of these.

**Comment by DanielStolt** [comment]
Yes, absolutely. I just wanted to make sure you don't remove them.

**Comment by sebastienros** [comment]
Exactly

> In O1 are content items ... blablabla complex blablabla ... __However I think we'll need to keep it this way__

**Comment by DanielStolt** [comment]
haha, yes exactly

> So the **decision to keep** this extensibility is quite important

**Comment by Skrypt** [comment]
You guys are funny to read :smile

**Comment by bleroy** [comment]
Another thing to keep in mind: menus generated from query results (taxonomies, projections, etc.). That's what's going to be the case for big, dynamic sites. On the other end of the spectrum, small sites barely need anything else than static name/url pairs that could fit in a single json file or database record.

FWIW, that's why in Decent, I have providers for navigation, the simplest of which handles a disk-bound json file: [file-navigation-provider.js](https://github.com/DecentCMS/DecentCMS/blob/master/modules/core/navigation/services/file-navigation-provider.js), and the most complex so far is [the one that drives the documentation TOC using a map-reduce query thingy on actual content files on disk](https://github.com/DecentCMS/DecentCMS/blob/master/modules/core/documentation/services/documentation-toc-part.js). The latter was pretty fun to write, check it out. The TOC thing also has a bunch of [tests here](https://github.com/DecentCMS/DecentCMS/blob/master/modules/core/documentation/test/index.js).

**Comment by sebastienros** [comment]
I am with all of you here, everything based on content types for extensibility (fields) and custom providers (query, taxonomy) like in O1, and also all of it stored in a single content item document. And this can be versioned too. I made good progress, on track for Tuesday's demo.

**Comment by sebastienros** [comment]
Done
