### ISSUE TITLE
Implement Hml Editor flavors

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#363]
Like in O1, be able to use custom editors for HTML parts and fields.

Example of license friendly editors:
- http://jakiestfu.github.io/Medium.js/docs/#partial
- http://summernote.org
- https://github.com/Alex-D/Trumbowyg

Note: TinyMce and CKEditor are LGPL, I am not sure about pricing impact on deployments.

**Comment by agriffard** [comment]
Would it work if we separate the wysiwyg editor in another module? 
Would the option appear/disappear if we enable/disable it?
