### ISSUE TITLE
Ephemeral signing credentials shouldn't be generated by default

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#368]
Since `AddEphemeralSigningKey()` is called on startup, an ephemeral signing key is always generated by OpenIddict (tho' it's potentially later removed by `OpenIddictConfigureOptions`): https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Cms.Web/Modules/Orchard.OpenId/Startup.cs#L98

Unfortunately, as mentioned in a previous ticket, this operation is _fragile_ and won't work everywhere (see https://github.com/openiddict/openiddict-core/issues/204 for a concrete case). Not to mention that it's also time-consuming (generating 2048-bit RSA keys is quite expensive). For these reasons, a signing key should be only generated when the testing mode is enabled. 

Consider delaying the generation part in  `OpenIddictConfigureOptions`: https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Cms.Web/Modules/Orchard.OpenId/OpenIddictConfigureOptions.cs#L36

/cc @jersiovic

**Comment by jersiovic** [comment]
Fixed
