### ISSUE TITLE
Make sure the OpenID configuration classes/delegates are invoked in the right order

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#369]
The whole new `OpenIddictConfigureOptions` is currently registered before `services.AddOpenIddict()` is called. Since the configuration classes/delegates are invoked in the same order as they are registered, things like `DisableHttpsRequirement()` will override the logic used by `OpenIddictConfigureOptions` to determine whether HTTPS should be enforced or not.

@jersiovic please confirm this is indeed the behavior you're seeing and consider registering `OpenIddictConfigureOptions` after `services.AddOpenIddict()`.

**Comment by jersiovic** [comment]
You were right, registration order makes it to don't work properly.

**Comment by jersiovic** [comment]
Fixed
