### ISSUE TITLE
Serve files from Media folder

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#370]
What is the minimum code to add to enable a 'Media' folder to serve static files?

**Comment by sebastienros** [comment]
UseStaticFiles("Media")

Look for samples in the code where we add it for any "Content" folder in the modules.

**Comment by agriffard** [comment]
Would it be in a Orchard.Media module?

**Comment by sebastienros** [comment]
Yes, let's talk ;)

**Comment by agriffard** [comment]
We can use `wwwroot/Media`.

Then, next simple need in an Orchard.Media module would be to upload a file in a folder.
Thanks to this, we would be able to develop a plugin for the Wysiwyg Html Editor to insert a picture.

**Comment by agriffard** [comment]
In #94 you were suggesting to manage Media by tenant in App_data\Sites\Default\Media.

Is it still an option to consider?

**Comment by sebastienros** [comment]
Can we talk about this when we start designing the media module? It's been only two weeks we talked about it and I can't remember the pros/cons. Too many things to focus on right now. Unless someone wants to work on the module and then we can start some design discussion and invite more people to join.

**Comment by agriffard** [comment]
See Media Services Design thread #561
