### ISSUE TITLE
Meta generator

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#371]
How do we include automatically this meta in the head of each theme:
<meta content="Orchard" name="generator" />

**Comment by sebastienros** [comment]
using a tag helper from the Orchard.ResourceManagement module. There is an example in Demo, in the Index.cshtml file.

**Comment by sebastienros** [comment]
Ah, this one, can be done using a middleware. There is already one middleware doing something similar in Demo as an example.

**Comment by agriffard** [comment]
If I add it with tag helper, it would be in a view, so removable:
`<meta content="Orchard" name="generator" />`

If I use a middleware:
In which module do we add this?
How can I acces the head from the middleware?

**Comment by sebastienros** [comment]
Can be part of the Orchard.Commons module.

**Comment by agriffard** [comment]
See https://github.com/OrchardCMS/Orchard2/pull/379

**Comment by agriffard** [comment]
Wouldn't it be easier to do like in O1?
Add by default the meta generator in the meta entries in the ResourceManager.

**Comment by sebastienros** [comment]
@agriffard you are probably right, but I would like to reuse this module externally ... so can't do it.
We can use a Filter instead of a middleware, this way it will just be done for Views. Look at the AdminMenuFilter, and check for StatusCode == 200.

**Comment by agriffard** [comment]
Do we use Orchard or OrchardCore for the meta generator?
