### ISSUE TITLE
404s still evaluate Layout

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#375]
The current homepage has links to unexisting script files, all these 404s are currently converted by the Diagnostics module into custom views with a 404 status.

Maybe that's the correct thing to do, and maybe there should be a custom Layout that would not render any content like the menus, or maybe it should be cache aggressively.

**Comment by jtkech** [comment]
Yes, when a script file exists it is served as a static file and orchard doesn't see the request. If it doesn't exist orchard computes it as a normal request and finally serves the `NotFound` view.

Note: I can see in the debugger that `ExpandViewLocations()` is called for each of them.

I first thought that somewhere we have to filter these requests (just return a 404), but we can have some controllers specifically used to implement some static files requests.

Because it's related somewhere to view rendering, i'll search on this.

**Comment by sebastienros** [comment]
FYI, the fact that a custom NotFound file is done is on purpose, I made a module for that, we just need to optimize it by serving the custom page only if it was handled by the MVC handler.

**Comment by jtkech** [comment]
Just for infos because i began to get something working with the following. I didn't find a way by checking if it has been handled or not by the MVC handler. When a static file doesn't exists, it seems that it is just not served by the StaticFiles midleware, then orchard middlewares execute ...

    ...
    using Microsoft.AspNetCore.Diagnostics;
    using Microsoft.AspNetCore.StaticFiles;
    ...

            // c.f. https://docs.asp.net/en/latest/fundamentals/error-handling.html#id3
            app.UseStatusCodePagesWithReExecute("/Error", "?status={0}");

            app.Use((context, next) =>
            {
                // this can be declared as a private variable at the class level
                var contentTypeProvider = new FileExtensionContentTypeProvider();

                string contentType;
                if (contentTypeProvider.TryGetContentType(context.Request.Path, out contentType))
                {
                    var statusCodePagesFeature = context.Features.Get<IStatusCodePagesFeature>();
                    if (statusCodePagesFeature != null)
                    {
                        statusCodePagesFeature.Enabled = false;
                    }
                }

                return next();
            });

**Comment by sebastienros** [comment]
We might also need to change the AdminMenuFilter not to render anything when the status code is not 2xx. Not sure we should care for now, but keep track of it.
