### ISSUE TITLE
ContentPreview: Not rendering if Title is empty

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#377]
Repro:
- Enable the ContentPreview module.
- Create a content type with a Title and a Body part.
- Create a new content item.
- Click on Preview button.
- Enter a text in Body and **let the Title empty**.

The Body will not be rendered because the Index method of the Preview controller will return an error 500 because if this test:
```
if (!ModelState.IsValid)
{
	return StatusCode(500);
}
```
The Title property of the TitlePart is Required so if I don't fill it, the ModelState is invalid.

Is it the expected behavior?

Users won't understand why the preview is not displayed until there is no more validation errors.

**Comment by sebastienros** [comment]
It's expected,it will fail for any server side validationerror. An
improvement would be to display a custom message with the errors instead.
