### ISSUE TITLE
Pages

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#385]
Pages will be the first content type needed.

Do we make an Orchard.Pages module with a Migration or do we provide a recipe to create the content type ?

Initial properties would be:
- Title
- Autoroute with 'Allow custom pattern' and {{slug}}
- Html Body with Wysiwyg editor
- Show on a menu (When available)

Options will be:
- Creatable
- Listable
- Draftable

**Comment by sebastienros** [comment]
For reference, here are Drupal's default content types: https://www.drupal.org/docs/7/understanding-drupal/content-types

**Comment by sebastienros** [comment]
`Page` makes more sense that `Story` or `Article` as it represent a generic routable content. Users should be able to create more semantically adapted types if they need to. We do it in the Blogs recipe with a `Blog Post`. 

TODO:
- Add Page type to the CMS recipe
- Change `Article` to `Page` in the Blogs recipe

Working on it
