### ISSUE TITLE
Provide a recipe step for OpenIdSettings in OAuth branch

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#387]
I have started with this feature providing an OpenIdSettingsStep and an OpenIdSettingsStepModel.  Problem I find in OpenIdSettingsStep is OpenIdSettings still are not initialized when I create a site using a recipe. So, this is null: ` _siteService.GetSiteSettingsAsync().As<OpenIdSettings>()`
How can I initialize OpenIdSettings within SiteSettings at this point?

**Comment by jersiovic** [comment]
Finally I solved this calling this two methods in OpenIdService.cs from the OpenIdSettingsStep. So, if you agree with this solution I can add a commit with this change to OAuth branch

```
        public async Task<OpenIdSettings> GetOpenIdSettingsAsync()
        {
            var siteSettings = await _siteService.GetSiteSettingsAsync();
            var result = siteSettings.As<OpenIdSettings>();

            if (result == null)
            {
                result = new OpenIdSettings();
            }
            return result;
        }
        public async Task UpdateOpenIdSettingsAsync(OpenIdSettings openIdSettings)
        {
            var siteSettings = await _session.QueryAsync<Orchard.Settings.SiteSettings>().FirstOrDefault();
            siteSettings.Properties[typeof(OpenIdSettings).Name] = JObject.FromObject(openIdSettings);
            _session.Save(siteSettings);
            _memoryCache.Set("Site", siteSettings);
        }
```

**Comment by jersiovic** [comment]
Added a PR https://github.com/OrchardCMS/Orchard2/pull/393

**Comment by sebastienros** [comment]
I had not seen this issue before commenting on the PR. See my comment.

Would you mind creating a `README.md` file in the module, like I did in the other ones, just to document the format of the Recipe step with an example?
