### ISSUE TITLE
Provide a command for creating new users

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#388]
Currently if you want to create a user through recipe only way is to use Content Execution Step but in that way you are not able to set password.
If you agree I'm going to add a command to create a new user through Command Execution Step

**Comment by sebastienros** [comment]
How does the Content Execution step allow you to create a User? I don't think a User is a content item.

Let me check how drupal allows the creation of passwords from command line. I'd say we should at least use a cryptographically generated password. Not one that would be defined in the recipe step, and the account should be awaiting for email verification. Which is something we don't have yet.

**Comment by sebastienros** [comment]
I can see that Drush has a command for that: https://drushcommands.com/drush-6x/user/user-create/
So it should be fine to have the password in the recipe file.

**Comment by jersiovic** [comment]
Ok (I though all records in table Content were Content Items)

**Comment by sebastienros** [comment]
No, but I intend to create a collection just for Content Items though. Also you can take a look at how I implemented `IndexingTaskManager` to use raw tables and Dapper instead of using YesSql.

**Comment by jersiovic** [comment]
I've taken a look at IndexingTaskManager. 
Won't be more desirable we use YesSql also there?

**Comment by jersiovic** [comment]
I also want to import roles. 
Do you agree I create a RecipeExecutionSetep called RolesStep ?

**Comment by sebastienros** [comment]
ok, do you want to create separate branches for that so we can review it? You can then also copy the commit on the oauth branch or just merge master when it's approved.

**Comment by jersiovic** [comment]
ok
