### ISSUE TITLE
How unload extension, module

### ISSUE THREAD

**Issue by GVX111** [OrchardCMS/Orchard2#39]
IExtensionManager has only 

<pre>
AvailableExtensions
AvailableFeatures
GetExtension
LoadFeatures
EnabledFeatures
</pre> 

How can i disable modules?

**Comment by Jetski5822** [comment]
I think we need an UnloadFeatures method...

Also, it needs to monitor Module.txt files so if it gets renamed, it unloads the assembly.

**Comment by gvx111** [comment]
Also LoadFeatures doesnt work.

**Comment by Jetski5822** [comment]
Really!? that seems weird. I will take a look later this evening.

**Comment by gvx111** [comment]
Did you look at this problem? @Jetski5822

**Comment by Jetski5822** [comment]
Not yet, just finishing up on the event bus work I was looking at, and fixing the latest beta 8 changes.

Should get time tomorrow, sorry for the delay

-----Original Message-----

**Comment by Jetski5822** [comment]
I have just been looking in to this, and decided to port the tests from Orchard over around this, and all go green?

Once the recipe story is done, then the MinimumShellDescriptor will be rewritten to be exactly what it says.

**Comment by gvx111** [comment]
yes it works but maybe dependency not working because I have  Routes : IRouteProvider and Routes are not registered also IDependency. Meybe it must added in ShellContext

**Comment by sebastienros** [comment]
Same as in Orchard1, when some feature change, or are enabled/disabled, the shell has to be reloaded on the next request, i.e. it's like a restart for the tenant. Nothing is implemented yet, neither is tenant management like disabling, restarting, or creating a new one. Will be part of the Orchard.MultiTenancy port.

**Comment by agriffard** [comment]
Orchard.Modules now provides an admi UI that allows you to enable or disable the modules.
