### ISSUE TITLE
ThemeAwareViewLocationExpander throws null exception (Master Broken)

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Orchard2#398]
@jtkech Hey man, after that merge, I kicked up O2, and ThemeAwareViewLocationExpander throws a null reference exception.

        public void PopulateValues(ViewLocationExpanderContext context)
        {
            var themeManager = context.ActionContext.HttpContext.RequestServices.GetService<IThemeManager>();
            context.Values["Theme"] = themeManager.GetThemeAsync().GetAwaiter().GetResult().Id;
        }

It looks like the IThemeManager doesnt get registered.

**Comment by Jetski5822** [comment]
@jtkech okay I have fixed Master, but I have had to comment out ThemeAwareViewLocationExpander implementation, could you have a look for me?

Also, the ExtensionManager where it get dependencies needs to remain, when a call is made in it was only getting 2 Features on startup, where as 3 need to be returned.

**Comment by jtkech** [comment]
@Jetski5822 ok, i'll take a look.

But it was working on my side which was rebased on master. Did you tried it before the last other merge?

**Comment by Jetski5822** [comment]
Yeah, I tried on your merge set and it was throwing null reference exceptions.

**Comment by Jetski5822** [comment]
Did you try from scratch? i.e. through Setup. Thats where it fails.

**Comment by jtkech** [comment]
Ah ok, will try.

Right now, just as i remember in `AddExtensionManager()` when i first fixed master i used

            services.TryAddScoped<IFeaturesProvider, FeaturesProvider>();

As it was used before for `FeatureManager`

**Comment by jtkech** [comment]
Oh, yes in a context of a setup it fails on

            context.Values["Theme"] = themeManager.GetThemeAsync().GetAwaiter().GetResult().Id;

So, i'll start on this issue.

**Comment by jtkech** [comment]
Indeed, when doing the setup `IThemeManager` is not registered.

Then in `ThemeAwareViewLocationExpander`, after commenting a few lines related to theme, it works.

I could run and pass the setup.

**Comment by Jetski5822** [comment]
Yup, I just put the other one back in until you could look at it as I was blocked. I modified the one I put in to be a bit for awesome that the old one - but not by much.

**Comment by jtkech** [comment]
So, by adding some null check on requested services (because of setup), i've re-run a setup and it seems to work well.

> Also, the ExtensionManager where it get dependencies needs to remain, when a call is made in it was only getting 2 Features on startup, where as 3 need to be returned.

Can you give more details on where and in which context. Then i can test it on my machine, so before the last 2 merges on master.

**Comment by jtkech** [comment]
Oh, got it in.

        public IEnumerable<IFeatureInfo> GetFeatures(string[] featureIdsToLoad)
        {
            var allDependencies = featureIdsToLoad.SelectMany(featureId => GetFeatureDependencies(featureId));
            var orderedFeatureDescriptors = GetFeatures().Where(f => allDependencies.Any(d => d.Id == f.Id));

            return orderedFeatureDescriptors;
        }

featureIdsToLoad = Orchard.Hosting and Orchard.Commons. And it returns only Orchard.Commons.

Will take a look.

Does GetFeatureDependencies(featureId) return the feature itself? Maybe here the culprit.

**Comment by jtkech** [comment]
@Jetski5822 yes, but by applying your fix in the 2 `GetFeatures` methods, i still get only the `Orchard.Commons` feature.

Maybe normal because `Orchard.Hosting` is not a module, it's a built in feature.

**Comment by jtkech** [comment]
@Jetski5822 sorry for the troubles.

So, i think we only need to add the right null checks in ThemeAwareViewLocationExpander.

So, if you agree, maybe you can revert your last fix, then i can do a simple PR to do this.

Need to leave right now, i can do it this night in 3 or 4 hours.

Best.

**Comment by sebastienros** [comment]
Where went the time we had PRs and the time to test the features so at
least it passes setup.

**Comment by Jetski5822** [comment]
When you request, lets say, Orchard.Recipes and Orchard.Setup, which is what happens during setup, what should be returned is Orchard.Recipes, Orchard.Setup and Orchard.Resources (I don't remember the order).

If we change it back, then only the two will be returned.

Now, on to the ThemeAwareViewLocationExpander, I think that we need more than Location Expander. One for Themes, and one for Modules, etc... Is there an order to Themes and then Modules?

**Comment by jtkech** [comment]
Just coming back.

@sebastienros so sorry.

@Jetski5822 

> If we change it back, then only the two will be returned.

Indeed, tested during a setup, i can see is that `Orchard.Recipes` has a dependency on `Orchard.Modules` which has a dependency on `Orchard.Resources`. Then indeed `Orchard.Resources` is missing.

But if i use your fix, i get the same missing feature. So, i've used this testing line.

            var test = GetFeatureDependencies("Orchard.Recipes");

And here, test doesn't contain `Orchard.Resources`.

**Comment by jtkech** [comment]
@Jetski5822 

> Now, on to the ThemeAwareViewLocationExpander, I think that we need more than Location Expander. One for Themes, and one for Modules, etc... Is there an order to Themes and then Modules?

Oh, i see what you mean, using modules without theming. Need to think about this but i think it will be easy to implement 2 expanders.

Yes, here views locations related to themes need to be at the top.

**Comment by jtkech** [comment]
@Jetski5822 

So, about the missing `Orchard.Resources` it is the same with your code.

It seems that in `GetFeatureDependencies()` you don't parse all the dependency graph. I could fix it by doing the following. See the commented line i've replaced to use the dependencies of the current dependency in place of always using those of the original feature.

    while (stack.Count > 0)
    {
        var next = stack.Pop();
        foreach (var dependency in next.Where(dependency => !dependencies.Contains(dependency)))
        {
            dependencies.Add(dependency);
            //stack.Push(unorderedFeatures.Where(subject => feature.Dependencies.Any(x => x == subject.Id)).ToArray());
            stack.Push(unorderedFeatures.Where(subject => dependency.Dependencies.Any(x => x == subject.Id)).ToArray());
        }
    }

**Comment by Jetski5822** [comment]
Yo yo okay cool, I have to catch a 8hr train so gunna write a bunch on unit tests around extension manager. At this point we are guessing so if I get some tests written then we can refactor to our hearts content.
