### ISSUE TITLE
Order reversed

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#406]
Navigation, sites settings, multiple things are reversed. Does anyone know why?

**Comment by sebastienros** [comment]
Maybe when items are added to shapes, then ordered. Possible that it is since shapes are displayed asyncronously, I will investigate.

**Comment by jtkech** [comment]
Fixed

**Comment by jtkech** [comment]
Related to other little things i pointed out in my last comments in #398
