### ISSUE TITLE
Patch requests not working

### ISSUE THREAD

**Issue by psp589** [OrchardCMS/Orchard2#412]
It seems like patch requests are not working, I try to make calls with a private client app and also postman, but the response I get is always a 400. 

Seen to output in Vs I saw this Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 PATCH "myUrl" application/json-patch+json 177
Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware:Debug: PATCH requests are not supported

the request starting and then "PATCH requests are not supported", could someone help?

**Comment by sebastienros** [comment]
Please provide a repro (a simple action and an example of request you are sending), it's weird that the request is handled by the static file provider.

**Comment by PinpointTownes** [comment]
FYI, this debug message indicates that the static files middleware doesn't handle the request as it uses an incompatible verb: in this case, it allows the rest of the pipeline to be invoked. The 400 response likely comes from somewhere else.

**Comment by jersiovic** [comment]
@psp589 maybe you can use branch oauth2_withSimpleModuleOfPCCOM in our xkproject repo as a base code for adding a little sample to the web api controller that shows them a sample of our problem.

**Comment by psp589** [comment]
Sorry it was my bad I was doing the request in the wrong way
