### ISSUE TITLE
Consider registering the OAuth2 validation middleware when using the opaque token format

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#416]
The OpenID module automatically registers the JWT middleware when choosing JWT as the access token format, but doesn't do the same thing for the default format.

https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Cms.Web/Modules/Orchard.OpenId/Startup.cs#L58

**Comment by jersiovic** [comment]
I need to initialize JWT middleware independently of the format it is chosen? Does it has to be in a different way if it is done for JWT of for default format?
Can you provide a sample?

**Comment by PinpointTownes** [comment]
I'll send a PR and ping you once it's ready :smile: 

The important thing to remember is that we have to configure the validation middleware to use the same data protection provider than the one we use to create the access tokens.

**Comment by jersiovic** [comment]
I merged my PR and one hour ago I rebased Oauth2 branch on main branch, so you can send that PR whenever you want.

**Comment by PinpointTownes** [comment]
Fixed by https://github.com/OrchardCMS/Orchard2/commit/aed6b02b9260daad95776c5a6dfd1411a6434a84.
