### ISSUE TITLE
Resources : scripts, styles

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#421]
Topic to decide what client side libraries (css, jss, fonts) are worth being added to the Orchard.Resources module.

Currently:
Bootstrap
jQuery

Create at least a ReadMe.md to explain how to add resources in the resourceManifest, use the taghelpers (resource, script, style).

**Comment by agriffard** [comment]
Reminder: update to the latest version :
FontAwesome
	`<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">`

Bootstrap v3.3.7	
```
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
```

Add Bootstrap 4.0.0-alpha.5 version ?

**Comment by sebastienros** [comment]
we are already on BS 4-alpha5 on the admin

**Comment by agriffard** [comment]
Yes, but using the assets, not the resourceManifest.
I also asked this question because I want to know how to handle different versions of the same library. Ex jQuery 1.x, 2.x, 3.x

**Comment by sebastienros** [comment]
the resource manager now supports multiple versions of the same library. We could potentially have all major ones available as resources, and each view define which one is required. If no version is specified the latest is used.
