### ISSUE TITLE
[Design] Tags

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#433]
How do we allow to enter tags associated to a content item?

@sebastienros suggested to create a content field to manage them.

We need to provide these features:
- Add a list of strings in a textbox.
- Javascript plugin to add them on tab or comma, display them as labels, and remove them thanks to a 'x'.
- Autocomplete (optional).
- Tag cloud widget ?
- Index them and allow to find the content items associated to a tag.
- When XmlRpc MetaWeblog is implemented, manage the field.

**Comment by sebastienros** [comment]
What I said is that while we don't have tags, we can use a text field for the blogs if necessary.

Tags will be implemented as part of the Taxonomy module.
