### ISSUE TITLE
Fields are not displayed anymore

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#440]
since https://github.com/OrchardCMS/Orchard2/commit/60cd75a5c3a03f2f012d88ccb33346dedd880c81
In BooleanFieldDriver and TextFieldDriver.
If you use 2 .Location(), it the first one doesn't seem to be used.
```
            .Location("Content")
            .Location("SummaryAdmin", "");
```

**Comment by sebastienros** [comment]
Fixed in PR
