### ISSUE TITLE
Content Fields: Alternates and placement

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#443]
Please, add Alternates for content fields and explain how placement.json work in a theme.

Ex: As a theme designer, I want to be able to make an alternate view of the field BlogPost.Subtitle and place it in header at position 2 in Detail and hide it in Summary. 

I think placement.json would look like this :
```
{
  "TextField": [
    {
      "display-type": "Detail",
      "differentiator": "Subtitle",
      "place": "Header:2"
    },
    {
      "display-type": "Summary",
      "differentiator": "Subtitle",
      "place": "-"
    }
  ]
}
```

**Comment by sebastienros** [comment]
Fixed in the fields PR.

The differentiator needs to be `[PartName].[FieldName]` like `Article.MyTextField`

**Comment by sebastienros** [comment]
Will add some documentation too

**Comment by agriffard** [comment]
I manage to place in the local zone Meta a TextField named Tags in a content type BlogPost by adding a placement.json in a theme :
```
{
  "TextField": [
    {
      "display-type": "Detail",
      "differentiator": "BlogPost.Tags",
      "place": "Meta:3"
    },
    {
      "display-type": "Summary",
      "differentiator": "BlogPost.Tags",
      "place": "Meta:3"
    }
  ]
}
```

But I can't make an alternate. Adding TextField-Tags.cshtml doesn't work.

**Comment by sebastienros** [comment]
trying right now

**Comment by sebastienros** [comment]
Works now, it was a typo in the json parsing. Example:

```
{
  "TextField": [
    {
      "display-type": "Detail",
      "differentiator": "Article.MyTextField",
      "place": "Content",
      "alternates": [ "TextField_Title" ]
    }
  ]
}
```

And `TextField.Title`:
```
@model Orchard.ContentFields.ViewModels.DisplayTextFieldViewModel
@using Orchard.ContentManagement.Metadata.Models

<h1>
    @Model.PartFieldDefinition.DisplayName(): @Model.Field.Text
</h1>
```

**Comment by sebastienros** [comment]
I am doing a change now so that you don't have to specify `place` and it won't affect the default. Otherwise it just hides it
