### ISSUE TITLE
Index Search not working

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#444]
/Lucene/Admin/Query?IndexName=Search

Index Search is not working anymore, since changes in Identity.
```
/Modules/Lucene/Views/Admin/Query.cshtml

Argument 1: cannot convert from 'int' to 'string'
 29       var contentItemId = Convert.ToInt32(document.GetField("ContentItemId").StringValue);
 30       var contentItem = await ContentManager.GetAsync(contentItemId, VersionOptions.Latest);
```

**Comment by agriffard** [comment]
Easy to fix by removing the Convert.ToInt32() but are there other changes to check, now ContentId is a string?

**Comment by sebastienros** [comment]
ContentItemId is a string now, right, there might be other parts of the code to change. I changed most of it, must have missed some.
