### ISSUE TITLE
Index Part Settings are not saved

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#445]
Index Part Settings are not saved anymore.

Repro:
In /Admin/Edit/BlogPost/BodyPart, I click on Include this element index.
I check the checkboxes Stored, Analyzed, Sanitized
I save.
I go back and the checkboxes are not selected.

**Comment by agriffard** [comment]
Settings are saved (even if there is a problem with Bootstrap on a toggle collapse with the checkbox 'Include this element index') but they are not correctly loaded :
in Lucene\Settings\ContentTypePartIndexSettingsDisplayDriver.cs, method EditAsync, line 32.

`model.ContentIndexSettings = contentTypePartDefinition.Settings.ToObject<ContentIndexSettings>();`
should be something like this  :
`model.ContentIndexSettings = contentTypePartDefinition.Settings.Property("ContentIndexSettings").Value.ToObject<ContentIndexSettings>();`
 because ContentIndexSettings is a sub-property.

I dont know if it is the best way to fix it. Please advise.

Btw, 'Include this element index' should be =>'Include this element **in the** index'

**Comment by sebastienros** [comment]
there is an overload on the settings, to pass a type, it will then prefix it automatically. I think I forgot the other way around. will do thanks

**Comment by agriffard** [comment]
I don't manage to index fields either.

Repro:
Create a 'Search' Lucene index.
Add a 'Tags' Textfield on a BlogPost.
Edit the settings to check 'Include in the index', 'Stored', 'Analyzed' and 'Sanitized'.
Create a BlogPost, enter 'Orchard' in Tags.
Query the 'Search' Lucene index, enter *:*

No results.

**Comment by sebastienros** [comment]
I must have broken it when I changed the content item id property ... will fix it.
