### ISSUE TITLE
Error indexing

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#457]
I found an error that occurs when the background task tries to index a content.

In Lucene\LuceneIndexProvider.cs, method CreateLuceneDocument
`case DocumentIndex.Types.DateTime:`
When the PublishedUtc property is added, there is an error because entry.Value.Value is null.

A simple fix would be to check if entry.Value.Value != null.

**Comment by agriffard** [comment]
As it is in a background task, I had to be in debug to watch the Exception appear and as I am running on IISExpress, there is no console open.
We should enable Debug console logging and File logging in app_data\sites\{tenant}\logs for this kind of problem. See #458

**Comment by agriffard** [comment]
Reminder : Indexing still need to be fixed.

**Comment by sebastienros** [comment]
Fixed in https://github.com/OrchardCMS/Orchard2/commit/90df48f851f44766f868ea9e05ed29598953a2c7
