### ISSUE TITLE
Prevent AccessController from being accessed when the configuration is invalid

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#464]
In the current bits, the OpenID module won't register OpenIddict nor the JWT/validation middleware if something is wrong with the OpenID settings (which is a very smart thingy). Unfortunately, this is not enough to prevent `AccessController` from being accessible, as the MVC routing middleware is registered at a higher level by Orchard.

When trying to access this controller, an exception is thrown at runtime by `OpenIddictModelBinder` as it's unable to find the OIDC request in the environment (because OpenIddict was not invoked).

We should consider updating that to offer a better experience.

**Comment by PinpointTownes** [comment]
I see two possible approaches:

  - Update `StartupBase.Configure` to insert a middleware handling all the OIDC requests and returning an error when the configuration is invalid, which will prevent the `AccessController` from being reached.

  - Stop using `OpenIddictModelBinder` so it doesn't throw an exception when the request cannot be found and update the `AccessController` to make an `IsValidOpenIdSettings` check before handling the request.

I personally like the second option.

**Comment by sebastienros** [comment]
Can;t the tenant be prevented from loading when the configuration is invalid?
How can you provide an invalid configuration in the first place? If that's not an easy task, then failing the tenant to load (with and exception in the Startup) would fine.

**Comment by PinpointTownes** [comment]
> How can you provide an invalid configuration in the first place?

It's by default in an invalid state, as it must be configured to work (AFAICT, there's no dedicated screen during startup that forces you to register the OpenID settings, it must be done via the admin panel)

**Comment by sebastienros** [comment]
Ok, then simply ignore the middlewares in this case, and don't care about controller issues, it's a temporary state (first configuration phase).

**Comment by PinpointTownes** [comment]
> then simply ignore the middlewares in this case

That's already what it does.

> and don't care about controller issues

That too. But IMHO, it's not really ideal, specially since it's easy to fix. Meh heh, your project, your rules :running_man:

**Comment by sebastienros** [comment]
If there is an easy, GTG, I just want to prevent useless complexity.

**Comment by sebastienros** [comment]
> Meh heh, your project, your rules

Not my project ;) Our project, our rules

**Comment by PinpointTownes** [comment]
> If there is an easy, GTG

PR submitted: https://github.com/OrchardCMS/Orchard2/issues/465 :sweat_smile:

**Comment by PinpointTownes** [comment]
Fixed by https://github.com/OrchardCMS/Orchard2/commit/a8a6c5fe00257dccae8a74a706117459342fd720.

FYI, here's what you now get when the configuration is invalid:

Token response:

```csharp
{
  "error": "server_error",
  "error_description": "The authorization server is not correctly configured."
}
```

Authorization/logout response:

![image](https://cloud.githubusercontent.com/assets/6998306/21444784/bafb0a96-c8b1-11e6-83c6-840d860dc704.png)
