### ISSUE TITLE
Manage Themes

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#469]
The Themes admin pages has to list all the available themes, allow to Enable/Disable theme and select the Front and the Admin One.

We will use cards to display these informations:
- The title of the theme (in Theme.txt)
- The description
- The author
- The version
- The website
- The thumbnail (Look for Theme.png or use default one if not found)

**Comment by jtkech** [comment]
Just for infos with what @Jetski5822 has done where a base theme now is somewhere implemented as a regular dependency, enabling / disabling themes will be as simple as for modules.

Because i needed it in one of my tests, i already tried it through the Modules Service just by displaying all features, not only modules.

Best.

**Comment by agriffard** [comment]
FYI, I started to change the themes admin screen to display all the available themes.
I will try to push a first commit soon, even if it is still in early stage.

**Comment by agriffard** [comment]
I created a pull request #507 but there are many things to improve:
- UI : I tried to use cards.
- Disable/Enable actions
- Theme informations : Author, Version, Web site, thumbnail.

**Comment by sfmskywalker** [comment]
I updated your PR with:

* Improved Cards UI
* Enable/Disable actions (with HTTP POST)
* Theme info: Author, Version, Website, Thumbnail

Current state:

![image](https://cloud.githubusercontent.com/assets/938393/23245768/6092f528-f98f-11e6-966a-c5dc5310fe4a.png)

If you like it, we can remove the 'dontmerge' label and get it merged in.

**Comment by agriffard** [comment]
There are still some improvements to make to the UI but there will be some incremental changes:

- Separate Front and Admin themes.
- Search, filters, tags.
- Retrieve manifest infos.

And in the future:

- Download from nuget gallery. 
- Install themes from computer.
- Upgrade latest version of theme.
