### ISSUE TITLE
Prev/Next pager on Details page of a list item

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#471]
Is it possible to display a Prev/Next pager on the Details page of an item that has a ListPart?

I guess, we have to add the pager shape to the detail but I don't know where exactly, in which Driver?

**Comment by sebastienros** [comment]
`@await DisplayAsync(Model.Pager)` from the `ListPart` shape.

**Comment by agriffard** [comment]
Your answer works for the ListPart to display the List and its items, but for a contained item on the Details page, we don't have the pager and no view displayed.

**Comment by sebastienros** [comment]
`Model.Content.Named("ListPart").Pager` should work then.

If that works then it could use some documentation. That's a nice way to reuse content shapes together with the new `Remove(shapeType)`

**Comment by sebastienros** [comment]
Maybe I could also add an extension to the `Content` zone shape so that named properties would resolve a shape type, so we could do: `Model.Content.ListPart.Pager`

**Comment by sebastienros** [comment]
I think I misunderstood your question. You want a way to navigate from one item to the next one, like documentation pages. This should be a custom part, or a setting on the List. It might also be affected by the order of the list (which is something we still need to do).

**Comment by agriffard** [comment]
Another question: Is it possible to have the choice to display the title of the previous and next page in the links?

What do I have to change in the pager.cshtml view?

**Comment by agriffard** [comment]
Answer for Next/Prev pager : This should be a custom part, or a setting on the List.

Answer to change the title of links : Alternates can be used.
