### ISSUE TITLE
Sharing knowledge or experience

### ISSUE THREAD

**Issue by DaveConsulting** [OrchardCMS/Orchard2#48]
I apologize that I'm writing an off-topic message here. But I don't know how else I could get in touch with other developers who are experimenting with Brochard.
Although I'm not an expert on Orchard, but I'm familiar with it and have built an order management module and some other small modules with it for a customer of mine.

I would love to get in touch with others how are interested in Brochard too and want to share knowledge and give the core developers (Nick at this moment) feedback. Hopefully we would be able to give hem a helping hand in the future.

If you want to get in touch with other developers, please do not hesitate to write a message here or make your contact info public or leave your e-mail address to make it possible for the rest of us to contact you without polluting the 'issues' section of github.

If anyone has a better idea, please do not hesitate to share it here. It would be nice to find a better way to communicate with each other.

Dave

**Comment by Jetski5822** [comment]
I love feedback :+1:

**Comment by ASADeveloper** [comment]
Hi Dave,
I just made my e-mail address public. So feel free to contact me anytime you want.

**Comment by Totemika** [comment]
What about a gitter for the brochard repo? why not? I'm not helpful atm but I like reading all the conversations and sometimes catch important information.

**Comment by Jetski5822** [comment]
You asked for it: https://gitter.im/OrchardCMS/Brochard

**Comment by sebastienros** [comment]
Gitter has been created and is active.
