### ISSUE TITLE
NullReferenceException in Orchard.OpenId's Create view when the model state is invalid

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#486]
![image](https://cloud.githubusercontent.com/assets/6998306/21555815/dc6667ec-ce1b-11e6-8b83-89cf79a5a113.png)

The root cause was quite easy to find: when the model state is invalid, `AdminController.Create` redisplays the form but doesn't add `OpenIdSettings` in the `ViewData` bag, which causes the NRE in the `Create` view.

**Comment by jersiovic** [comment]
Fixed at https://github.com/OrchardCMS/Orchard2/commit/8033a01ec51c434a317a2b2f20bbf98de4da0063
