### ISSUE TITLE
Autoroute: Path generation

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#488]
The generation of the path from a token doesn't work with the latest version.
I can't identify since when.

The path is correctly created from the pattern in Orchard.Autoroute\Handlers\AutoroutePartHandler.cs line 87 in the Updated method :
`part.Path = _tokenizer.Tokenize(pattern, ctx);`
But it is not stored with this value in the database.

**Comment by sebastienros** [comment]
Probably since I am not calling Apply on every event handler call. I will fix it.
