### ISSUE TITLE
Owner property

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#491]
Related to https://github.com/OrchardCMS/Orchard2/issues/384

In O1 there is an `Owner` property on a content item. It doesn't vary by version. It is used on the admin screens to represent the author, and in the security layer to asses ownership.
I changed it to call it `ModifiedBy` in O2 so we can use the latest user who modified a content instead, and it's attached to each version.
In the end I think we need both values, `OwnedBy` and `ModifiedBy` (or `Owner` and `Modifier`). Which would be set on each version. The owner doesn't change automatically, the modifier does. There is a UI to change the owner (optionally, like in O1) but not for the modifier.

**Comment by bleroy** [comment]
Yes, being the owner actually gives you rights. Last modifier is only informative, and useful for auditing, but doesn't give rights. Those are two distinct properties.

**Comment by sebastienros** [comment]
I could only find `author` in DecentCMS, which I assume could be used as the modifier.

**Comment by bleroy** [comment]
Yes, author in Decent is informative only. There's no notion of permissions yet in there, so owner has not been necessary yet, and I haven't introduced it.

**Comment by agriffard** [comment]
Author and Owner Implemented in #496
