### ISSUE TITLE
Unable to build on OSX

### ISSUE THREAD

**Issue by christianscheuer** [OrchardCMS/Orchard2#493]
I get the following output when producing the nuget package for Orchard.Feeds when building on OSX.
Is there a workaround/fix for this?

```
Producing nuget package "Orchard.Feeds.2.0.0-t003c6393e" for Orchard.Feeds
Orchard.Feeds -> /Users/Chr/Projects/orchard2/src/Orchard.Cms.Web/Modules/Orchard.Feeds/bin/Debug/Orchard.Feeds.2.0.0-t003c6393e.nupkg
Producing nuget package "Orchard.Feeds.2.0.0-t003c6393e.symbols" for Orchard.Feeds
Orchard.Feeds -> /Users/Chr/Projects/orchard2/src/Orchard.Cms.Web/Modules/Orchard.Feeds/bin/Debug/Orchard.Feeds.2.0.0-t003c6393e.symbols.nupkg
```
[...]
```
info: Exec
info:   program: dotnet
info:   commandline: pack  /Users/Chr/Projects/orchard2/src/Orchard.Cms.Web/Modules/Orchard.Identity --configuration Debug
info:   workingdir: /Users/Chr/Projects/orchard2

Unable to find a project.json in /Users/Chr/Projects/orchard2/src/Orchard.Cms.Web/Modules/Orchard.Identity/project.json
```

**Comment by jtkech** [comment]
Would need to try it (i don't use the build command) but just after a quick look i can see

    Orchard.Cms.Web/Modules/Orchard.Identity/project.json

We don't have anymore this module on the master branch, so maybe you just need to clean your repo

    git clean -xdf

Best.

**Comment by sebastienros** [comment]
I am closing as @jtkech 's suggestion should fix it. Plesae reopen if you still have the issue.

**Comment by christianscheuer** [comment]
@jtkech thank you for your quick response. That was indeed the issue 👍
