### ISSUE TITLE
Suggestion for adding the IUpdateModel to the UpdateContentContext.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard2#503]
Not an issue just a suggestion that may be useful. As i remember here the idea.

In `ContentItemDisplayManager.UpdateEditorAsync()`, when calling the `UpdateEditorAsync()` we pass an `UpdateEditorContext` which references the `IUpdateModel`. So each handler can check if the model is still valid but at this point not all handlers have been called.

    _contentHandlers.Invoke(handler => handler.Updating(updateContentContext), Logger);
    await _handlers.InvokeAsync(handler => handler.UpdateEditorAsync(contentItem, context), Logger);
    _contentHandlers.Reverse().Invoke(handler => handler.Updated(updateContentContext), Logger);

Maybe good that `UpdateContentContext` also references the `IUpdateModel`. Then each handler could check in its `Updated()` event if the model is still valid and then do specific operations. And we know that at this point all `UpdateEditorAsync()` have been called.

    if (context.Updater.ModelState.IsValid)

I don't remember the details but i think about the `AudiTrail` module in O1 and also the `Comments` module where, by using this check in place of other workarounds, we could prevent some specific db operations.

Best.

**Comment by sebastienros** [comment]
Ok, doesn't hurt to add it.
