### ISSUE TITLE
Raise event for custom class

### ISSUE THREAD

**Issue by GVX111** [OrchardCMS/Orchard2#51]
1) adding in IEventBus
<pre> public interface IEventBus : IDependency {
        IEnumerable Notify(string messageName, IDictionary< string, object > eventData);
        IEnumerable Notify(string type, string messageName, IDictionary< string, object> eventData);
    }</pre>
2) Add in IEventNotifier 
 <pre>public interface IEventNotifier {
        object Notify< TEventHandler >(Expression< Action < TEventHandler >> eventNotifier) where TEventHandler : IEventHandler;
        object Notify< TEventHandler >(string type, Expression< Action < TEventHandler> > eventNotifier) where TEventHandler : IEventHandler;

    }</pre>
3) Add in DefaultOrchardEventNotifier
<pre>  public object Notify< TEventHandler >(string type, Expression< Action< TEventHandle r> > eventNotifier) where TEventHandler : IEventHandler
        {
            var expression = GetExpression(eventNotifier);

            var interfaceName = expression.Method.DeclaringType.Name;
            var methodName = expression.Method.Name;

            var data = expression.Method.GetParameters()
                .Select((parameter, index) => new { parameter.Name, Value = GetValue(parameter, expression.Arguments[index]) })
                .ToDictionary(kv => kv.Name, kv => kv.Value);

            var results = _eventBus.Notify(type, interfaceName + "." + methodName, data);

            return Adjust(results, expression.Method.ReturnType);
        }</pre>

4) Change in DefaultOrchardEventBus
<pre> 
private IEnumerable< object > NotifyHandlers(string messageName, IDictionary< string, object > eventData) 
to
 private IEnumerable< object> NotifyHandlers(string messageName, IDictionary< string, object > eventData, string type ="")
</pre>

5) change in DefaultOrchardEventBus in method NotifyHandlers
<pre>
var eventHandlers = _eventHandlers[interfaceName];
to 
  var eventHandlers = (!string.IsNullOrEmpty(type) ? _eventHandlers[interfaceName].Where(e => e.GetType().Name == type) : _eventHandlers[interfaceName]);
</pre>

Testing
_eventNotifier.Notify< IPlugin >(pluginType, e => e.Submit(_shell.SiteId, ActionContext, new PluginSettings()))

**Comment by sebastienros** [comment]
Done
