### ISSUE TITLE
creare usercenterfilter

### ISSUE THREAD

**Issue by zhhbo** [OrchardCMS/Orchard2#512]
creare usercenterfilter
usercenterselecter..
support usercenter theme

**Comment by Jetski5822** [comment]
Sorry I dont understand, could you give more context?

**Comment by zhhbo** [comment]
i mean that we can create a filter like AdminFilter to provider a theme or menu for user pool

**Comment by zhhbo** [comment]
I mean to create a user center to provide users with a user interface and the template is different from the admin ui, but similar to the admin ui, but also a UserCenterFilter, UserCenterMenuFilter, UserCenterThemeSelector

**Comment by zhhbo** [comment]
https://github.com/OrchardCMS/Orchard2/pull/660
 I do it but there are some bugs in AdminMenu and route,I hav'nt found the method to solve them

**Comment by sebastienros** [comment]
I don't think it fits in our scope. I would suggest to keep this module separate from the main repository.

But I'd gladly accept a PR to fix the Lucene bug if you want to.
