### ISSUE TITLE
How to do make it work on vs 2017rc

### ISSUE THREAD

**Issue by zhhbo** [OrchardCMS/Orchard2#517]
When i do it, I found the Orchard.Cms.Web.xproj Con't load
the error :
E:\Orchard2\Orchard2-master\src\Orchard.Cms.Web>dotnet run
E:\Orchard2\Orchard2-master\src\Orchard.Cms.Web\Orchard.Cms.Web.xproj(7,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

The build failed. Please fix the build errors and run again.

**Comment by Jetski5822** [comment]
We need to migrate the project files to csproj, we havent done that yet as a few of us are waiting for a more stable VS2017 build

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/Orchard2/pull/552
