### ISSUE TITLE
Bootstrap radio/checkbox fix doesn't fix all the scenarios

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#518]
I thought this commit "Patching Boostrap collapse behavior on radio/checkbox (#499)" will solve problems with OpenIdSetting in Oauth2 branch. However it doesn't solves the Bootstrap bug I faced.
The problem I face happens when you want to collapse sth when a check is checked. 
I have reviewed how is used this patch in ContentIndexSettings.Edit.cshtml, but the point is there when a check is checked it shows sth (the opposite I need in OpenIdSettings).

**Comment by sebastienros** [comment]
Can you point me to the property that will behave like this? I have thought about this and it sound weird to show more checkboxes when you unselect one. I want to understand what you are trying to do.

**Comment by jersiovic** [comment]
Yes, it is needed in the open id settings https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Cms.Web/Modules/Orchard.OpenId/Views/OpenIdSettings.Edit.cshtml for the checkbox TestingModeEnabled. When it is checked we hide certificate select lists cause they are not needed.
