### ISSUE TITLE
Question about Content type part ordering

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard2#527]
When you add a part(s), maybe better to always add it (them) at the very top, before the other parts which are already persisted, even before a part which currently has a position of 0 or not already defined.

 Can be easily fixed e.g by using a negative position.

**UPDATE**: Same remark when adding a field to a part.

**Comment by agriffard** [comment]
I would like to be able to 'Edit placement' in a separate page in which I can drag and drop fields and parts together, not just fields in the owned part and then parts.

**Comment by jtkech** [comment]
Just realized i was wrong, maybe too tired. Indeed we need to display and be able to order the owner part, this to place the owned part and its embeded fields relative to other parts.

Will re-try it this night and reformulate my first comment.

Then, good idea to be able to order fields and parts together, but maybe not so simple to do.

**Comment by jtkech** [comment]
Currently, to do this you would need to create a named part for each individual field.

**Comment by jtkech** [comment]
Need to be re-tried and re-formulated.
Will open another issue if i find something.
