### ISSUE TITLE
Jint throws an exception interpreting Date().toLocaleDateString()

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#536]
Using this var in a recipe:
`"today": "[js:Date().toLocaleDateString()]"`

I get following exception:
![image](https://cloud.githubusercontent.com/assets/4950766/22087462/53fbd374-ddde-11e6-8f2e-662916520391.png)

However, looking at the tests of Jint apparently it should be supported: https://github.com/sebastienros/jint/blob/master/Jint.Tests/Runtime/EngineTests.cs#L1712

**Comment by sebastienros** [comment]
Try to learn javascript first ;)

**Comment by sebastienros** [comment]
http://www.ecma-international.org/ecma-262/5.1/#sec-15.9.2

```
When Date is called as a function rather than as a constructor, it returns a String representing the current time (UTC).

NOTE The function call Date(…) is not equivalent to the object creation expression new Date(…) with the same arguments.
```

**Comment by sebastienros** [comment]
Note for later, whenever you think Jint doesn't support something, you are probably wrong. 😄

**Comment by jersiovic** [comment]
To learn javscript ???
Are you crazy? Javascript is for losers 😄
