### ISSUE TITLE
Update Gulp dependencies

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Orchard2#550]
Ive notices quite a few are outta date, we should bring them all up to date.

**Comment by DanielStolt** [comment]
I've done a complete refresh of the Gulp pipeline and all its dependencies in `dev` a few days back - I'm guessing you should be able to bring that over to OC pretty much copy-paste.

**Comment by Jetski5822** [comment]
@danielstolt saweeeeet :)

**Comment by agriffard** [comment]
See #913 : package.json upgraded in Bootstrap4beta branch
