### ISSUE TITLE
Duplicated url with AutoroutePart

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#555]
Repro: 
- Create a content type with AutoroutePart.
- Add two content items with the same url.

The second url should have a suffix or the editor should prevent this duplication.

**Comment by jersiovic** [comment]
In Orchard 1 if programmatically you store a content item (new or modified) with same url as other one that exists it arise problems cause both have same alias. So, then you need to add code to prevent it. 
It would be interesting in Orchard 2 this is checked by the framework every time you store a content item with autoroute part no matter the scenario (editing it through admin UI, through recipe or programmatically) . So, the suffix would be added in the case it is detected a duplicate no matter the scenario. I mean you don't need to worry about that also when you add/edit a content item programmatically.

**Comment by agriffard** [comment]
@lukaskabrt your fix added a new 'Published' column to the AutoroutePartIndex table so there was an error if as me, your instance has been created before this change.

It is ok because we are in Beta but next time, for that kind of change, please add an UpdateFrom1 function in Migrations.cs

**Comment by sebastienros** [comment]
I told him to do. He had made a migration, but it was useless as the old values would not be populated.
I know I have to provide a way to mark as index as stale so that it gets rebuilt. I will provide it soon, probably when I work on projections which will need something similar.
