### ISSUE TITLE
Migration Report: Error

### ISSUE THREAD

**Issue by marquish** [OrchardCMS/Orchard2#559]
Failed to migrate XProj project Orchard.Cms.Web. 'dotnet migrate --skip-backup -s -p 
on master.

Log (zip) file here.

[UpgradeLog.zip](https://github.com/OrchardCMS/Orchard2/files/736665/UpgradeLog.zip)

**Comment by sebastienros** [comment]
Do you mean to do this: https://github.com/OrchardCMS/Orchard2/pull/552

**Comment by marquish** [comment]
I Just opened the solution
and found The following error in VS 17
[vs17_errors_opening_orchard2_sln.txt](https://github.com/OrchardCMS/Orchard2/files/736678/vs17_errors_opening_orchard2_sln.txt)

**Comment by marquish** [comment]
Used NuGet Package manager to fix issue with Reflection. 
Manual intervention, solved the issue on downgrading.

**Comment by sebastienros** [comment]
Can you create a PR targeting the __csproj__ branch?
