### ISSUE TITLE
jQuery UI and sortable

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#567]
It seems jQuery UI is only required to use sortable script.

May be it would be worth investigating on an alternative?
Ex: https://johnny.github.io/jquery-sortable/

**Comment by sebastienros** [comment]
We are already using a plugin to do that for Menus, https://github.com/ilikenwf/nestedSortable, not sure which one is better. The one we are already using does the job. Open to pros and cons, jquery-sortable might support more features, but it's also older, and doesn't seem to support touch (there is a PR for that).

Other than that, don't try to fix what's not broken. We can always remove this dependency once the product is mature enough to show that this is the only component that we depend on.

**Comment by Jetski5822** [comment]
Be good if we can use just one, might be an easy win tag thing?

**Comment by sebastienros** [comment]
Just to be clear, we do nothing right now. There is no easy win here ;) The easy win is to change nothing as it already works.
