### ISSUE TITLE
Edit Blog Post Field generates error

### ISSUE THREAD

**Issue by stevetayloruk** [OrchardCMS/Orchard2#575]
Using the blog theme recipe, go into the admin > content types > blog post and then click on edit button of the `SubTitle` Text Field.

Error page appears:

`There is no argument given that corresponds to the required formal parameter 'shapeFactory' of 'IShapeFactory.Create(string, Func<dynamic>)'`

In fact, looks like it happens on all fields of all types.

Thanks

**Comment by jtkech** [comment]
Just tried and i could repro.

For infos it works for this field if i add in `TextFieldSettings.Edit.cshtml`.

    @using Orchard.DisplayManagement

Best.

**Comment by sebastienros** [comment]
Right, this has been moved to an extension method, so we need to `using`, I will add it in the ViewImports instead.
