### ISSUE TITLE
one config (setting) for multiple tenants

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard2#597]
for example, The super Admin only need process one time for login, workflow, send email which can be used by multiple tenants.
I think @Piedone had a module about that in orchard1

**Comment by Piedone** [comment]
Not exactly. Worked with sharing data across tenants and cross-tenant features (see e.g.: https://orcharddojo.net/blog/advanced-orchard-accessing-other-tenants-services) but not making complex features like the ones you mentioned cross-tenant.

**Comment by Jetski5822** [comment]
Need to have a think about this. At the moment I am focused on true tenant isolation, however we do have services within the ApplicationServices stuff that go across tenants. Need to think of the security implications too.

**Comment by Jetski5822** [comment]
Done https://github.com/OrchardCMS/Orchard2/commit/a02cbe29c69c18588ecb1a5fe4ce474f71506ee9
