### ISSUE TITLE
Authorization policies are not enforced in MVC controllers

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#600]
While testing the OpenID module, I discovered a (big) bug in the latest Orchard bits: the `[Authorize]` attributes have absolutely no effect. The reason is actually quite simple: the MVC modules stack doesn't call `builder.AddAuthorization()` here, so the authorization filter is never executed: https://github.com/OrchardCMS/Orchard2/blob/master/src/OrchardCore/Microsoft.AspNetCore.Mvc.Modules/Extensions/ModularServiceCollectionExtensions.cs#L43.

/cc @Jetski5822 @sebastienros

**Comment by sebastienros** [comment]
I think we've had the same issue by the past, or maybe the opposite, that it was called twice.

Thanks for reporting.
