### ISSUE TITLE
Fix the Orchard.Users module to ensure authentication cookies are correctly isolated and can't be shared across tenants

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#606]
This issue was fixed a while ago in the `oauth2` branch, but it has never been merged into `master`:
https://github.com/OrchardCMS/Orchard2/pull/215#r85806573
https://github.com/OrchardCMS/Orchard2/pull/605#discussion_r105554163

**Comment by zhhbo** [comment]
Is there can give a setting button that will allow user shared across tenants?

**Comment by jersiovic** [comment]
It looks a good idea to me to make it configurable. What do you think @sebastienros ? 
Maybe @zhhbo or other interested in can add a new feature to Orchard.Users called "Orchard.Users.CookieConfiguration" which by default will be disabled. That feature will allow to set for a tenant the cookie name and the purpose string used for creating the DataProtectorProvider. 
By default those two would be based on tenant name as they are now in oauth branch..

**Comment by sebastienros** [comment]
@jersiovic  No, even if user auth cookies are shared the user objects are not. The solution is to use an external SSO service, even an Orchard tenant.

**Comment by PinpointTownes** [comment]
Closing, as this issue was fixed as part of https://github.com/OrchardCMS/Orchard2/commit/03468ae6e5d89a61075a28104e24d168213030ae.

Feel free to open a new ticket if you think it's worth investigating the "separate tenant approach" suggested by @sebastienros.
