### ISSUE TITLE
use front-end

### ISSUE THREAD

**Issue by xewn** [OrchardCMS/Orchard2#610]
会不会，考虑 使用 前后端分离。
比如wordpress的wp-calypso。

**Comment by Jetski5822** [comment]
what do you mean?

**Comment by anwaramoon** [comment]
@Jetski5822 
会不会，考虑 使用 前后端分离。 比如wordpress的wp-calypso

ENGLISH
Will not, consider using front and back separation. Such as wordpress wp-calypso

**Comment by infofromca** [comment]
Will you guys consider using the separation of  front and back end, Such as wordpress wp-calypso?

**Comment by xewn** [comment]
Thanks @anwaramoon  @infofromca
