### ISSUE TITLE
Generate Nuget packages on a feed

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#617]
@alexbocharov 

We need the nuget packages to be generated, at least for the ones in /OrchardCore.
Can you configure appveyor to build and host them?

**Comment by alexbocharov** [comment]
@sebastienros 
Appveyor or MyGet?

**Comment by sebastienros** [comment]
No preferences whatsoever, maybe myget makes more sense.

**Comment by Jetski5822** [comment]
@alexbocharov how are you getting on?

**Comment by alexbocharov** [comment]
@sebastienros @Jetski5822 
We no longer plan to use KoreBuild?

**Comment by Jetski5822** [comment]
@alexbocharov yeah we should use 

```
build_script:
  - ps: .\build.ps1
```

do you want me to make the changes?

**Comment by alexbocharov** [comment]
I can configure the KoreBuild for correct build packages.
But it is not the same as the https://github.com/OrchardCMS/Orchard2/pull/598

**Comment by alexbocharov** [comment]
@Jetski5822 I will configure via KoreBuild

**Comment by Jetski5822** [comment]
@alexbocharov sweet dude, I can help if you need. Check out the MVC ones: https://github.com/aspnet/mvc

**Comment by Jetski5822** [comment]
@alexbocharov I also have a myget feed, could we publish to that if I give you the creds?

**Comment by alexbocharov** [comment]
@Jetski5822 Yes

**Comment by alexbocharov** [comment]
Ok, I do it

**Comment by sebastienros** [comment]
Done, it targets myget right now
