### ISSUE TITLE
Authorization Code Flow doesn't work

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/Orchard2#622]
I'm not using this flow for my customers, but simply for checking everything is all right I've tested Authorization Code Flow using Postman. The point is it doesn't work, in fact I put a breakpoint in Authorize action within AccessController but it never stops there.

The log doesn't say anything interesting:
```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 GET http://localhost:2918/Orchard.OpenId/Access/Authorize%20?client_id=distribb2b&scope=openid%20%20profile%20roles&state=6921040&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback&response_type=code  
Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware:Information: Begin Routing Request
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executing action method Orchard.Diagnostics.Controllers.DiagnosticsController.Error (Orchard.Diagnostics) with arguments (404) - ModelState is Valid
Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor:Information: Executing ViewResult, running view at path \Modules\Orchard.Diagnostics\Views\Diagnostics\NotFound.cshtml.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action Orchard.Diagnostics.Controllers.DiagnosticsController.Error (Orchard.Diagnostics) in 21.3325ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 33.817ms 404 text/html; charset=utf-8
```
@PinpointTownes do you experencie similar problem?

**Comment by PinpointTownes** [comment]
> HTTP/1.1 GET http://localhost:2918/Orchard.OpenId/Access/Authorize%20?client_id=distribb2b&scope=openid%20%20profile%20roles&state=6921040&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback&response_type=code

There's a space (encoded to `%20`) between the request path and the query string.

**Comment by jersiovic** [comment]
ups thank you.
After fix it and accept consent I get this:
![image](https://cloud.githubusercontent.com/assets/4950766/24057602/33eeb776-0b48-11e7-976e-186d4491e82b.png)

```
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request starting HTTP/1.1 POST http://localhost:2918/Orchard.OpenId/Access/Authorize?request_id=722815c9-f754-465a-853e-6ee9a7d98055 application/x-www-form-urlencoded 248
Microsoft.AspNetCore.Modules.ModularTenantRouterMiddleware:Information: Begin Routing Request
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware:Information: The authorization request was successfully extracted from the HTTP request: {
  "__RequestVerificationToken": "CfDJ8G0BKaFikCdHonG_Xi7qhti3BH3ZpxOSdmHarkjFFbUe57ytrmLSeSsc1UioicX2fIP320o81ybsPBx1-Cs0GjQlKyWR-SLsGag43Q-69EKylG4SJbqFk05kVj3ZquV_zo8aHpUjSH8cYU2CAG9PJdk",
  "request_id": "722815c9-f754-465a-853e-6ee9a7d98055",
  "submit.Accept": "Yes",
  "client_id": "distribb2b",
  "scope": "openid  profile roles",
  "state": "6921269",
  "redirect_uri": "https://www.getpostman.com/oauth2/callback",
  "response_type": "code"
}
AspNet.Security.OpenIdConnect.Server.OpenIdConnectServerMiddleware:Information: The authorization request was successfully validated.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executing action method Orchard.OpenId.Controllers.AccessController.Accept (Orchard.OpenId) with arguments ((null)) - ModelState is Valid
Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor:Information: Executing ViewResult, running view at path \Modules\Orchard.OpenId\Views\Access\Error.cshtml.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action Orchard.OpenId.Controllers.AccessController.Accept (Orchard.OpenId) in 5900.4006ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 5915.0438ms 200 text/html; charset=utf-8
```

**Comment by PinpointTownes** [comment]
This error is returned from this path: https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Cms.Web/Modules/Orchard.OpenId/Controllers/AccessController.cs#L468-L476

Are you sure your user profile is still in the database?

(we should consider improving the error message, BTW)

**Comment by jersiovic** [comment]
It is the admin user the one I used to login, and it still exist.
I've debugged at those lines but there is not any problem there.
Do you have same problem?

**Comment by PinpointTownes** [comment]
> Do you have same problem?

I experienced a similar issue when working on the module last week: I came to the conclusion it was likely a Postman bug, because the Orchard authentication cookie was not correctly sent. 

That said, you shouldn't hit this code path because you're supposed to be redirected to the login page (there was a bug with the authorization attribute, but I fixed it). Due to the Postman bug, you should get caught in a login loop instead of seeing this error.

**Comment by jersiovic** [comment]
Related with that, despite I click on logout, and I called /Orchard.OpenId/Access/Logout and I clear cookies from browser when postman starts  Code Flow I directly see the consent view, but I'm not able to be asked another time for my user and password

**Comment by PinpointTownes** [comment]
Oh wait, the authorization attribute fix is not in the oauth2 branch: https://github.com/OrchardCMS/Orchard2/commit/8c98dcef35ff007e7edb2e14abec03490d47b3e6

**Comment by jersiovic** [comment]
ah ok, i'm going to merge it on my branch locally for testing it and if everything is ok for me there is no problem on merging oauth2 branch on master

**Comment by PinpointTownes** [comment]
With this fix, you'll likely hit the same issue and be caught in a login loop. Can you confirm that?

If so, we should try with another client (I tested manually and it worked)

**Comment by jersiovic** [comment]
It worked properly. I didn't suffered that loop.
I have added the PR https://github.com/OrchardCMS/Orchard2/pull/623
@sebastienros

**Comment by PinpointTownes** [comment]
> It worked properly. I didn't suffered that loop.

FYI, I tested with the Chrome version of Postman and it indeed worked like a charm.
Looks like this bug only impacts the desktop version.
