### ISSUE TITLE
Security Menu in wrong place.

### ISSUE THREAD

**Issue by mdockal** [OrchardCMS/Orchard2#625]
Why is the Security Menu under the Design Menu in the dashboard?   Should be at the root of menu.    Makes no sense!

**Comment by sebastienros** [comment]
Please watch the meeting we had on 9/13/2016 where we talked about the menu organization. It made some sense for all the people at the meeting. At the same time we are not even in beta, so we can always reconsider it once the menu is more complete, along with all other items. We might find some discrepancies then.

Right now if you really care about it you can create a module that would override its location.

**Comment by Jetski5822** [comment]
Here we go: https://www.youtube.com/watch?v=fOZGjZUcl00
