### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.Identity.RoleManager`1[Orchard.Security.Role]'

### ISSUE THREAD

**Issue by BilalHasanKhan** [OrchardCMS/Orchard2#628]
I am using VS2017 and setup a SAAS recipe site everything worked well until this point then in DashboardI went in and tried to enable Security-> Role which gave an exception and since then I am unable to performa any action and keep getting the same error.
I conveyed this to @Jetski5822  who suggested to delete App_Data\Site folder and then I removed the database as well and created a fresh site with same configuration and tried same steps and the error recurred.
Screenshot attached 
![image](https://cloud.githubusercontent.com/assets/1527108/24101341/eea59dee-0d9d-11e7-90c6-a50bceba9d99.png)

**Comment by sebastienros** [comment]
Can't repro anymore
