### ISSUE TITLE
 Query<TDocument> [Bug]

### ISSUE THREAD

**Issue by GVX111** [OrchardCMS/Orchard2#63]
Can't create content.
Error in: EfContentQueryStore line 34 Method: Query
<pre>An exception of type 'System.NullReferenceException' occurred in EntityFramework.Core.dll but was not handled in user code
Additional information: Object reference not set to an instance of an object.</pre>
InnerExceptionMessag: Message = "An attempt was made to use the model while it was being created. A DbContext instance cannot be used inside OnModelCreating in any way that makes use of the model that is being created."

**Comment by Jetski5822** [comment]
Yeah I am getting the same, I am hesitant to touch this code as it is due to be replaced by the work @sebastienros is doing

**Comment by GVX111** [comment]
oh it will be good :) on Brochard migrated on Yessql?
