### ISSUE TITLE
Cannot create content items with reusable parts

### ISSUE THREAD

**Issue by domonkosgabor** [OrchardCMS/Orchard2#632]
Let's say I would like to define a content type that has two reusable content parts. To do that, first I have to define the part in the migration in the following way:

```
_contentDefinitionManager.AlterPartDefinition(nameof(AddressPart), builder => builder
           .Reusable()
);
```
that makes the `AddressPart` ContentPart reusable. To attach this part twice to a `Person` content type, I need to use the following type definition:

```
_contentDefinitionManager.AlterTypeDefinition(nameof(Person), builder => builder
                .WithPart("HomeAddress", nameof(AddressPart), cfg => cfg
                    .WithDisplayName("The home address of the person."))
                .WithPart("WorkAddress", nameof(AddressPart), cfg => cfg
                    .WithDisplayName("The work address of the person."))
);
```

The first parameter of the `.WithPart()` method will be the named name of the part (like `HomeAddress`) and the second one will the name of the part (`AddressPart`).

Now I have a `Person` content type with two attached `AddressPart` content part. To create a new `Person` content item in a service, I injected the `IContentManager` to my service and tried to fill the properties of one of the `AddressPart` with explicit syntax:

```
var personContentItem = _contentManager.New(ContentTypeNames.Person);
var workAddress = personContentItem.As<AddressPart>();
workAddress.City = "Budapest";
```

Of course, the `personContentItem.As<AddressPart>()` should not has idea which `AddressPart `I would like to use, thats clear. But the method can provides me the `AddressPart`, because the `Person `content type only has one `AddressPart `attached.

The reason for that is when I called the `_contentManager.New()`, inside that the `ContentItemBuilder` calls the `Weld `extension method in the `ContentExtensions` class that adds the content elements by name. But the name of the content element is `AddressPart`, which is already exist, then the method will not add the second `AddressPart` to the `ContentElement.Data` array.

```
public static ContentElement Weld(this ContentElement contentElement, string name, ContentElement element)
        {
            JToken result;
            if (!contentElement.Data.TryGetValue(name, out result))
            {
                element.Data = JObject.FromObject(element);
                element.ContentItem = contentElement.ContentItem;

                contentElement.Data[name] = element.Data;
            }
            return contentElement;
        }
```

I see that these methods are working by using the name of the part, not the named name of the part. 
I have also tried to fill the properties of the AddressParts with dynamic syntax, without success.

Maybe I have implemented the migration in a wrong way or I have misunderstood the way we use Reusable parts?

**Comment by sebastienros** [comment]
I might have broken it recently, I also noticed the editors didn't work anymore with named parts, I will look at this:

>  the name of the content element is AddressPart, which is already exist

Looks like where the issue is

**Comment by sebastienros** [comment]
The code in Orchard looks good, but in your code you are doing `.As<AddressPart>()` which you are not allowed to for accessing named parts. 
Instead do `contentItem.Get<AdressePart>("HomeAddress")`

**Comment by sebastienros** [comment]
I found out what you meant in the `.New()` call, I am fixing it, but what I said in the previous one about `As()` still applies.
