### ISSUE TITLE
Issues with tenant administration

### ISSUE THREAD

**Issue by lukaskabrt** [OrchardCMS/Orchard2#640]
- if I create a tenant with an URL prefix and later I want to edit it, I am unable to save the changes. The message "The url prefix is already used by another tenant" appears
- if I create a tenant with a host and a prefix and another tenant with a different host but the same prefix, I am unable to save changes to either of them without changing the prefix

**Comment by sebastienros** [comment]
Where is the PR 😅

**Comment by lukaskabrt** [comment]
It is there #641 ;-)
