### ISSUE TITLE
Is there any live demo for Orchard2 ?

### ISSUE THREAD

**Issue by mikeandersun** [OrchardCMS/Orchard2#65]

**Comment by sebastienros** [comment]
There is almost nothing to show at the moment, you can barely Setup an instance. BTW you should join Gitter if you want to talk about it.

**Comment by sebastienros** [comment]
https://gitter.im/OrchardCMS/Orchard2

**Comment by emiliano84** [comment]
do you have any plan to provide a live demo for orchard core? especially now that almost reached beta3?
