### ISSUE TITLE
Fields Placement

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#651]
With the latest version (may be since .csproj migration?), the 'part' (I don't remember its name) that appeared in the 'edit content type definition' page to specify where the fields are placed amongst the parts is not available anymore.

Can you confirm it is not there anymore?

I also remember a discussion with @jtkech (May be in one of his PRs?) and that we need to find a solution to specify the Edit placement of fields and parts (... and tabs, later) in a flexible way, without restrictions.

**Comment by jtkech** [comment]
The name is the content type where this fake part is added, e.g `Page`.

Just tried it (but on my `csproj-updates` working branch). I added a text field in the Page content type, then i got the following, so it seems to work for me.

     Page - Contains the fields for the current type

About the discussion, i don't remember exactly but the related issue is #527. Need to leave soon but i'll let you know if i retrieve more details.

Best.

**Comment by agriffard** [comment]
OK, thank you. My bad, the '_Content type_ - Contains the fields for the current type' is there.
