### ISSUE TITLE
why do we need to use brackets for ifs with one line? 

### ISSUE THREAD

**Issue by psp589** [OrchardCMS/Orchard2#661]
I see the code clearer and cleaner removing brackets when there is no need of them

**Comment by agriffard** [comment]
http://peterkellner.net/2009/10/19/codingstandards-csharp-braces/

**Comment by psp589** [comment]
@agriffard Thank you for your answer, I think the good reason is when the code grows and you need to add more lines to an if .. (I mean, to avoid the bug there because the code then will need to be between brackes then)
For me that does not worth the styling.

**Comment by RobHawk90** [comment]
But if you need to put some lines of code in your if statement, you should refactor your code adding some functions/methods to it...
