### ISSUE TITLE
Menu levels stops to 6

### ISSUE THREAD

**Issue by justgfather** [OrchardCMS/Orchard2#663]
There seems to be a limit in the UI that only allows for 6 levels of depth in the menu, this is a problem for the breadcrumbs of my website. Can someone help. 
![orchard levels limit](https://cloud.githubusercontent.com/assets/22310057/24711328/9f4b60ba-19ed-11e7-9559-08b3e4a85497.PNG)

**Comment by sebastienros** [comment]
Did you mean to create this issue here: https://github.com/OrchardCMS/Orchard ?
