### ISSUE TITLE
Widget position does not change when contentitem has draft

### ISSUE THREAD

**Issue by matiasmolleja** [OrchardCMS/Orchard2#671]
Hi,
Repro steps:
1. Create two paragraph widgets titled "a" and "b".
2. Edit "b", change title to "bDrafted". Then "bdrafted" appears as the title of content item "b" in the layers admin.
3. Change position of "bDrafted".
4. Go to frontend. The frontend does not reflect the change we did in admin.

**Comment by sebastienros** [comment]
They are drafts, I assume that's expected. (in this case)
I am not sure how/when they are ordered.

**Comment by matiasmolleja** [comment]
Yes, I think it is expected when the content item is only a draft before being published.
But not if it is a content item already published to wich the user adds a draft, as a work in progress.

**Comment by sebastienros** [comment]
I see, what you mean is when you move things around it's live, but if the content item has a draft you are actually moving the draft. I can't imagine any scenario that would be perfect here. Or that when we move a published item it creates a draft automatically.

**Comment by matiasmolleja** [comment]
In the Index action of AdminController of Layers Module, the widgets are retrieved through this line:
`var widgets = await _layerService.GetLayerWidgetsAsync(c => (c.Latest== true);`

I think we should get:
1. All published items (with or without a draft created).
2. All content items that have only a draft (never published).

**Comment by matiasmolleja** [comment]
But I don't know how to do that without adding a few lines of really ugly code :)

**Comment by matiasmolleja** [comment]
That way a user can change position of the currently published items.
And he can too change position of items that are only drafts and he plan to release then in the future.

**Comment by sebastienros** [comment]
That would mean the same content item would appear twice, and publishing a draft would overwrite the changed location of the published item. Maybe a message or some other way to apply the position change to the published item would be better. So when you move an item which has a draft, we could have another action to apply it on the published version too.

**Comment by matiasmolleja** [comment]
Yes, but I don't like the idea of having the same content item appearing twice. It is confusing for an end user that does not need to know anything about a content item having two separate versions. 
After thinking about this, what you already had was OK, with the only exception that changes in a content item published+drafted were not reflected on the frontend.
I made I PR following in part what you proposed. Maybe it solves this issue. 
Every time the user changes the position of the draft, the published version is modified accordingly. No appearing twice, and no message.
Please, let me know what do you think.

**Comment by sebastienros** [comment]
So you are applying the value to the published version by default. I assume that's ok as this is what we do if  there are no drafts anyhow.
