### ISSUE TITLE
Be able to start up from visual studio

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/Orchard2#68]
Just began with Orchard2, so, here it's just to show you what I did to make it working... Maybe it can give you an idea to do it in a better way...

To solve the issue seen in `ExtensionAssemblyLoader`, In `ModuleLoaderContext.cs` at the beginning of the constructor I've added this.

            Project.DefaultCompiler = Project.DefaultRuntimeCompiler;

This way, the `LibraryExporter` uses the right compiler.

But still an issue when compiling a view because in the `DefaultRoslynCompilationService` singleton, a `LibraryExporter` is resolved in the constructor (maybe too early related to my first update). So, in this class, at the beginning of the `GetApplicationReferences()` method, I've added this.

            Project project;
            var libraryExporter = _libraryExporter;
            if (Project.TryGetProject(_environment.ApplicationBasePath, out project))
            {
                var engine = new CompilationEngine(new CompilationEngineContext(
                        _environment,
                        _runtimeEnvironment, // new service resolved in the constructor
                        _loader,
                        new CompilationCache()));

                libraryExporter = engine.CreateProjectExporter(
                    project, _environment.RuntimeFramework, _environment.Configuration);
            }

Then, afterwards I use `libraryExporter` in place of `_libraryExporter`...

Note: In Visual Studio, Orchard.Web is set as the Startup project, and the `web` command is selected.

Best

**Comment by GVX111** [comment]
Good Job :) can you make PR?

**Comment by jtkech** [comment]
Ok, just want to revise a little my code, I can do it tomorrow

**Comment by GVX111** [comment]
somewhere is bug. every page load Memory increasing 50-80MB. it's memory leak.
but for testing it is good.

**Comment by sebastienros** [comment]
Is the memory leak specific to this branch or overall?

**Comment by sebastienros** [comment]
Just a quick note on ExtensionAssemblyLoader, I am currently reviewing the code and making some changes to build on dotnet5.4, also the Assembly loading story will change significantly so please try not to go crazy with it. Running from VS is not that critical, and having changes for that might be risky for the future.

**Comment by GVX111** [comment]
overall

**Comment by GVX111** [comment]
he cloning libraryexporter and old exporter doesn't disposing

**Comment by jtkech** [comment]
@sebastienros ok, anyway I've learned new things...

@GVX111 thanks to point out the memory drawback. But did you try it with the PR #71 where I no longer inject an ILibraryExporter through the constructor and only use the newly created (as done in ExtensionAssemblyLoader)...

Best

**Comment by sebastienros** [comment]
I will take your PR, at least to unblock something else ;) hope it works
