### ISSUE TITLE
Build in command line is broken

### ISSUE THREAD

**Issue by kerryjiang** [OrchardCMS/Orchard2#702]
I got a lot of errors like below:

/Users/xxx/yyy/orchard/master/src/OrchardCore/OrchardCore.AsModule/OrchardCore.AsModule.props(26,5): error MSB3021: Unable to copy file "Module.txt" to "/OrchardCorePackages/Orchard.Tenants/Module.txt". Access to the path '/OrchardCorePackages/Orchard.Tenants' is denied. [/Users/xxx/yyy/orchard/master/src/OrchardCore.Modules/Orchard.Tenants/Orchard.Tenants.csproj]

I checked the file OrchardCore.AsModule.props, and found a variable $(Temp) is used in the path.
It seems like $(Temp) was empty when I ran "dotnet build".

<Copy
      SourceFiles="@(PackageAssetFiles)"
      DestinationFolder="$(Temp)\OrchardCorePackages\$(MSBuildProjectName)\%(RecursiveDir)" />

My environment:
OS: osx Sierra 10.12.4
dotnet version: 1.0.1

**Comment by sebastienros** [comment]
It's because you are on a mac, that explains.
We will fix it, in the meantime please define an environment variable named Temp that points to a temporary folder. On Windows it's the local user's one.

**Comment by sebastienros** [comment]
I assume we need to ensure the same solution is applied on Linux.

**Comment by jtkech** [comment]
I will try to get rid of the Temp folder.

**Comment by sebastienros** [comment]
@kerryjiang would you mind testing the branch for this PR https://github.com/OrchardCMS/Orchard2/pull/707 to ensure it fixes your issues ? At least the build issues.

**Comment by kerryjiang** [comment]
It works great!
Thank you guys!
