### ISSUE TITLE
Drafts are broken

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#712]
Tried to create a Blog post Draft, the draft is created but the content is the same as the published one.
Saving a Published version works.

@agriffard can you confirm?

**Comment by agriffard** [comment]
I tested and I confirm that when you create a draft, if you edit the Body of the BodyPart is for example, a new version is added but with the previous BodyPart, without changes.

**Comment by sebastienros** [comment]
The repro is to have an autoroute part with a pattern, for instance `{{slug}}` and to allow custom permalinks, then when editing an already published item, it the permalink is empty it will regenerate it. If it regenerates then the body is correctly taken in the draft, if it's not empty the body is not stored.

The body part is correctly bound to the model, but somehow not saved. Everything else works. Same issue on markdown.

**Comment by lukaskabrt** [comment]
It seems, there isn't any call to `ISession.Save` when saving the draft. 

If user saves & publishes a content item, `IContentManager.PublishAsync` is called. It sets `Latest` propery on the original and on the new content item and saves them both.

If user saves a draf, there is no call to `ISession.Save` after the content item is updated with posted data (`await _contentItemDisplayManager.UpdateEditorAsync(contentItem, this)`). The issue affects not only body, but all fields.

Quick fix is to add `_session.Save` to `Orchard.Contents.AdminController.EditPOST`
```
[HttpPost, ActionName("Edit")]
        [FormValueRequired("submit.Save")]
        public Task<IActionResult> EditPOST(string contentItemId, string returnUrl)
        {
            return EditPOST(contentItemId, returnUrl, contentItem =>
            {
                //TODO add this line
                _session.Save(contentItem);

                var typeDefinition = _contentDefinitionManager.GetTypeDefinition(contentItem.ContentType);
                _notifier.Success(string.IsNullOrWhiteSpace(typeDefinition.DisplayName)
                    ? T["Your content draft has been saved."]
                    : T["Your {0} draft has been saved.", typeDefinition.DisplayName]);

                return Task.CompletedTask;
            });
        }
```

I am just not sure, if this is the correct place to handle it.

**Comment by sebastienros** [comment]
There is a call to Save, but as you mention, before the content is updated. Which could mean that if a query comes previously, it will be saved before it's modified. I will try to add a save after the changes. We really need you on this project ;)
