### ISSUE TITLE
Resource TagHelpers don't work from packages

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#713]
I created a new web app and referenced the OrchardCore.Cms bundle package.
Typed AddOrchardCms and UseModules.

After Setup, the <resource> tag helpers are not rendered.

**Comment by jtkech** [comment]
Just tried with our `Orchard.Cms.Web` app but by only referencing packages: `Orchard.Hosting.Console` and  `OrchardCore.Cms` packages from your feed.

And it works.

Can't right now, i will try it with a new web app this night.

**Comment by sebastienros** [comment]
ping me on skype plz

**Comment by sebastienros** [comment]
Did you try from the package on the myget gallery?

**Comment by jtkech** [comment]
Sorry, not closed to my pc, return back in 2 or 3 hours.
Yes i tried with the myget feed.
But just saw you closed the issue?

**Comment by sebastienros** [comment]
yes, I trust you, I will check again, I changed the version of RM package and cleared my nuget cache
