### ISSUE TITLE
dotnet publish doesn't copy App_Data

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#714]
More specifically it's not copying `Settings.txt`.
This is necessary.

@jtkech

**Comment by jtkech** [comment]
Just tried with `Orchard.Cms.Web`, it works on my side. But if you created a new web app, you need to add the following as in `Orchard.Cms.Web.csproj`. Because we decided to not use `App_Data` in `AsBundle.targets`, but can be changed if you want.

    <ItemGroup>
      <Compile Remove="App_Data\**" />
      <Content Remove="App_Data\**" />
      <EmbeddedResource Remove="App_Data\**" />
      <None Remove="App_Data\**" />
    </ItemGroup>

Best.

**Comment by sebastienros** [comment]
Ah you are right.
What is weird is that it copied some of the file, but now I remember. 
So I will change my web app.

**Comment by sebastienros** [comment]
Actually for the OrchardCore.Cms bundle it would make sense to have it.
And also probably define the variable that sets which files will be copied that are specific to Orchard.
Not important for now.

**Comment by jtkech** [comment]
If you agree, in `AsBundle.targets` we could just also include `App_Data\Sites\**`.

**Comment by sebastienros** [comment]
Not AsBundle, it's just for the Orchard.Cms

**Comment by jtkech** [comment]
Ah, ok, will do it
