### ISSUE TITLE
can not pass build for Orchard.Cms.Web

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard2#720]
win 10
vs 2017 community
![duplicate](https://cloud.githubusercontent.com/assets/297675/25312027/5f9e403e-27dc-11e7-8279-d2fa434aa5b4.png)

**Comment by sebastienros** [comment]
Can't repro.

**Comment by infofromca** [comment]
@sebastienros 
I just installed vs2017 (15.2) pro in windows 10 pro.
The same issue.
![cs0579-cli](https://user-images.githubusercontent.com/297675/27011404-11fd9e46-4e89-11e7-9ecc-f3157644a93b.png)
![cs0579-vs](https://user-images.githubusercontent.com/297675/27011405-12018db2-4e89-11e7-8f65-cb3184509886.png)

**Comment by infofromca** [comment]
after I use brand new clone, everything is ok
