### ISSUE TITLE
Question: Is there any OrchardCMS / IdentityServer3 or 4 implementations around?

### ISSUE THREAD

**Issue by nigel-dewar** [OrchardCMS/Orchard2#722]
Hi Guys,

Is it possible to implement Orchard CMS with IdentityServer 3 or 4? And if so, is there any samples one can reference?

Cheers

**Comment by alexbocharov** [comment]
Orchard CMS or Orchard 2 (OrchardCore.Cms)?

**Comment by nigel-dewar** [comment]
Hi Thanks for your reply,

Either one. Id assume if possible then Orchard CMS would likely go with identityserver3 and Orchard 2 would likely go with IdentityServer4 (my assumptions)

**Comment by alexbocharov** [comment]
Orchard 2 is supports [OpenIddict](https://github.com/openiddict/openiddict-core)([Orchard.OpenId](https://github.com/OrchardCMS/Orchard2/tree/master/src/OrchardCore.Modules/Orchard.OpenId))

**Comment by nigel-dewar** [comment]
Nice! Thanks for the info.

I'll have a good look into it. Cheers
