### ISSUE TITLE
LinkEntry: type attribute is encoded

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#733]
If you enable XmlRpc and RemotePublishing, these metas are inserted but the type attribute is encoded so the `+` is rendered as `&#x2B;`:

```
<link href="http://localhost:2918/Contents/Lists/4sycaf2c49s4kxdmm421jda0cs/rss" rel="alternate" title="Blog" type="application/rss&#x2B;xml" />
<link href="http://localhost:2918/xmlrpc/metaweblog" rel="wlwmanifest" type="application/wlwmanifest&#x2B;xml" />
<link href="http://localhost:2918/xmlrpc/metaweblog/4sycaf2c49s4kxdmm421jda0cs/rsd" rel="EditURI" title="RSD" type="application/rsd&#x2B;xml" />

```

**Comment by sebastienros** [comment]
It still works, and it's the new default encoding behavior in ASP.NET, there is nothing we can do. Until someone famous on the internet complains. I am not famous enough yet to make this be changed.
