### ISSUE TITLE
The configuration file 'Settings.txt' was not found

### ISSUE THREAD

**Issue by zhengxiaosong** [OrchardCMS/Orchard2#743]
Hello:
    I clone from the master branch and run it in my vscode(macOS sierra 10.12.4). After the first configuration, I stop and run it again, it raise an exception tell me the configuration file 'Settings.txt' was not found in "src/Orchard.Cms.Web/App_Data/Sites/Default/". I open the "src/Orchard.Cms.Web/App_Data/Sites/Default/" folder and found that there is only one file named "yessql.db" .
Then I use "dotnet clean" command to clean the solution, and rebuild it. But it still give me the same result. 
How could I do to make it run in currect? 
Thank you very much!

**Comment by sebastienros** [comment]
It means the setup failed. Please share the Appl_Data/Logs file with us, then delete the app_data folder to start fresh.

**Comment by zhengxiaosong** [comment]
Oh, I had been deleted all files that created by the program, contains "App_Data" and Logs files. then i rebuild it and the exception is not appear again. Sorry i can't provide the log. And thank you for ur attention.
