### ISSUE TITLE
Errors generating when trying to run the Orchard 2 solution from  Visual Studio 2017

### ISSUE THREAD

**Issue by blachawk** [OrchardCMS/Orchard2#747]
> Ensure OrchardCore.Cms is the startup project and run it

- I'm using Visual Studio 2017 Community Edition on Windows 10.  
- I cloned my fork version the Orchard2 project via Git
- From VS2017, I opened the solution `Orchard.sln`
- The following errors display in my error log next:

![screenshot 2017-05-12 09 46 02](https://cloud.githubusercontent.com/assets/3985279/26000709/023ad224-36f8-11e7-9605-c4d570258481.png)

- I then found and set OrchardCore.Cms to be the start up project.
- I then pressed CTRL+F5 to run the solution, but when I do, I get the following error:

![screenshot 2017-05-12 09 53 41](https://cloud.githubusercontent.com/assets/3985279/26001061/206c6cd4-36f9-11e7-9701-66c907c56656.png)

What am I doing wrong?

Thanks

**Comment by thierholzer** [comment]
I just set the actual cms application project as the startup project and I’m not having any issues running it.  Maybe try that?

[cid:image001.jpg@01D2CB0B.E4F9A350]

Tina Hierholzer

**Comment by sebastienros** [comment]
Set Orchard.Cms.Web as the startup project. It's at the bottom of the solution

**Comment by jtkech** [comment]
Oh, it seems that there is an error about VS2017 in the `README.md` file.
Thanks @blachawk

**Comment by blachawk** [comment]
I went ahead and set **Orchard,Cms.Web** as the startup project, and also installed gulp `npm install -g gulp`  via powershell.  I then re-opened the solution and was able to run the project.

Thanks for the help!

**Comment by sebastienros** [comment]
`npm install` is on;y necessary if you develop modules that require the Assets pipeline.
