### ISSUE TITLE
Setting a Home Page

### ISSUE THREAD

**Issue by thierholzer** [OrchardCMS/Orchard2#754]
I have the Orchard CMS Project up and running and this may be a dumb question but I'm having issues getting my content to show up on the home page. I created a page and added some basic text. I tried setting the permalink to "~/", and "/" and just left if blank and it still doesnt render the content on the home page. 

I know the Orchard.Demo has an index page, but I don't imagine I have to hook that up to render the content right? Am I missing something?

Thanks.
Tina

**Comment by sebastienros** [comment]
You need to go to the type settings of your content item, and in AuroroutePart settings check the option to allow it to be set as the homepage.

You are not the first one to be blocked on it, we might want to make this option a default for the types we create in the recipes.

@agriffard Would you mind doing it? (Page and Blog).

**Comment by thierholzer** [comment]
Ok Thanks, found it I was wondering where that checkbox was hiding!

**Comment by agriffard** [comment]
OK, I will modify the setup recipes.

**Comment by sebastienros** [comment]
I didn't mention BlogPost on purpose. How often do you see people set a specific blogpost as homepage when you have a blog. Usually it's the blog itself, or another page.
