### ISSUE TITLE
Login fails

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/Orchard2#758]
I updated to the latest commit https://github.com/OrchardCMS/Orchard2/commit/1c3b9391eeda395db2a866ca3fb3991b4d4c7b61

1. Create a brand new site (Blog recipe) without table prefix
2. Windows 10
3. I created a system account and register a new local account
4. The setup works successfully and shows the default content
5. localhost:5000/admin does not admit my system account and local account (Invalid login attempt.)

**Comment by sebastienros** [comment]
Can you check the user is correctly created in the database?
I tried it myself and it worked fine.
What database are you using?

**Comment by dodyg** [comment]
```
Id	DocumentId	NormalizedUserName	NormalizedEmail
1	50	DODYG1	DODYG+1@SILVERKEYTECH.COM
```
SQL Server 2014

**Comment by dodyg** [comment]
I deleted the database, the App_Data folder and restart the command several times and retry and got the same result. It's weird.

**Comment by sebastienros** [comment]
I tried again with SQL 2016 and Sqlite and everything is working.

Maybe you could try to debug the code to see what is happening?

**Comment by DannyT** [comment]
Just trying out the latest from master and seeing the same issue. 

From the Log:

`2017-05-26 16:04:37.9035|Default|0HL548VHLNSH9|0|Orchard.OpenId.Startup|WARN|The OpenID Connect module is not correctly configured. `

Which presumably is a clue, will keep digging.

**Comment by DannyT** [comment]
simply deleting the db and app_data folder and trying again worked for me, sorry that's not much use!

**Comment by sebastienros** [comment]
Closing as nobody can reproduce it.
