### ISSUE TITLE
shape Layout not found

### ISSUE THREAD

**Issue by Yambr** [OrchardCMS/Orchard2#802]
Hi,

I'm trying to create my simple theme, I made a full copy of TheTheme and added a reference to OrchardCore.Cms. In Admin Panel i set my theme and i got error in home page 'Shape Layout not found'..

In the source code, I did not find anything related to TheTheme (only in recipes)

**Comment by agriffard** [comment]
The feature corresponding to your theme has to be enabled.

You can do it in the database or use the `adminthemes `branch in which we improved the dashboard for the themes.

**Comment by Yambr** [comment]
Thanks, i'm trying it
