### ISSUE TITLE
An invalid password doesn't prevent setup

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#817]
Then the site is in a corrupted state as the admin user is not created.

**Comment by agriffard** [comment]
See also #250 , #191

**Comment by xperiandri** [comment]
How to debug this? Is it not about password escaping, serialization, deserialization?
I tried but can't figure out where this can happen

**Comment by Skrypt** [comment]
maybe related : https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address
