### ISSUE TITLE
OSX - Logs are not stored at right path

### ISSUE THREAD

**Issue by carlwoodhouse** [OrchardCMS/Orchard2#818]
Not sure if this happens in windows but in osx logs are stored in App_Data but with a filename of
App_Data\Logs\file... rather then in a folder.

<img width="478" alt="screen shot 2017-06-12 at 23 42 05" src="https://user-images.githubusercontent.com/465424/27058443-304374de-4fc9-11e7-8573-af11de9a8640.png">

**Comment by sebastienros** [comment]
We probably need to use '/' when creating these files
