### ISSUE TITLE
Warning on setup: Orchard.Media dependency

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#821]
Logged during setup with the latest version:
`Orchard.Environment.Extensions.ExtensionManager|WARN|No loader found for extension "Orchard.Media". This might denote a dependency is missing or the extension doesn't have an assembly. `

**Comment by sebastienros** [comment]
This happens to me when I have an existing instance with media, then I switch to a branch that doesn't have media.
Or maybe the media folder is still here from a previous setup, in the /Packages folder. Clean it and it should go away.

**Comment by jtkech** [comment]
For infos, normally you could just do a `Clean` or `Rebuild` command. This because in our msbuild script we have a custom `CleanPackageAssets` task which removes all `/Packages` files.
