### ISSUE TITLE
Incorrect hint in OpenID Connect settings

### ISSUE THREAD

**Issue by anoordende** [OrchardCMS/Orchard2#842]
The hint text in **Settings -> OpenID Connect -> Endpoints -> Enable UserInfo Endpoint** seems incorrect, this should be:

`Enables action /Orchard.OpenId/UserInfo/Me`

**Comment by PinpointTownes** [comment]
Nice catch @anoordende!

Definitely something worth fixing :+1:

**Comment by anoordende** [comment]
@PinpointTownes Want me to raise the PR when I have 2 mins?

**Comment by PinpointTownes** [comment]
@anoordende that would be much appreciated, thanks!

While you're at it, please also add POST support for the Me action. For some reasons, it looks like it now only accepts GET (to be standard-compliant, it must supports both GET and POST): https://github.com/OrchardCMS/Orchard2/blob/master/src/OrchardCore.Modules/Orchard.OpenId/Controllers/UserInfoController.cs#L29
