### ISSUE TITLE
Setup finishes even if SQL Server DB can't be accessed

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/Orchard2#85]
Repro:
- Run setup
- Leave connection type at default (SqlConnection)
- Provide an invalid connection string (in my case the name of the server didn't match the actual one)

Setup finishes and the site is running (console shows SQL connection errors).

**Comment by Bitexirtz** [comment]
I tried to run setup and provided a correct (SqlConnection) connection string, console shows but SQL connection errors are displayed. I am totally lost in Orchard 2. I hope someone would write a setup tutorial. Thank you.

**Comment by jimitndiaye** [comment]
I second the need for some kind of setup guide. Maybe update the readme with a few lines describing what's changed in setup. These are the first steps ppl would follow to get started with the codebase so I think they're pretty important.

**Comment by GVX111** [comment]
Setup is not finished. Jetski working on it.

**Comment by agriffard** [comment]
see #355
