### ISSUE TITLE
Support service suppression

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#850]
Be able to remove a service from another module/feature.

c.f. discussion in https://github.com/OrchardCMS/Orchard2/pull/843

**Comment by Jetski5822** [comment]
Can't you just replace?

**Comment by sebastienros** [comment]
I changed the title, it's not about supporting this attribute, but defining a solution that works, whatever it is. Read the linked PR comments as it explains it doesn't work right now.

**Comment by Jetski5822** [comment]
Okay, still confused as replace should work. :/

**Comment by sebastienros** [comment]
Maybe I broke it at some point with multi-tenant support. I don't know if we have any test for this.

**Comment by jrestall** [comment]
I can look into this over the next few days and submit a pull request. I'll make sure to add a couple unit tests.

@Jetski5822, Replace will now work again if you get latest with my change, but there's some cases with FeatureTypeProvider that I want to check. For example I expect issues if a IPermissionProvider was Replaced since that is used by the FeatureTypeProvider.

**Comment by jrestall** [comment]
Some initial work in my branch on this which includes a failing unit test for the TypeFeatureProvider issue ('CanReplaceDefaultServiceWithCustomService'):

https://github.com/jrestall/Orchard2/commit/bf5dae7198dcb5c2874d833b40984143c5c0751e
https://github.com/jrestall/Orchard2/commit/03633b98d33e5c0fb64f5307de110b0e624daaec

Hopefully the unit test helps clarify the issue Nick. I'll see what I can do for a fix when I get a chance.

**Comment by Jetski5822** [comment]
Ah yes!!... It was broken, due to each service having separate registration, so replace would never had worked. Your stuff fixed that.

Good work so far @jrestall

**Comment by jrestall** [comment]
This issue could be closed now.
