### ISSUE TITLE
Time to update to 2.0.0-preview2-final

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/Orchard2#855]

**Comment by sebastienros** [comment]
Yes, now we can start.

**Comment by PinpointTownes** [comment]
Note that you'll be blocked by https://github.com/OrchardCMS/Orchard2/issues/730 (unless you decide to remove the OpenID module, of course).

Just so you know, I won't release a version of ASOS/OpenIddict compatible with preview2 for two reasons:

  - The ASOS/OpenIddict ports rely on API changes in the events model that were not included in preview2. See https://github.com/aspnet/Security/pull/1266 for more information.

  - There's a huge bug in the current bits that will require a fix that won't be obviously included in preview2: https://github.com/aspnet/Options/issues/211.

**Comment by alexbocharov** [comment]
We can temporarily comment out the module.

**Comment by sebastienros** [comment]
I assume the API changes will be in RTM, I believe they have been merged already.
For the options issue, seems like a breaking change, but that can be handled in the client libraries, right?

Can I assume it should be ok with 2.0 RTM for asos/openiddict ? 

We can still start the migration to preview-2, keep this one for later. And this is clear we will find other issues on the way. We need to start now to be able to give feedback and fix bugs before RTM ships.

**Comment by PinpointTownes** [comment]
> Can I assume it should be ok with 2.0 RTM for asos/openiddict ?

I'll push new ASOS/OpenIddict bits (compatible with the nightly preview3 bits) to the aspnet-contrib feed in the next few days, when https://github.com/aspnet/Security/issues/1282 and https://github.com/aspnet/Security/issues/1287 are fixed.

**Comment by Jetski5822** [comment]
I think we should hold off, I dont feel comfortable with these breaking changes... dunno

**Comment by sebastienros** [comment]
Hold off? The next version will prbably be RTM, unless we want to stick with 1.x we should definitely try a migration right away on a branch to at least know what is blocking.

**Comment by Jetski5822** [comment]
Yeah that's cool, I'd hold off on merging it to master though.

**Comment by sebastienros** [comment]
Sure, we'd only merge when it's released.

**Comment by Jetski5822** [comment]
Okay cool. Now get to it!!

**Comment by Jetski5822** [comment]
With us upgrading we should also think about using the HealthCheck APIs. https://github.com/dotnet-architecture/HealthChecks

**Comment by PinpointTownes** [comment]
Note: the OpenIddict and aspnet-contrib packages compatible with the ASP.NET Core 2.0 preview3/RTM nightly builds are now available.

**Comment by jtkech** [comment]
👍

**Comment by jtkech** [comment]
I began to try `aspnetcore 2.0.0-rtm-26227`.

I started with 431 errors but now i only have 7 errors. All core projects pass, only 2 modules fail to build, but i have not yet used the latest `OpenId` packages, i will try it tomorrow ...

I've done some adaptations that will need to be checked. Here, just some infos:

- No more `ICompilerCacheProvider`. To cache view compilations across tenants, i needed to use an `IViewCompilerProvider`. 

- `ViewsFeature` has changed, i needed to adapt our custom `ViewsFeatureProvider`.

- No more `PlatformServices`. In unit tests i've used `AppContext` to get the `ApplicationBasePath`.

- `ResponseCachingPolicyProvider` has changed. Right now, i only commented out some lines.

- ...

**Comment by jtkech** [comment]
Some parts will need to be reviewed by the related people, but finally i was able to do these first tests.

- Fresh blog setup.
- Login
- Go to the admin.
- Create a new page



Still one problem, i'm not redirected to the login if i try to go to the admin without being authenticated.

**Comment by agriffard** [comment]
Migrated to 2.0.0
