### ISSUE TITLE
Setup with CMS recipe: wrong dynamic content id

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#860]
In Ochard.Setup\cms.recipe.json, 
`"ContentItemId": "[uuid()]"`
should be:
`"ContentItemId": "[js: uuid()]"`

or the dynamic id won't be interpreted correctly.

**Comment by ASVS-Kartheek** [comment]
I'm a first timer can I take up this work?

**Comment by agriffard** [comment]
Sure you can. 

Fix it (2 occurrences in the recipe). 
Test Setup again and make sure the contentItemId is well generated in database. 

Submit a PR.

**Comment by kirst** [comment]
I hope I didn't step on any ones toes with this one it was still open. Got excited on the first commit and completely missed the second instance.
