### ISSUE TITLE
Got error when "dotnet restore"

### ISSUE THREAD

**Issue by li0803** [OrchardCMS/Orchard2#863]
below are my log from vscode when run the command "dotnet restore"
`Restoring packages for C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-master\src\OrchardCore.Modules\Orchard.Body\Orchard.Body.csproj...
  Restoring packages for C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-master\src\OrchardCore.Modules\Orchard.Alias\Orchard.Alias.csproj...
  Restoring packages for C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-master\src\Orchard.Mvc.Web\OrchardCore.Mvc.csproj...
  Restoring packages for C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-master\src\Orchard.Cms.Web\Orchard.Cms.Web.csproj...
  Restoring packages for C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-master\src\OrchardCore.Modules\Orchard.Commons\Orchard.Commons.csproj...
  Restoring packages for C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-master\src\OrchardCore.Modules\Orchard.Autoroute\Orchard.Autoroute.csproj...
  Restoring packages for C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-master\src\Orchard.Nancy.Web\OrchardCore.Nancy.csproj...
  Restoring packages for C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-master\src\OrchardCore.Modules\Orchard.Admin\Orchard.Admin.csproj...
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.http.features/index.json'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.net.http.headers/index.json'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.text.encodings.web/index.json'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.http.features/index.json'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.http.features/index.json'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.text.encodings.web/index.json'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.net.http.headers/index.json'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.aspnetcore.http.features/index.json'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
  Failed to download package 'AspNet.Security.OpenIdConnect.Extensions.1.0.0' from 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/aspnet.secur
ity.openidconnect.extensions/1.0.0/aspnet.security.openidconnect.extensions.1.0.0.nupkg'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
  Failed to download package 'AspNet.Security.OpenIdConnect.Extensions.1.0.0' from 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/aspnet.secur
ity.openidconnect.extensions/1.0.0/aspnet.security.openidconnect.extensions.1.0.0.nupkg'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error : Failed to download package 'AspNet.Security.OpenIdConnect.Extensions.1.0.0' from 'https://myget-2e16.kxcdn.com
/artifacts/aspnet-contrib/nuget/v3/flatcontainer/aspnet.security.openidconnect.extensions/1.0.0/aspnet.security.openidconnect.extensions.1.0.0.nupkg'.\r [C:\Users\Hengzhe Li
\Desktop\DevTools\Orchard2-master\Orchard.sln]
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error : An error occurred while sending the request.\r [C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-master\Orchard.s
ln]
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error :   The server returned an invalid or unrecognized response [C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-maste
r\Orchard.sln]
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.data.sqlclient/index.json'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.data.sqlclient/index.json'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error : Failed to retrieve information about 'System.Data.SqlClient' from remote source 'https://myget-2e16.kxcdn.com/
artifacts/aspnet-contrib/nuget/v3/flatcontainer/system.data.sqlclient/index.json'.\r [C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-master\Orchard.sln]
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error :   An error occurred while sending the request.\r [C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-master\Orchard
.sln]
C:\Program Files\dotnet\sdk\1.0.1\NuGet.targets(97,5): error :   The server returned an invalid or unrecognized response [C:\Users\Hengzhe Li\Desktop\DevTools\Orchard2-maste
r\Orchard.sln]
  Retrying 'FindPackagesByIdAsync' for source 'https://myget-2e16.kxcdn.com/artifacts/aspnet-contrib/nuget/v3/flatcontainer/microsoft.identitymodel.protocols/index.json'.
  An error occurred while sending the request.
    The server returned an invalid or unrecognized response
`

**Comment by li0803** [comment]
Sorry. It seems it is my network problem. I change another ISP and it works

**Comment by doublnt** [comment]
I have the same issue , I fix if also by change my proxy to Other country(Cause I am in China) eventually.
