### ISSUE TITLE
how to open orchard 2 on webmatrix?

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/Orchard2#866]
I couldn't open on webmatrix and visual studio ?
I installed .net core 2 preview
where can I find a video how to lunch it on my laptop with windows 10 client
![untitled](https://user-images.githubusercontent.com/20259070/27959266-fb2e1a66-633b-11e7-9962-7956e6760c37.png)

**Comment by agriffard** [comment]
Use Visual Studio 2017 or Visual Studio Code or dotnet CLI to restore and run.

**Comment by khoshroomahdi** [comment]
thank you 
but I try and I couldn't

**Comment by agriffard** [comment]
Orchard does not support .NET Core 2 Preview 2 yet. 
Install the LTS Version.
