### ISSUE TITLE
How to create module in Orchard2?

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/Orchard2#871]
I can create module and theme in orchard 1.10  with commandline. but i do not know how to do these in orchard2.

**Comment by Jetski5822** [comment]
@jnucpz we currently dont have any commands to do this in O2. its on the road map.

To create a module/theme in O2, create a module and reference ORchard.AsModule nuget package. Thats it. A dummy application is here for just pain modules. https://github.com/Jetski5822/ecom

**Comment by jnucpz** [comment]
thanks . i get it
