### ISSUE TITLE
Routing error with latest version

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#874]
When I launch the latest version of Orchard.Cms.Web, this exception occurs:

```
An unhandled exception occurred while processing the request.

InvalidOperationException: Unable to find the required services. Please add all the required services by calling 'IServiceCollection.AddRouting' inside the call to 'ConfigureServices(...)' in the application startup code.
Microsoft.AspNetCore.Routing.RouteBuilder..ctor(IApplicationBuilder applicationBuilder, IRouter defaultHandler)

```

In Microsoft.AspNetCore.Modules.ModularTenantRouteBuilder.Build() in src\OrchardCore\Microsoft.AspNetCore.Modules\ModularTenantRouteBuilder.cs
line 23:
            `var routeBuilder = new RouteBuilder(appBuilder)`

@Jetski5822 : Do you have any idea of what could have changed recently?

**Comment by Jetski5822** [comment]
@agriffard not sure, going to take a look now

**Comment by agriffard** [comment]
ShellFeaturesManager.cs fixed.
