### ISSUE TITLE
JSON Serialization

### ISSUE THREAD

**Issue by siyamandayubi** [OrchardCMS/Orchard2#88]
Hi,
Is there any new feature/changes regarding serializing Shapes and ContentItems into JSON in Orchard 2.0?

Regards,
Siyamand

**Comment by bleroy** [comment]
In Orchard 2, content items are natively JSON, so serialization will be pretty trivial. For shapes, I'm not sure why you'd want to do that, but I don't see why it would be especially difficult. Are you facing difficulties around that in Orchard 1? What's the scenario?

This not being a bug or a suggestion, I'm going to close this. Please use forums or the Gitter chat for questions like this one in the future. Thanks!
