### ISSUE TITLE
If re-implementing CoreShapes, please do List differently

### ISSUE THREAD

**Issue by CSurieux** [OrchardCMS/Orchard2#89]
Being able to use an inherance feature from an alternate as List.cshtml to call the corresponding CoreShape base  List.
Anyway we should be able to add alternates for CoreShapes without adding ShapeTables in code.

**Comment by bleroy** [comment]
Can you elaborate? What are the pain point and the proposed solution?

**Comment by CSurieux** [comment]
Bertrand, do you have a list of standard questions, I know this one a lot.

Well, there are no aternates for all those lists generated everywhere in Orchard, From your own old blogs the solution to offer different templates according the context of the list is not obvious: adding alternaates on the fly, adding a Shapetable to the Theme, rewiting the code from the CoreShape List class in List.cshtml (and some code on internet is no more sync with last changes).
For some lists I need a Bootstrape raw/col implementation rather than the default ul/li an it is tricky to find how to do it. I found a way for List of itemss using the same taxonomy term, but for tags no way (seems that the search view of Tag/HomeController can't be relocated under my theme...). 
This is an Orchard 1 Pb.

Hope it will be easier to select various implementations for list in Orchard 2. 

A fallback feature on Shapes could be nice.

**Comment by bleroy** [comment]
So is the problem that it is hard to override the shape and that it doesn't offer alternates out of the box?

**Comment by CSurieux** [comment]
In the actual implementation the items in the list could be anything, and in many orchard Display Drivers code the list are created without any differentiator which could be used to have adapted  layouts

**Comment by bleroy** [comment]
> In the actual implementation the items in the list could be anything

Yes. Are you saying that's a problem?

> in many orchard Display Drivers code the list are created without any differentiator which could be used to have adapted layouts

Yes, it would be the responsibility of the driver producing the list shape to add alternates that make sense. Do you have specific examples?

**Comment by CSurieux** [comment]
tags lists

**Comment by CSurieux** [comment]
and yes anything could be a problem, maybe different kind of List could help.

**Comment by bleroy** [comment]
OK, what kind of problem that adding ad-hoc alternates wouldn't solve, and what alternates would you like to see for tags? I agree it would be useful to add a list_tags alternate at least for this one.

**Comment by CSurieux** [comment]
Related to #90

**Comment by CSurieux** [comment]
Even if #90 has been close, the discussion on the more general point it opens, continues on the 'Close Side of Orchard 2'.
