### ISSUE TITLE
Page should have a Flow by default

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#893]
For the same reason Page has a Layout part in O1 we should have Flow part by default on a Page.
I see a Page as something very flexible, as opposed to something like and Article or a Company which should probably only be based on specific fields and parts.

A Page relies on the notion that something is accessible from a URL but completely customizable. This is typically what should be used for a home page, or specific hub main pages. It would query other contents on the site, and organize the content freely (services, list of recent news, any other widget).

**Comment by Jetski5822** [comment]
Yup - Do it, and ditch Flow Page.

**Comment by agriffard** [comment]
Done in agency and blog recipe.
