### ISSUE TITLE
Admin Template: Preview button

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#900]
When you create or Edit a Template, the Preview button is not useful.

**Comment by agriffard** [comment]
See also #481 for similar behavior to fix.

**Comment by sebastienros** [comment]
I don't understand the issue. It's super useful !

**Comment by agriffard** [comment]
I didn't understand the purpose when I was editing a `Widget__ImageWidget` template.

**Comment by agriffard** [comment]
I use this issue for another problem then:
I created a tenant called 'agency'.
When I click on the preview button, it opens http://localhost:2918/agency/Orchard.Templates/Preview/Index and a Bad Request erro happens :
```
Bad Request - Request Too Long

HTTP Error 400. The size of the request headers is too long.
```
and any url returns this error (on main site or tenant).

**Comment by sebastienros** [comment]
Issue with the cookies, I still need to clean them, but looks like they are too big on your system

**Comment by sebastienros** [comment]
If you are using IIS it might be limited to 16KB

**Comment by agriffard** [comment]
I still have this error when I edit the template `Content__LandingPage` of TheAgencyTheme in the admin after an install of OrchardCore as a nuget package.
