### ISSUE TITLE
Does modules functionality works with Razor Pages?

### ISSUE THREAD

**Issue by xperiandri** [OrchardCMS/Orchard2#907]

**Comment by sebastienros** [comment]
Not yet but very very soon. We have a branch to upgrade to netcore 2.0 and as part of the MVC team I made sure that it would work in Orchard Core by reporting limitations early enough. I think this will be a great addition as developers will be able to create custom pages very easily without the need to create new modules, while being able to reuse the content items, search and other dynamic queries. You should be able to try the netcore2 branch already and test it.

**Comment by agriffard** [comment]
#943 merged : Razor Pages
