### ISSUE TITLE
loading custom module js/css resources

### ISSUE THREAD

**Issue by etcetraw** [OrchardCMS/Orchard2#909]
I hope its ok to post a question here. 
Does not matter what path I use, i am getting 404 for module js/css files. 
Themes use /module/content/bla.js, that does not work for a custom module. What am I missing? 
Thanks for your help in advance.

**Comment by sebastienros** [comment]
It works for any module as long as you put your assets in the `Content` folder. Then the public path is `ModuleName/Filename`, you don't have to specify `Content`.

**Comment by etcetraw** [comment]
That works, thank you very much.
