### ISSUE TITLE
Modules/Themes organization

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#91]
I'd keep the current folders, `Themes` and `Modules`, but would not make an assumption on what they contain, and also have these folder only because they are defined in the configuration so that people can put everything in `Extensions` if they want. The manifest name would make the distinction: `theme.json` and `module.json` as they might have different schemas.

**Comment by Jetski5822** [comment]
We have a Manifest Parser that allows you have whatever format you want.

You can also specify the Manifest name and type is the host

> services.AddManifestDefinition("Theme.txt", "theme");

You can also have whatever folders you want as its based on wildcard searching

> services.AddExtensionLocation(Path.Combine("App_Data", "Sites", "**", "Themes", "**"));
