### ISSUE TITLE
When the first release? 

### ISSUE THREAD

**Issue by yahue** [OrchardCMS/Orchard2#92]
There are schedule in this respect it?

**Comment by BenedekFarkas** [comment]
There is no scheduled release date at this point. The framework is still undergoing additions/improvements and there are no user features at this point either, although you can already start using in some specific scenarios if you want to build upon the framework aspect of Orchard.

I suggest following the website for updates about Orchard 2, we've started making Orchard 2 a recurring part of the weekly meetings to announce updates and new features.

I'm closing this as it's not an issue. If you have questions, please visit the [forums](http://orchard.codeplex.com/discussions) or chat on [Gitter](https://gitter.im/OrchardCMS/Orchard2).
