### ISSUE TITLE
Can you support MongoDB?

### ISSUE THREAD

**Issue by dataangel** [OrchardCMS/Orchard2#922]
Provides high-perfomance data access

Identity.MongoDB
https://github.com/tugberkugurlu/AspNetCore.Identity.MongoDB

**Comment by pgy866** [comment]
What advantage does MongoDB OrchardCMS support it?

**Comment by etcetraw** [comment]
https://www.youtube.com/watch?v=D42eK6CJjF4
Orchard harvest 2017 - YesSql
Sebastien discussed MongoDb in this video

**Comment by sebastienros** [comment]
Short answer, not possible technically.

**Comment by RockNHawk** [comment]
@sebastienros @dataangel 
Mongodb now supports transactions. Is it possible for Orchard to support mongodb now?

**Comment by hishamco** [comment]
> Mongodb now supports transactions. Is it possible for Orchard to support mongodb now?

You can post your question in [YesSql](https://github.com/sebastienros/yessql/) repo
