### ISSUE TITLE
Agency theme

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/Orchard2#923]
@sebastienros : I could wait for you to make a pull request on the Agency theme to comment on it but I already tested it so here are some remarks.

Images src:
I saw you can include an image in Base64 from the recipe but it would be easier if we could have a Media Step to copy the images from TheAgencyTheme to the Media folder.
	
Content types:
All mediaField in content types that are in Bags of the Landing page have a `required `setting.
So it generates a error when we save the page and that a media is missing : `A media is required.`

Login:
Missing `<div class="container">` around the content so it is not well aligned.

Bag:
- + buttons appear when you expand a sub item. 

Footer
`Content:` appears in the footer.

Template LandingPage:
`Start Bootstrap` should be `{{ site.SiteName }}`

**Comment by sebastienros** [comment]
Some of these bugs are the reason why I didn't submit a PR yet. But some other I didn't know of, thanks.

**Comment by sebastienros** [comment]
Everything in this list should be fixed now. The {{ site.name }} thing will wait for jt's branch.

**Comment by agriffard** [comment]
About the contact form that sends an email, tell me if I am wrong, but can this be a solution? :
When the migration to DotNet Core 2.0 is done, we can use Razor pages in modules and themes so can we make a Page that sends an email like this example : 
http://asp.net-hacker.rocks/2017/07/26/razor-pages-email-form.html

It will also be easier and configurable when the email module and smtp settings will be available.
Even better if there is a Contact Content type or a dynamic form module and a workflow activity with a liquid template that can used to format the message.

**Comment by sebastienros** [comment]
Yes, we will be able to make a razor page. Note that we can already create a controller if we want to in the theme. We need settings though even if we don't have the smtp module.
I might do something quickly to support custom settings, I have an idea where we can use a "Settings" stereotype so that this type would be a settings tab. And because site settings are available in templates that would allow us to do such things in the recipe.

**Comment by sebastienros** [comment]
I pushed a new module to handle custom settings. Create a type and give it "CustomSettings" stereotype.

**Comment by agriffard** [comment]
I add a CustomSettings steretotype on Blog.

When I display the content on front:
`Exception: Shape type 'CustomSettings' not found`

When I display the content items in admin:
`Exception: Shape type 'CustomSettings_SummaryAdmin' not found.`

When I edit the item in admin :
`Exception: Shape type 'CustomSettings_Edit' not found.`

In CustomSettingsDisplayDriver.cs line 63: It doesn't work even if I replace `CustomSettings `by `CustomSettings_Edit`
`var shape = Shape<CustomSettingsEditViewModel>("CustomSettings_Edit", async ctx =>`
