### ISSUE TITLE
AdminMenu.cs  have some bug.

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/Orchard2#928]
AdminMenu.cs  do not have Url, In NavigationHelper.cs

```
   public static dynamic BuildMenuItemShape(dynamic shapeFactory, dynamic parentShape, dynamic menu, MenuItem menuItem, ViewContext viewContext)
        {
            var menuItemShape = shapeFactory.NavigationItem()
                .Text(menuItem.Text)
                .Href(menuItem.Href)
            
                .LinkToFirstChild(menuItem.LinkToFirstChild)
                .RouteValues(menuItem.RouteValues)
                .Item(menuItem)
                .Menu(menu)
                .Parent(parentShape)
                .Level(parentShape.Level == null ? 1 : (int)parentShape.Level + 1)
                .Local(menuItem.LocalNav);
```

**Comment by sebastienros** [comment]
I added it, but not that you are supposed to use `Href` instead.

**Comment by jnucpz** [comment]
thanks. In AdminMenu.cs， if builder.add("demo",cee=>cee.Url("http://ddddddddddd.com")),it have wrong, in admindashboad it can not  show this menu.
  public void BuildNavigation(string name, NavigationBuilder builder)
        {
            if (!String.Equals(name, "admin", StringComparison.OrdinalIgnoreCase))
            {
                return;
            }

            builder
                .Add(T["Demo"], "10", themes => themes
                    .AddClass("demo").Id("demo")
                    .Add(T["This Menu Item 1.1"], "0", installed => installed
                        .Add(T["This is Menu Item 1.1"],"1",cee=>cee.Url("http://ddddddddddd.com"))
