### ISSUE TITLE
[Announcement] Integration branch

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#932]
/cc @alexbocharov @agriffard @Jetski5822 @jtkech 
/bcc @PinpointTownes @jersiovic

I am about to merge the most important branches in a `dev` branch to check everything is working fine without breaking master, and also to be able to revert some of these in case there is a major issue. dev to master won't be squashed to retain the branch commits. But each PR will as our usual process.

Please don't be too active on them until it's done, then we can continue based on master.

**Comment by PinpointTownes** [comment]
Nice. Will this branch include the 1.x -> 2.x migration PRs?

**Comment by sebastienros** [comment]
@PinpointTownes  yes

**Comment by jtkech** [comment]
> Please don't be too active ...

I think i can do it ;)

**Comment by sebastienros** [comment]
I merged NET Core 2.0, Liquid Views and The Agency recipe in dev already and it works

I have a bug with YesSql and the Blog recipe I need to understand.
JT mentioned a bug with templates persistence.
Feel free to test the dev branch and issue PRs.

**Comment by agriffard** [comment]
The media are not rendered on Admin, Front or Tenants.
I can upload a file and it is correctly saved in File system but I can't display it when I call the url.

**Comment by sebastienros** [comment]
@agriffard found the issue with images, there is a bug in ImageSharp on netcore2.0, I will update to the latest which is supposed to resolve this.

**Comment by sebastienros** [comment]
@agriffard Fixed the image resize feature

**Comment by agriffard** [comment]
The images work if they are .jpg but not with png or bmp files.

**Comment by dodyg** [comment]
If I want to try Orchard 2, which branch should I use today?

**Comment by alexbocharov** [comment]
@dodyg I recommend the master branch
