### ISSUE TITLE
Find out why ISiteService can't be a singleton

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/Orchard2#942]
Make this PR work https://github.com/OrchardCMS/Orchard2/pull/941

**Comment by jtkech** [comment]
So, it seems that, in the context of a new shellcontext scope, a service may have issues to use `IHttpContextAccessor` to resolve scoped services.


So, i could get it working by doing this in several places in `SetupService` and `RecipeExecutor`.

    using (var scope = shellContext.CreateServiceScope())
    {
        var httpContextAccessor = scope.ServiceProvider.GetRequiredService<IHttpContextAccessor>();
        var existingServices = _httpContextAccessor.HttpContext.RequestServices;
        httpContextAccessor.HttpContext.RequestServices = scope.ServiceProvider;
        ...
        ...
        httpContextAccessor.HttpContext.RequestServices = existingServices;
    }

    // Also here at the end of SetupInternalAsync()
    using (var shellContext = await _orchardHost.CreateShellContextAsync(shellSettings))
    {
    }

So, if we can do something like this, maybe good to make it in the `CreateServiceScope()` method.
