### ISSUE TITLE
Missing nupkg files when building from dev branch

### ISSUE THREAD

**Issue by MichaelPetrinolis** [OrchardCMS/Orchard2#948]
Playing with dev branch, I was not able to update a test app to the produced packages.

With net core 2 the default behavior for projects that use Microsoft.NET.Sdk.Web
is not to pack by default and the CLI does not report an error(https://github.com/aspnet/websdk/pull/165)

So the IsPackable property should be added in each csproj, or in OrchardCore.Commons.props

**Comment by sebastienros** [comment]
Let's see if we can remove Microsoft.NET.Sdk.Web now. We did it just for intellisense.
But maybe simpler to just add the property, just in case the editor issue is not fixed everywhere.

**Comment by sebastienros** [comment]
Could you point to such a project? I can see all of them generated when I do dotnet pack at the solution level

**Comment by MichaelPetrinolis** [comment]
Sure, Orchard.Contents. I have copied the demo module in order to test, and it references orchard.contents which is not packed.

**Comment by jtkech** [comment]
Just tried `Sdk="Microsoft.NET.Sdk"`, now it works for razor intellisense.

Would be good to do, then we could also remove

    <EnableDefaultContentItems>false</EnableDefaultContentItems>
    <OutputType>Library</OutputType>

@sebastienros

And i also think that it will not add unwanted things when we have a `/Pages` subfolder in a module.
