### ISSUE TITLE
Cannot resolve 'System.Collections.Generic.IEnumerable`1[YesSql.Indexes.IIndexProvider]' from root provider because it requires scoped service 'YesSql.Indexes.IIndexProvider'.”

### ISSUE THREAD

**Issue by yiji** [OrchardCMS/Orchard2#961]
update to latest,build success,run report a bug,Cannot resolve 'System.Collections.Generic.IEnumerable`1[YesSql.Indexes.IIndexProvider]' from root provider because it requires scoped service 'YesSql.Indexes.IIndexProvider'.”

**Comment by alexbocharov** [comment]
Please, show the full error log

**Comment by yiji** [comment]
the problem is sloved, in my module i use services.AddScoped<IIndexProvider,T>(),should use services.AddSingleton<IIndexProvider, T>();
