### ISSUE TITLE
Consider removing the OpenID module from the built-in SaaS recipe

### ISSUE THREAD

**Issue by PinpointTownes** [OrchardCMS/Orchard2#971]
It's not clear to me why the OpenID module is enabled by default for the SaaS recipe.

@sebastienros @jersiovic is there any particular reason for this?

**Comment by jersiovic** [comment]
There is not an strong reason. It was a decissión taken for not hiding to new comers a relevant feature of Orchard for their apps.

**Comment by sebastienros** [comment]
I think I already removed it in dev ... will have to check though

**Comment by PinpointTownes** [comment]
I'm tempted to say no, assuming this sort of things is still configured in the `recipe.json` files: https://github.com/OrchardCMS/Orchard2/blob/dev/src/OrchardCore.Cms.Web/Recipes/saas.recipe.json#L26

**Comment by PinpointTownes** [comment]
Done by @sebastienros: https://github.com/OrchardCMS/Orchard2/commit/8d78c6761297d2198c7a101b4179e28fe67f3651.
