### ISSUE TITLE
Content type widget which contain list part can not be managed.

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/Orchard2#980]
if i define a content type which contian list part, this type is widget.  in contentitem,it can not editor.
example for:
![blog](https://user-images.githubusercontent.com/17457950/30194435-c14af9a6-9485-11e7-91cb-673dac415388.png)

if you create a new blog,it will not be shown. and the blog can not be eidtor.

**Comment by jnucpz** [comment]
i want the layer add a widget contains a type ,this type have list part. what should i do?

**Comment by sebastienros** [comment]
If it's a `Widget` then it can't be ` ContentItem` and edited. So you shouldn't add it on `Blog`.

I don't understand what you are trying to do. You can't add a **type** to a layer, you can just add a widget instance. If you want a widget to behave like a list of things, I would suggest you create a new type, let's say `MyList` then add a `Bag` part to it, and in the `Bag` part setting select the type of element you want it to contain, like `MyListItem`. This way your widget will own all the content, and you can customize it.

**Comment by jnucpz** [comment]
Thank you for your answer. I want to show two or more blog on the same single page. 
a single page contains two blog and have respective blogpost list. what should i do ?

**Comment by sebastienros** [comment]
I would suggest to create two SQL queries like `RecenteBlogPost`, then create a Liquid Page to render a custom page that uses these queries, or use widgets with Liquid Widgets if they need to be displayed on several pages.

**Comment by jnucpz** [comment]
Thank you for your solution. it works .thank you
