### ISSUE TITLE
Promote the docs site from this GitHub project site

### ISSUE THREAD

**Issue by jeremycook** [OrchardCMS/Orchard2#983]
I think it would be helpful to link to https://orchardcore.readthedocs.io from the project Readme.md, the GitHub project description, and/or the GitHub wiki homepage.

I had trouble finding the docs by browsing the GitHub project, orchardproject.net, and googling. My mistake was that I used Google to search for "orchard 2 docs," which didn't help. However, searching for "orchard core docs" did work.

**Comment by sebastienros** [comment]
Fixed
