### ISSUE TITLE
Setup Page : Elements were disappeared after database connect fails twice.

### ISSUE THREAD

**Issue by YaoaY** [OrchardCMS/Orchard2#987]
An error occured after i clicked the Finish Setup.
That was because i forgot create the database which in my connection string,like this one:

> Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=Orchard2;Connect Timeout=30;

but i didn't realize it ,and just tried again.

Of cause the error occured again, but this time some elements in this setup page were disappeared.

So i can't continue setup until restart the application.

![2017-09-10 1](https://user-images.githubusercontent.com/8706312/30247639-74e50b20-964b-11e7-8197-f9335da7882d.png)

reload page doesn't restore them unless restart app:
![2017-09-10 2](https://user-images.githubusercontent.com/8706312/30247692-38099968-964c-11e7-9310-b84d48c6c0eb.png)

Sorry for my english, i hope you can understand what i'm saying. :joy:

**Comment by agriffard** [comment]
Duplicate of #944
I confirm the problem occurs, I tested the setup with a wrong password in the connection string on purpose and then the connectionstring and the database prefix disappear.

**Comment by YaoaY** [comment]
OK.
