### ISSUE TITLE
how to get settings for my service class in O2

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/Orchard2#988]
now I only can borrow the idea from 
var contentTypeDefinition = _contentDefinitionManager.GetTypeDefinition("**Menu**");
            if (!contentTypeDefinition.Settings.ToObject<ContentTypeSettings>().Draftable)

inside public class AdminController of namespace Orchard.Menu.Controllers.

but notice something like  "Menu" is hard code inside my service class.

in O1, I can use IWorkContextAccessor or IOrchardServices to get settings.
for example:
_orchardServices.WorkContext.CurrentSite.As<**CloudMediaSettingsPart**>().IsValid()

**Comment by sebastienros** [comment]
`ISite` is not a content item anymore in OC, but it's extensible as it's a JSon document.

Here is an example:
https://github.com/OrchardCMS/Orchard2/blob/8d78c6761297d2198c7a101b4179e28fe67f3651/src/OrchardCore.Modules/OrchardCore.Lucene/LuceneIndexingService.cs#L161

You'll find how to create a custom driver in the same module.
